### ISSUE TITLE
Improve computation for compensation

### ISSUE THREAD

**Issue by kevinushey** [RGLab/flowCore#10]
Currently, compensation is applied as (in [flowFrame-accessors](https://github.com/RGLab/flowCore/blob/trunk/R/flowFrame-accessors.R#L443)):

    e[, cols] <- t(solve(t(spillover))%*%t(e[,cols]))

This is equivalent to computing:

    e[, cols] <- e[, cols] %*% solve(spillover)

and avoids a lot of un-necessary transposes.

Test code just to make sure:

    library(flowCore)
    
    ## example from flowCore
    samp <- read.flowSet(path=system.file("extdata", "compdata", "data", package="flowCore"))
    cfile <- system.file("extdata","compdata","compmatrix", package="flowCore")
    comp.mat <- read.table(cfile, header=TRUE, skip=2, check.names = FALSE)
    spillover <- as.matrix(comp.mat)
    x <- samp[[1]]
    
    ## take only the columns of e that are in the spillover matrix
    cols <- colnames(spillover)
    sel <- cols %in% colnames(x)
    e <- exprs(x)
    
    all.equal( 
      t(solve(t(spillover)) %*% t(e[,cols])), ## old
      e[,cols] %*% solve(spillover) ## new
    )

**Comment by mikejiang** [comment]
This speeds up compensation by `20%` immediately 
```r
Unit: milliseconds
                         expr      min       lq     mean   median     uq      max neval
 compensate(comp.fs1, comp.mat) 25.05346 30.31677 43.33896 32.78508 36.792 157.1661    50                          
 compensate(comp.fs1, comp.mat) 24.37472 26.6198 33.1542 27.92868 29.94891 134.4084    50
