### ISSUE TITLE
flowCore sort() breaks BiocGenerics sort()

### ISSUE THREAD

**Issue by LTLA** [RGLab/flowCore#101]
As described in Bioconductor/Biostrings#7; _flowCore_ seems to define its own `sort` generic, which ends up breaking the `sort` generic in the BioC-devel version of _BiocGenerics_. Presumably this is an easy fix by just importing and using `BiocGenerics::sort` instead.

**Comment by gfinak** [comment]
Oddly I can't reproduce this either under devel or 3.6 release. Happy to import BiocGenerics::sort but can't confirm it's a fix.

**Comment by LTLA** [comment]
Thanks Greg, looks like that fixed it.
