### ISSUE TITLE
Changing channel description in a flowSet

### ISSUE THREAD

**Issue by jchellmuth** [RGLab/flowCore#102]
It's easy renaming channels in a flowSet, for example:
`colnames(fs)[colnames(fs)=="FITC.A"] <- "AF488"`
`colnames(fs)[colnames(fs)=="Pacific.Blue.A"] <- "BV421"`

However, I don't see a straightforward way to change the channel description for all flowFrames in a flowSet. I am currently looping through the flowSet to rename each channel using the parameters function:
`for (i in 1:length(fs)){`
`parameters(fs[[i]])@data$desc[parameters(fs[[i]])@data$name=="AF488"] <-  "CD11"`
`parameters(fs[[i]])@data$desc[parameters(fs[[i]])@data$name=="BV421"] <-  "CD4"`
`}`

Is there a more elegant and efficient way to change the channel description in a flowSet ?

**Comment by gfinak** [comment]
The `markernames()<-` method should do what you want.
However it is currently misbehaving:

```
 fs = flowSet(replicate(10,flowFrame(matrix(rnorm(100),ncol=5,dimnames=list(NULL,
> nms= letters[1:5]
> names(nms)=colnames(fs)
> markernames(fs)=nms
Warning messages:
1: In `[<-.factor`(`*tmp*`, iseq, value = c("a", "b", "c", "d", "e" :
  invalid factor level, NA generated
2: In `[<-.factor`(`*tmp*`, iseq, value = c("a", "b", "c", "d", "e" :
  invalid factor level, NA generated
3: In `[<-.factor`(`*tmp*`, iseq, value = c("a", "b", "c", "d", "e" :
  invalid factor level, NA generated
4: In `[<-.factor`(`*tmp*`, iseq, value = c("a", "b", "c", "d", "e" :
  invalid factor level, NA generated
5: In `[<-.factor`(`*tmp*`, iseq, value = c("a", "b", "c", "d", "e" :
  invalid factor level, NA generated
6: In `[<-.factor`(`*tmp*`, iseq, value = c("a", "b", "c", "d", "e" :
  invalid factor level, NA generated
7: In `[<-.factor`(`*tmp*`, iseq, value = c("a", "b", "c", "d", "e" :
  invalid factor level, NA generated
8: In `[<-.factor`(`*tmp*`, iseq, value = c("a", "b", "c", "d", "e" :
  invalid factor level, NA generated
9: In `[<-.factor`(`*tmp*`, iseq, value = c("a", "b", "c", "d", "e" :
  invalid factor level, NA generated
10: In `[<-.factor`(`*tmp*`, iseq, value = c("a", "b", "c", "d", "e" :
  invalid factor level, NA generated
```

@mikejiang could you have a look ?

**Comment by gfinak** [comment]
I'll reopen the issue until I get confirmation it's fixed.

**Comment by mikejiang** [comment]
@gfinak , I made some adjustment based on your patch to avoid this
```r
nms= letters[1:2]
names(nms)=LETTERS[1:2]
markernames(fs)=nms
pData(parameters(fs[[1))
    name desc    range   minRange maxRange
$P1    A    a 3.151028 -2.1254943 3.151028
$P2    B    b 2.358097 -1.5093466 2.358097
$P3    C    3 2.159559 -1.7648019 2.159559
$P4    D    4 2.033268 -1.6171635 2.033268
$P5    E    5 2.534455 -0.6385325 2.534455
```
where some markers became integer values when only a subset of markers are updated. 

It should be good now.

**Comment by gfinak** [comment]
Thanks.
