### ISSUE TITLE
 introducing channel "aliases"

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowCore#103]
per request by @gfinak and @mimisikai in RGLab/cytoUtils/issues/2
The most straightforward way is to introduce the `channel_alias` argument to `read.FCS/ read.flowSet` so that the channel names are normalized during the initial FCS parsing thus has zero side effects on the downstream pipelines.
e.g. manually supply the `alias vs channel options` mapping as a `data.frame`
```r
map <- data.frame(alias = c("FITC", "V450")
                  , channels = c("FITC, GFP, Alexa 488", "BV421, V450, ef450")
                  )

```
or it can be read from csv file

alias|channels
-- | --
FITC | FITC, GFP, Alexa 488
V450 | BV421, V450, ef450

```r
fs <- read.flowSet(files, channel_alias = map)
```

**Comment by mikejiang** [comment]
@mimisikai, I've pushed the enhancement. You will need to install trunk branch for both `flowCore` and `ncdfFlow`. i.e `devtools::install_github("RGLab/flowCore", ref = "trunk')`

**Comment by mikejiang** [comment]
@mimisikai, I've added the additional message to show the channels that are dropped due to the discrepancy across samples. e.g.
```r
> fs <- read.ncdfFlowSet(c(fcs1,fcs2))
Not all FCS files have the same channels

Only load the following common channels:
FSC-H
SSC-H
FL2-H
FL2-A
FL4-H
Time
Skipped the channels that are not found in all samples:
FL11-H
FL33-H
FL1-H
FL3-H
write file34014e181cc9 to empty cdf slot...
write file34011fa183d2 to empty cdf slot...
done!
```
Please install the latest `ncdfFlow` and give it a try

**Comment by mimisikai** [comment]
The samples can be read. But, two more questions show up.
1. When autoplot individual sample, the parameter of each x-axis is still
the sample own channel, not the normalized common channel.
2. May the same reason, when do the compensation, the error info shows, for
instance:

Error: The following parameters in the spillover matrix
 are not present in the flowFrame:
Alexa Fluor 488-A, ef450-A, APC-A

**Comment by mikejiang** [comment]
The latest commits :
1. spillover is synced with new alias
2. support partial and case insensitive matching for `channel names` in mapping. i.e. `alexa fluro 488` is also a valid entry

**Comment by mikejiang** [comment]
@mimisikai , I've added the validity checks to report the diagnostic error information on the conflicting aliasing issue.e.g.
```r
> fr <- read.FCS(fcsfile, channel_alias = data.frame(alias = c("FL1", "FL3"), channels = c("B710-A,V545", "R780-A")))
     orig_channel_name new_channel_name
$P5N            B710-A              FL1
$P9N            V545-A              FL1
 Error in update_channel_by_alias(cn, channel_alias) : 
  channel_alias: Multiple channels from one FCS are matched to the same alias! 
```

**Comment by Minh084** [comment]
I have an fcs 3.0 file where we have the original channel names and new channel names are all the same. So, I couldn't see mapping as described above. 
Some people who read the same file before in flowCore and didn't get this error message that I have now. I'd appreciate any thoughts on how to handle this
<img width="574" alt="Screen Shot 2019-10-22 at 9 23 19 AM" src="https://user-images.githubusercontent.com/5348000/67307669-b255d580-f4ad-11e9-8dbd-784cce996b1f.png">

When viewing the file, here's "treatment" appeared x4:
<img width="502" alt="Screen Shot 2019-10-22 at 9 59 51 AM" src="https://user-images.githubusercontent.com/5348000/67310542-cf40d780-f4b2-11e9-8f03-2b4455c8d083.png">

**Comment by mikejiang** [comment]
It should have been taken care of by #161. Did you try the latest trunk version?

**Comment by Minh084** [comment]
I did update to the latest trunk version from your earlier suggestion. My problem is exactly as [#159](https://github.com/RGLab/flowCore/issues/159). I've read [#161](https://github.com/RGLab/flowCore/issues/161), but it doesn't seem to me like a solution to this problem, esp when the channels are also the same.

**Comment by mikejiang** [comment]
Again, the latest flowCore reads your fcs with no error
```r
> fr <- read.FCS("~/Downloads/A_BASALHeLa.fcs", transformation = F)
      orig_channel_name new_channel_name
$P40N         treatment      treatment-1
$P41N         treatment      treatment-2
Warning message:
In update_channel_by_alias(cn, channel_alias) : 
channel_alias: Multiple channels from one FCS are matched to the same alias!
Integer suffixes added to disambiguate channels.
It is also recommended to verify correct mapping of spillover matrix columns.
```
Make sure to reinstall your package by `devtools::install_github("RGLab/flowCore", ref = "trunk")` without error and then give it another try

**Comment by Minh084** [comment]
I re-installed from github and that worked instead of installing the flowCore from Bioconductor and the trunk separately. No longer getting the read error. Thank you!
