### ISSUE TITLE
Importing .fcs files into shiny application

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowCore#107]
On 04/16/2018 04:00 AM, Dillon Hammill wrote:
>
> Hi Mike,
>
>  
> I am trying to load and read in multiple .fcs files into a shiny application but experiencing little success.
>
>  
>
> Do you know how to pass files loaded by fileInput into a flowSet that can be manipulated?
>
>  
>
> Please have a look at the attached app.R file if you have time.
>
>  
>
> Thanks again for all your help.
>
>  
>
> Kind regards,
>
>  
>
> Dillon
```r
library(shiny)
library(CytoGate)
library(flowDensity)
library(openCyto)
library(ggcyto)


ui <- fluidPage(

   titlePanel("Upload .fcs files:"),

   sidebarLayout(
      sidebarPanel(
         fileInput(inputId = "Samples",
                   label = "Select Samples",
                   multiple = TRUE,
                   accept = ".fcs")
      ),

      mainPanel(
         textOutput("names")
      )
   )
)


server <- function(input, output) {

   files <- reactive({
     test <- read.flowSet(path = input$Samples$datapath, pattern = ".fcs")
   })

   output$names <- renderText({
     sampleNames(test)
   })
}

shinyApp(ui = ui, server = server)

```

**Comment by mikejiang** [comment]
@DillonHammill, without the error message I can't tell what exactly went wrong. You can simply set breakpoint at `read.flowSet` line (e.g. by inserting `browser()` before it ) and inspect the value of `input$Samples$datapath` at runtime to see if it points to the right FCS folder.
BTW, it will be more efficient to replace it with `read.ncdfFlowSet` if you have many samples

**Comment by SamGG** [comment]
@DillonHammill, no idea about your error but a short remark about shiny apps. Shiny applications are using HTTP protocol, meaning that any file is transferred over internet even if internet is reduced to a network loop on your own computer. There is an overhead of file transfer and file duplication. If the application is written for a user who is going to analyse files on his/her computer or local network, I think the [shinyFiles package](https://github.com/thomasp85/shinyFiles) should be used in place. This package allows one to get the file path in the computer or local network environment. Moreover, it is very easy to switch from shinyFiles to the shiny file browser, so give it a try.
HTH

**Comment by DillonHammill** [comment]
Thank for the help guys!

Does read.flowSet expect a path to a folder to the "path" argument? 

I have had a look at input$Samples$datapath which provides the paths to each file, maybe I have to extract the path to the folder?

Regarding shinyFiles is it possible to browse all directories like in fileInput? I have used `volumes = getVolumes()` on the server side which takes a while to check access for each deirectory? Is there a better way of doing this without having to exclude a number of directories in `getVolumes()`?

Thanks for your help!

Dillon

**Comment by mikejiang** [comment]
If you already have full path to each file, then you should pass it directly to the first argument `files`
`read.flowSet(files = input$Samples$datapath`

**Comment by DillonHammill** [comment]
This seems to have worked:
```{r}
library(shiny)
library(openCyto)

ui <- fluidPage(

  titlePanel("Upload .fcs files:"),

  sidebarLayout(
    sidebarPanel(
      fileInput(inputId = "Files",
                label = "Select Samples",
                multiple = TRUE,
                accept = ".fcs")
    ),

    mainPanel(
      textOutput("names"),
      textOutput("test"),
      tableOutput("Samples"),
      tableOutput("exprs")
    )
  )
)

server <- function(input, output) {

    data <- reactive({
       read.flowSet(files = input$Files$datapath)
    })

  output$names <- renderText({
    req(input$Files)
    print(class(data()))
  })

  output$test <- renderText({
    req(input$Files)
    print(sampleNames(data()))
  })

  output$exprs <- renderTable({
    req(input$Files)
    DT::renderDataTable(exprs(data())) # Not sure how to subset data()
  })
}

shinyApp(ui = ui, server = server)
```


So I have now made the data() containing the flowSet, how do I extract individual flowFrames from this object? I am not sure how to subest this object....

Also it seems that the original sample names (xyz.fcs) have been replaced with numbers (e.g. 1.fcs) is it possible to keep original names? I thought this was the default behaviour for read.flowSet?

Thanks again!

**Comment by SamGG** [comment]
@DillonHammill concerning your questions about shinyFiles, no idea, you have to experiment or post it to Thomas who is reactive.

**Comment by mikejiang** [comment]
If you have issues about read.flowSet I suggest you to provide a minimum self-contained example by stripping the shiny context because this is really not a place to answer shiny questions.

**Comment by DillonHammill** [comment]
Thanks for your help guys I have solved the problem. Shiny `fileInput` renames files in `input$Files$datapath` but not `input$Files$name`. So the naming issue can be resolved by setting `sampleNames(fs) <- input$Files$name`.

We can now close this issue.
