### ISSUE TITLE
write.FCS sometimes modifies values

### ISSUE THREAD

**Issue by dtebaykin** [RGLab/flowCore#109]
I am using a concatenation function to merge several FCS files together that eventually uses flowcore::write.FCS to create the single FCS file. However, for channels with high values it sometimes squishes them. Example:

table(merged_file[1:nrow(file_1),]==file_1)
 FALSE    TRUE 
20919   1455703

The incorrect values mostly come from one channel, but not all of them. Here are first 10 entries from first file before and after concatenation:
Before: 120.44368 379.92374 198.61490 177.37033  82.66682 157.71584  92.34710 177.13588  97.67022  87.81115
After: 98.00000 98.00000 98.00000 98.00000 82.66682 98.00000 92.34710 98.00000 97.67022 87.81115

**Comment by mikejiang** [comment]
I am not aware of this behavior of `write.FCS`, if you can provide an example `flowFrame` object I can look into it.

**Comment by dtebaykin** [comment]
Upon more careful examination, the problem is not in the write.FCS, but right before it. I am using the following line of code:
cell.flowFrame <- flowFrame(as.matrix(cell.data), 
                              parameters = parameters(file.fcs), 
                              description = description(file.fcs))
I am not creating the description object properly when concatenating multiple files. Setting description to the description of the first file in the set of concatenated FCS files makes the test in my first post pass, but it does not work for the rest of the FCS files.

Is there a proper way to create a description object for the concatenated FCS file?

**Comment by mikejiang** [comment]
I am not sure what is working and what is not working here. Where did exactly truncation happen?

**Comment by dtebaykin** [comment]
I am trying to create one big FCS file out of several smaller FCS files, but I am not updating the "description" of the big FCS file properly. I don't see a function in flowCore that could do this task, is there one?

**Comment by mikejiang** [comment]
I don't see the truncation problem by executing your wrapper function on the collapsed data
```r
> data(GvHD)
> fs <- GvHD[1:3]
> fr <- as(fs, "flowFrame")
> tmp <- tempfile()
> writeCytofFCS(fr@exprs, tmp)
[1] "/tmp/RtmpLE8LSR/file316c38954bbd"
> 
> fr1 <- read.FCS(tmp)
> all.equal(fr@exprs, fr1@exprs, check.attributes = F, tol = 3e-8)
[1] TRUE
```

**Comment by gfinak** [comment]
@dtebaykin is this issue resolved?

**Comment by dtebaykin** [comment]
Yes, @SamGG was right, the issue occurred during the reading of the concatenated FCS file since it did not have max_range values updated properly. Thank you.
