### ISSUE TITLE
writing a subsetted a flowframe leads to an incorrect FCS file

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#110]
Hi,
While trying to build a minimal code for an issue, I came out to the following problems.
I subset a flowframe, but the keywords seem not to be correctly subsetted or written. Viewing the stored FCS file, I notice that the parameter following the one deleted has no $PxB keyword, but its previous $PxB remains. In fact, all the keywords associated with the previous index are still present. I didn't check removing other parameters than the N-1.
Alternatively, positive selection does not result in the same keywords as negative selection.
I hope the following code should be self-explanatory. If not, let me know.
Thanks for maintaining this invaluable package.

Code to reproduce (same result with flowcore v1.44.2)
```
# Configure
temp.dir = "C:/temp"

# main problem
library(flowCore)
packageVersion("flowCore")
data("GvHD")
GvHD
write.FCS(GvHD[[1]], file.path(temp.dir,"F1.fcs"))
write.FCS(GvHD[[2]], file.path(temp.dir,"F2.fcs"))
write.FCS(GvHD[[3]], file.path(temp.dir,"F3.fcs"))
read.FCS("c:/temp/F2.fcs")
F2 = GvHD[[2]][,c(1:6,8)]
F2
write.FCS(F2, "C:/temp/F2.fcs")
read.FCS("c:/temp/F2.fcs")

# alternate problem
length(description(GvHD[[2]]))
F2 = GvHD[[2]][,c(1:6,8)]
length(description(F2))
F2 = GvHD[[2]][,-7]
length(description(F2))
```

The run
![2018-05-09_133917](https://user-images.githubusercontent.com/3333348/39813066-4b238ec2-538f-11e8-8a42-a9ba43a892d3.png)

The header view
![2018-05-09_132431](https://user-images.githubusercontent.com/3333348/39813070-52680f5a-538f-11e8-910f-d40acc6b34c2.png)

**Comment by mikejiang** [comment]
They are indeed bugs that strangely never caught our attention before. The fixes are pushed. Thanks for reporting them!

**Comment by SamGG** [comment]
Thanks for your reactivity. I did some extended tests and everything is perfect. Thanks.
I noticed a not important behaviour. The range of the flowframe are not the same, but the current behaviour is OK for me.
Best.

![2018-05-11_175722](https://user-images.githubusercontent.com/3333348/39934395-efee818e-5545-11e8-8e73-807d3f653682.png)

**Comment by mikejiang** [comment]
The range from `GvHD` data is not accurate. (seems to be $PnR is corrupted or tampered somehow). 
It won't be an issue for other FCS.
