### ISSUE TITLE
Supply different gate types to filters()

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowCore#113]
Hi Mike, 

I am trying to pass 2 gates of different type (eg. Ellipsoid and polygon) with the same parameters (e.g. FSC-A, SSC-A) but keep getting an error through the `validFilter()` saying the parameters don't match.

Is there a way to do this?

Cheers,
Dillon

**Comment by mikejiang** [comment]
Debug your code and check your gates before passing them to `filters` constructor to see if they indeed have the same parameters. If they do, then post your gates and I can take a look at it.

**Comment by DillonHammill** [comment]
Each gate has class `filters`...

**Comment by mikejiang** [comment]
It works fine to me
```r
> cov <- matrix(c(6879, 3612, 3612, 5215), ncol=2,
+               dimnames=list(c("FSC-H", "SSC-H"), c("FSC-H", "SSC-H")))
> mean <- c("FSC-H"=430, "SSC-H"=175)
> eg <- ellipsoidGate(filterId= "myEllipsoidGate", .gate=cov, mean=mean)
> eg <- filters(list(eg))
> eg
A list of 1 filters applied to a flowFrame.
> 
> sqrcut <- matrix(c(300,300,600,600,50,300,300,50),ncol=2,nrow=4)
> colnames(sqrcut) <- c("FSC-H","SSC-H")
> pg <- polygonGate(filterId="nonDebris", boundaries= sqrcut)
> pg <- filters(list(pg))
> 
> filters(list(pg[[1]], eg[[1]]))
A list of 2 filters applied to a flowFrame.
```

**Comment by DillonHammill** [comment]
Mmmm ok I will give it another go later today. Thanks Mike!

**Comment by DillonHammill** [comment]
Found the mistake! Seems passing gate coordinates as a data.frame objects causes some parameter naming problems. Thanks Mike!
