### ISSUE TITLE
De-compensating a flowFrame

### ISSUE THREAD

**Issue by jspidlen** [RGLab/flowCore#114]
I was recently asked about being able to de-compensate a flowFrame, and so I wrote a quick function below, but I was thinking whether this is something we may want to incorporate into flowCore properly. I ran it by Mike and he thought it may be worth doing and so he suggested to post it on github so that there is a record of it. Below is the essence of what I though could be done:

```R
## De-compensate a flowFrame
## Expecting
## - x to be a flowFrame
## - spillover to be a matrix (compatible with the flowFrame)
## Returns a de-compensated flowFrame object
deCompensateFlowFrame <- function(x, spillover) 
{
  cols <- colnames(spillover)
  sel <- cols %in% colnames(x)
  if(!all(sel)) {
    stop(keyword(x)[["FILENAME"]], 
      "\\nThe following parameters in the spillover matrix are not present in the flowFrame:\\n",
      paste(cols[!sel], collapse=", "), call.=FALSE)
  }
  e <- exprs(x)
  e[, cols] <- e[, cols] %*% spillover
  exprs(x) = e
  x
}
```

And I tested it briefly as follows:
```R
library("flowCore")
x <- read.FCS("path/to/my/test/FCS/file.fcs")
y <- compensate(x, x@description[['SPILL']])
## y is now compensated as per what was in the SPILL keyword
z <- deCompensateFlowFrame(y, y@description[['SPILL']])
## z is now de-compensated, i.e., should be pretty much the same as what was in x to begin with

## Quick check:
max(x@exprs - z@exprs)
## [1] 9.313226e-10
## i.e., maximum difference between before and after is 1e-9 => looks good

## Quick check, let's inspect the first 10 events from x and z
x@exprs[1:10,]
z@exprs[1:10,]
## Looks the same
```

**Comment by gfinak** [comment]
I think it's great. Could you provide an S4 wrapper as well?

**Comment by mikejiang** [comment]
name it as `decompensate`?

**Comment by gfinak** [comment]
yes, that's the idea.

**Comment by jspidlen** [comment]
Mike, can you take care of it? I guess I could do it myself via a pull
request, but I am currently moving and so it would have to wait until the
week of July 23... which I guess isn't a big deal...
J.

**Comment by gfinak** [comment]
Don't worry about it @mikejiang , I'm just working on it now.

**Comment by gfinak** [comment]
Added in d167ef3aad70a80614f94009112c804119774255
