### ISSUE TITLE
Recent changes break my FCS channel labelling/renaming tool

### ISSUE THREAD

**Issue by jspidlen** [RGLab/flowCore#117]
Hi guys,

**Description**
There is a tool [LabelFCSChannels_3.0.1.zip](https://github.com/RGLab/flowCore/files/2307139/LabelFCSChannels_3.0.1.zip) that I have written several years ago and shared with several collaborators to fix names and descriptions of channels in FCS files (i.e, change values of $PnN and $PnS keywords along with other related changes, such as the $SPILLOVER and a few other keywords). This tool is based on R/flowCore (users guide and example input provided as part of the zip), it reads the FCS file into a flowFrame, modifies it as necessary and then saves it using write.FCS. Recently, one of the users has notified me that the tool is not working with flowCore 1.46.1 while it is still working in flowCore_1.44.2, and I strongly suspect that it is related to recent changes in flowCore, possibly the write.FCS function?

**Relevant code snippets from LabelFCSChannels**
See also server.R lines 89 to 124 in the Web (shiny) version.

***Changing $PnN in LabelFCSChannels***
...
`inputFcs@description[[kwParName]] <- as.character(newName)`
`colnames(inputFcs)[which(colnames(inputFcs) == parName)] <- newName`
...

***Changing $PnS in LabelFCSChannels***
...
`inputFcs@description[[kwParLabel]] <- as.character(newLabel)`
...

**Resolution?**
Do you guys think flowCore could be fixed be backwards compatible to make the current version of LabelFCSChannels work again? If so, it would be preferable. Alternatively, what changes would need to be made to make LabelFCSChannels work with the latest flowCore?

Best,
Josef

**Comment by mikejiang** [comment]
It is because the `desc` column of `flowFrame` parameters was not updated along with `$PnS` in your code. 
`write.FCS`  now always overwrite `$PnS` with `desc` value when it writes to a new fcs file (because in reality most users only change the `desc` value and are not aware of the keyword `$PnS`).

The fix for you is simply calling `colnames<-` and `markernames<-` replacement methods (instead of explicitly updating keywords by accessing S4 slot directly). i.e.
```r
> inputFcs <- GvHD[[1]]
>   colnames(inputFcs)
[1] "FSC-H" "SSC-H" "FL1-H" "FL2-H" "FL3-H" "FL2-A" "FL4-H" "Time" 
>   markernames(inputFcs)
[1] "CD15 FITC"  "CD45 PE"    "CD14 PerCP" "CD33 APC"  
>   
>   kwParName <- "$P3N"
>   kwParLabel <- "$P3S"
>   parName <- "FL1-H" 
>   newName <- "newname"
>   newLabel <- "newLabel"
>   
>   #update channel
>   colnames(inputFcs)[which(colnames(inputFcs) == parName)] <- newName
>   #update stain/marker
>   names(newLabel) <- newName
>   markernames(inputFcs) <- newLabel
>   #see updated data
>   colnames(inputFcs)
[1] "FSC-H"   "SSC-H"   "newname" "FL2-H"   "FL3-H"   "FL2-A"   "FL4-H"   "Time"   
>   markernames(inputFcs)
[1] "newLabel"   "CD45 PE"    "CD14 PerCP" "CD33 APC"  
>   #write fcs
>   tmpfile <- tempfile()
>   write.FCS(inputFcs, tmpfile)  
[1] "/tmp/RtmpOogsDt/file65194e1bf01c"
>   tmp1 <- read.FCS(tmpfile)
>   all.equal(colnames(inputFcs), colnames(tmp1))
[1] TRUE
>   all.equal(markernames(inputFcs), markernames(tmp1))
[1] TRUE
```

**Comment by SamGG** [comment]
Thanks Mike.
Josef, will you publish your code on github or so?
Best.

**Comment by jspidlen** [comment]
Thanks Mike,
makes sense, I'll fix it up and yes Samuel, good point, I suppose I should
share that publicly on github rather than emailing it to people... let me
work on that :-).

Best,
Josef

**Comment by jspidlen** [comment]
Mike,
I think you can close this ticket now. I have updated the LabelFCSChannels
tool to be compatible with the latest flowCore as per your suggestion, and
I have shared it on github (https://github.com/jspidlen/LabelFCSChannels)
as per Samuel's suggestion.
Thanks again for your help.

Best,
Josef

**Comment by mikejiang** [comment]
Great!Thanks.

**Comment by SamGG** [comment]
Yep, mega thanks to Josef for releasing it. Thanks Mike for the quick update.
