### ISSUE TITLE
R and CPP text parsing disagree

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#124]
**Describe the bug**
The R version unescapes the delimiter whereas the CPP version does not.

**To Reproduce**
``` r
# this example is correct IIRC
txt = "/zzz/zzz/aaa/aaa//fff/"

# set emptyValue to FALSE, trusting that TEXT is correctly formatted
eV = FALSE
flowCore:::fcsTextParse(txt, eV)
#>        zzz        aaa 
#>      "zzz" "aaa//fff"
flowCore:::fcs_text_parse(txt, eV)
#>       zzz       aaa 
#>     "zzz" "aaa/fff"
```
Created on 2018-08-29 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Expected behavior**
I don't know which one is correct concerning the next steps in importing FCS, but I guess that both versions should agree.

**Comment by mikejiang** [comment]
Both are correct. And C parser (`fcsTextParse` ) is more conservative by preserving whatever read from keyword content (i.e. `double delimiter` in this case) thus considered to be safer.
Also `R` parser is legacy private function, which is not visible to user and won't be invoked other than developer for debugging purpose.
So I don't consider it as the bug.

**Comment by SamGG** [comment]
Thanks. When emptyValue is FALSE, and thus considering double delimiter as an escaped delimiter, then the output might contains a single delimiter. Could you point me to the piece of code that is unescaping the double delimiter?
