### ISSUE TITLE
emptyValue should be FALSE by default

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#125]
**Describe the bug**
As emptyValue is TRUE by default, correctly escaped keyword values raise an error.

**To Reproduce**
``` r
# this example is correct IIRC
txt = "/zzz/zzz/aaa/aaa//fff/"

flowCore:::fcsTextParse(txt, TRUE) # default
#> Error in flowCore:::fcsTextParse(txt, TRUE): Empty keyword name detected!If it is due to the double delimiters in keyword value, please set emptyValue to FALSE and try again!

flowCore:::fcsTextParse(txt, FALSE)
#>        zzz        aaa 
#>      "zzz" "aaa//fff"
```
Created on 2018-08-29 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Expected behavior**
No error is raised when emptyValue is FALSE, which sounds to me the correct and should be the default behaviour.

**Comment by mikejiang** [comment]
If this flag is FALSE, then keyword parsing may silently go wrong for empty-value keywords. 
```r
> flowCore:::fcsTextParse("/K1//K2/v2", FALSE)
K1//K2 
  "v2" 
> flowCore:::fcsTextParse("/K1//K2/v2", TRUE)
  K1   K2 
  "" "v2" 
```
Thus it is safer to always prompt user to explicitly turn on the `double delimiter` behavior (i.e. by `emptyValue = F` since these two can't be handled simultaneously )

**Comment by SamGG** [comment]
Hi! My point of view is different. When I run a pipeline on FCS files with correctly escaped keywords, I don't want to have to add emptyValue=FALSE to the calls to read.FCS(). Especially if the pipeline consists in Citrus or SPADE. I think this will push me to reconsider the global options enhancement. Best.
