### ISSUE TITLE
write.FCS writes the inaccurate $BEGINDATA leading to wrong data segment

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowCore#129]
**Describe the bug**
The byte offsets for DATA segment are required to be written in  keywords  `$BEGINDATA` and `$ENDDATA`, which depends on the actual TEXT segment length. But on the other hand, the TEXT segment length itself is in fact affected by the actual string lengths of these two keyword values.

This circular dependencies causes the trouble for the current logic where the these keyword values become obsolete immediately after they are computed from the TEXT length since TEXT length may be changed after updating these values.
 
**To Reproduce**
```r
> mat <- matrix(1:30,ncol = 3, dimnames = list(NULL, letters[1:3]))
> fr <- flowFrame(mat)
> #add a dummy keyword to fill the TEXT segment so that itself actual offset is subject to change 
> #once the computed $ENDSTEXT (i.e. '995') replaces the original the placeholder (i.e. '0')
> keyword(fr)[["test"]] <- paste(rep(0,655), collapse = "")
> tmp <- tempfile()
> write.FCS(fr, tmp)
[1] "/tmp/Rtmp5bK5gA/file17b077e19cf5"
> fr2 <- read.FCS(tmp)
> head(mat)
     a  b  c
[1,] 1 11 21
[2,] 2 12 22
[3,] 3 13 23
[4,] 4 14 24
[5,] 5 15 25
[6,] 6 16 26
> head(exprs(fr2))
                a            b            c
[1,] 1.000000e+01 5.986526e-39 6.029574e-39
[2,] 5.877472e-39 5.992266e-39 6.032444e-39
[3,] 5.900431e-39 5.998006e-39 6.035314e-39
[4,] 5.923390e-39 6.003746e-39 6.038184e-39
[5,] 5.934869e-39 6.009485e-39 6.041054e-39
[6,] 5.946348e-39 6.015225e-39 6.043924e-39
```.

**Expected behavior**
A simple solution is remove these two keywords entirely since the first 58-byte HEADER already has these offsets information. (This probably explains why we see these missing from some flowJo-generated FCS files).  `read.FCS` has the logic to handle that by simply using HEADER (except it will throw the warnings).

The more standard-conforming way is to compute the offsets within a loop and keep updating TEXT content until its total length stops increasing.

**Comment by SamGG** [comment]
Hi Mike. Thanks for reporting. Hope that Josef will give his opinion before coding.

Firstly, coding the DATA within the HEADER limits the data end to less than 100 MB as stated in an example of the FCS3.1 standard (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2892967/bin/NIHMS203250-supplement-Supp_Fig_1.pdf, p8)

> A second example of a legal HEADER segment is:
> ```FCS3.1*********256****1545*******0*******0*******0*******0```
> The '0's in the begin DATA and end DATA positions indicates that the DATA segment exceeds
> the 99,999,999 byte limit. Therefore, the byte offsets to begin Data and end Data, are located
> only in the $BEGINDATA, $ENDDATA keyword values in the TEXT segment. The begin
> ANALYSIS and end ANALYSIS byte offsets are also located in the $BEGINANALYSIS and
> $ENDANALYSIS keyword values in TEXT segment, if an ANALYSIS segment exist. 

So the simple solution is OK for small to medium data file and FCS 3..0 (unverified). But for FCS 3.1, BEGINDATA seems to be required. (p12).

When DATA segment follows TEXT segment, there is no need to put it at the next byte. So let's use the TEXTEND (computed with BEGINDATA = ENDATA = 0) plus 100 bytes as BEGINDATA, then put this value in the keywords. Then compute the ENDDATA and update the keywords. There is nearly no chance that the data starts at a position bigger than 10^6 bytes AND the data ends at a position bigger than 10^90 bytes. So those 100 extra bytes should do the job, but we could add an extra check. IMHO, 100 bytes per segment (ie DATA, ANALYSIS, TEXT) should be for the next years. I already saw this kind of trick in some FCS files

Best.

**Comment by mikejiang** [comment]
Thanks for the input. But I think my second solution can solve this for good 
```r
> write.FCS(fr, tmp)
> fr2 <- read.FCS(tmp)
> all.equal(exprs(fr), exprs(fr2), check.attributes = F)
[1] TRUE
```

**Comment by SamGG** [comment]
Good job!
I prefer
```
      if(kw.len.new == kw.len.old) break
      #update the endTxt
      endTxt <- endTxt + kw.len.new - kw.len.old
      kw.len.old <- kw.len.new
```
than
```
      if(kw.len.new > kw.len.old)
      {
        #update the endTxt
        endTxt <- endTxt + kw.len.new - kw.len.old
        kw.len.old <- kw.len.new
        
      }else
        break
```
but that's a matter of taste ;-)
