### ISSUE TITLE
min.limit of read.FCS is NULL

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#131]
... whereas the doc says that the default value is -111. I don't know at which point this behavior changed, but the doc should reflect the current settings.
Best.

**Comment by jacobpwagner** [comment]
Thanks for pointing this out. I'm doing a large batch of doc updates right now, so I'll make sure to include this change.

**Comment by SamGG** [comment]
In the comment above the code of write.FCS, missing filename is said to be extracted from identifier(). Filename is currently mandatory.

**Comment by jacobpwagner** [comment]
Fixed by commit 6ba137b03a29c0d95559e8135d6d4370ffc03170 and commit ef5ae3709bef10a0d993b3aacb5ab4e3316aff82
