### ISSUE TITLE
2^31-1 bytes can be written in a single writeBin() call

### ISSUE THREAD

**Issue by mtrussart** [RGLab/flowCore#136]
Hi,

Im having problems saving a large file that contains several fcs concatenated, and I get this error:
Error in writeBin(as(t(exprs(x)), what), con, size = types[what, "bitwidth"],  :
  only 2^31-1 bytes can be written in a single writeBin() call

I have done that using the Catalyst package function normCytof, but they said it's related to flowCore function
normCytof(x=ff, y="dvs", k=80, out_path = paste(wd,"All_normCatalyst_debarcoded_data/",sep=""), remove_beads = TRUE).

Could you please help me to be able to save it for big sizes?

Thanks so much

**Comment by mikejiang** [comment]
Thanks for reporting it. @jacobpwagner and I will be adding support for it.

**Comment by jacobpwagner** [comment]
@mtrussart, would you see if commit 54b1e0d989ac0c907b65403ce50457258979796f fixes the problem?

**Comment by SamGG** [comment]
Hi,
Does the 2^31 limit impacts also the ncdfFlow object?
For that large FCS, even if there is a unique FCS, will it more efficient to use ncdfFlow?
Best.

**Comment by mikejiang** [comment]
No, It was `base::writeBin` issue,  ncdfFlow doesn't have this limitation.
