### ISSUE TITLE
Error: object 'comp' not found

### ISSUE THREAD

**Issue by algebio** [RGLab/flowCore#137]
Hi

I'm following the flowCore manual and I'm stuck with a problem.  On page 22, I should have produced two objects: gs and comp but I got this error message:

> comp
Error: object 'comp' not found

The manual says 

"Normally, we want to compensate the data firstly by using a user supplied compensation matrix:"

How do I do that? I'm just using the sample data provided by flowCore. I tried to use compensate.Rd from the flowWorkspace/man/ but it didn't work.

Thanks in advance!

JO

**Comment by mikejiang** [comment]
I transferred this issue here since it is related to `flowCore` vignette.
The `comp` object comes from a `GatingSet` that is parsed from the manually gated data from flowJo
```r
gs_manual <- load_gs(list.files(pattern = "gs_manual"
                                , system.file("extdata", package = "flowWorkspaceData")
                                , full = TRUE))
comp <- getCompensationMatrices(gs_manual[[1]])
```
I will need to un-hide this code chunk in vignette to avoid future confusion.

**Comment by mikejiang** [comment]
Ping @algebio in case you don't get the notification of the transferring the issue

**Comment by algebio** [comment]
Perfect!
Thank you so much.

JO

**Comment by igordot** [comment]
I just installed `flowWorkspaceData` from GitHub (so it should be the latest version) and I am getting the following error:
```
Error in .load_gs(output = path, files = files) : 
  .rds file missing in /Library/Frameworks/R.framework/Versions/3.4/Resources/library/flowWorkspaceData/extdata/gs_manual
```
I was able to fix it by changing `"extdata"` to `"extdata/legacy_gs"`.

I am just making this note here in case anyone else runs into this issue. I am guessing the documentation is just out of sync between version changes.

**Comment by mikejiang** [comment]
The changes you saw should have belonged to the `cytoset` branch. I've fixed and restored `trunk` branch to the original state.

**Comment by igordot** [comment]
Thanks for the quick fix!
