### ISSUE TITLE
[Question]  Extract hierarchical gate membership

### ISSUE THREAD

**Issue by hartmannfj** [RGLab/flowCore#143]
Hi all,

I hope its ok to ask this question here. Given a set of flowset and gatingset, is there an easy way to extract a TRUE/FALSE population/gate membership for each cell. A simple example would be a first gate on CD3, followed by gates on CD4 and CD8 (children of CD3). In other words, a TRUE/FALSE for each getData() call using all gates in the gatingSet. I was thinking of something like this as an output:

Cell  Gate-CD3, Gate-CD4, Gate-CD8
1       TRUE            TRUE             FALSE
2       TRUE            FALSE            TRUE

Best, Felix

**Comment by mikejiang** [comment]
Basically, `getIndices` method is what you need to get the memberships for each cell. There is also `getIndiceMat` convenient wrapper built around that API
```r
library(flowWorkspace)
dataDir <- system.file("extdata",package="flowWorkspaceData")

gs <- load_gs(list.files(dataDir, pattern = "gs_manual",full = TRUE))

getNodes(gs)
mat <- getIndiceMat(gs[[1]], "CD3+|CD4|CD8")              
head(mat)
     CD3+   CD4   CD8
[1,]  TRUE  TRUE FALSE
[2,] FALSE FALSE FALSE
[3,] FALSE FALSE FALSE
[4,] FALSE FALSE FALSE
```
And you can discard those cells that fall out side of these 3 gates by removing `all false` rows.

**Comment by hartmannfj** [comment]
Thanks a lot, works great!
