### ISSUE TITLE
Time Parameter maxRange

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowCore#145]
**Describe the bug**
Not sure how the maxRange is determined for the parameters of the flowFrame but is it possible to have the maxRange better reflect the actual range of the "Time" parameter?

**To Reproduce**
See screenshot of flowFrame below:

**Expected behavior**
It would be nice with the maxRange of the "Time" parameter reflected that the actual limits of the parameter in either the flowFrame or collectively in the flowSet.

**Screenshots**
![time_parameter](https://user-images.githubusercontent.com/28646736/52906792-19304880-32a8-11e9-8f6b-686937f0301a.PNG)

**Comment by gfinak** [comment]
The range reflects the instrument range, not the data range. This is
historical. I'm happy to entertain a discussion on use cases for both
instrument and data range, maybe we can have a method to convert between
both or something to that effect.

Greg Finak

**Comment by DillonHammill** [comment]
Hi Greg,

I have been using these ranges for setting plot limits. Which works great for all the other parameters but not the Time parameter. It would be nice if there was a better estimate for this parameter, otherwise I will have to manually set limits for the Time parameter. Would be great if there was a way to switch between instrument and data ranges!

Dillon

**Comment by mikejiang** [comment]
For ggcyto plots, how about `+ ggcyto_par_set(limits = "data")`?To get the actual data range, `range(fr, "data")`

**Comment by DillonHammill** [comment]
I knew there must be a better way! Thanks @mikejiang! I hadn't noticed the `type` argument in `range`. That should do the trick. I don't see any use for `machine` limits for the 'Time' parameter?

**Comment by mikejiang** [comment]
Do we want to treat `Time` differently from the other channels by always ignoring `$PnR` or overwriting it with the actual data range when parse FCS into flowFrame? @jspidlen

**Comment by jspidlen** [comment]
I would not do that. Max range comes from $PnR and reflects the instrument
range. It's the same for other parameters too, i.e. just because $PnR is
2^18 doesn't mean that the channel has actual values that go that high. So
I would keep it consistent and as is. Whoever needs the data range can get
it from the data easily. That's just my 2c :-)
Josef

**Comment by gfinak** [comment]
I agree with Josef on this. We can provide the option but leave it as is.

Greg Finak

**Comment by DillonHammill** [comment]
Makes sense. Thanks for looking into it.

Dillon.
