### ISSUE TITLE
write.FCS text segment offsets missing BD FACS Diva

### ISSUE THREAD

**Issue by NicolasArraud** [RGLab/flowCore#147]
Dear colleagues, 

Thank you so much for the excellent work you do.

I am a flow cytometry teacher and some of my students are more familiar with BD FACS Diva 6 so I tried to convert my BC Navios files for Diva to open.

Please find two .fcs files I would like your opinion on: https://hugge-my.sharepoint.com/:f:/g/personal/nicolas_arraud_hcuge_ch/ErO8OdcDfy1Gpo7u-ICrFW0Br-m9BPP81kmVvT9q3kQhNg?e=zrcKw1

I generated one of the files with the R flowCore write.FCS function.
BD Kaluza and Cytognos Infinicyt can reopen this file without any problem.
But BD FACS Diva sends an error message:
"Unable to read the file. The text segment offsets are missing or invalid in the FCS file header".

I took this file and exported it with the Infinicyt export function and now Kaluza, Infinicyt and Diva can read it.

Do you see what is the issue with the .fcs file generated with the write.FCS function ?

What would be the procedure to fix this .FCS file without using Infinicyt ?

Sincerely yours, 
Nicolas

**Comment by gfinak** [comment]
Thanks for reporting the bug and providing the files. We'll look into it and try to provide a fix.

**Comment by SamGG** [comment]
Hi,
I don't see any big differences in both files. It seems to me that both files have been exported from Infinicyt, what does not correspond to what I understand in your question. Could you specify the version of flowCore you are using? Could you provide the original Navios file?
My two cents.

**Comment by gfinak** [comment]
@SamGG thanks for taking a look!

**Comment by NicolasArraud** [comment]
Dear @SamGG , thank you for the time you spent!

You are absolutely correct, I took my original Navios file and exported it with Infinicyt to change the PnR values,  datatype & Byteorder as requested for Diva (At some point I would like to be able to do that part in flowCore).

As you requested I added the original Navios file & this first file exported by Infinicyt to the previous link.

I used flowCore to edit the this first file by adding the $TIMESTEP keyword in the header.

I tried both the write.FCS function from flowCore 1.40.3 and 3.8 with similar errors from Diva.
I also tried to use the write.FCS function on an unedited .fcs file and it is always the same Diva error...

Looking forward to hear from you, 
Au plaisir de vous lire

Cheers, 
Nicolas

**Comment by SamGG** [comment]
Dear Nicolas,
I will look into the files as soon as I get a correct internet connection. Currently the flowCore version is 1.48.1 (at least in my hands). I will read/write your original FCS file and send it back to you. I think the ranges will be corrected and maybe some other points.
Cheers.

**Comment by NicolasArraud** [comment]
Dear @SamGG, 

Thank you so much for the help !
I misread the flowCore version, I did the tests with version 1.40.3 and 1.48.1 with similar results.

All the best, 
Nicolas

**Comment by mikejiang** [comment]
I am able to import both fcs files (`file generated with R flowCore *`) into Diva without problems. My BD FACS Diva version is `8.0.1` (which is build 2014). Any possibility to upgrade your diva?

**Comment by SamGG** [comment]
The original Navios file consists in two segments. The first segment is in FCS2 format while the second segment is in FCS3 format. Some information are found in the first but not in the second. The following code tries to build a FCS file in FCS 3 format while retrieving most of the information. The resulting FCS file seems to be similar in FlowJo with the files you provided and the original file imported directly. I have no Diva 6 around to check. Let us know. I f the code sounds useful, I will start a flowForeign package for such need.
Best.

```
library(flowCore)

# --------- configure file location

ifile = "c:/demo/NArraud/Original Navios file.LMD"
ofile = "c:/demo/NArraud/ConvertedWithFlowCore.FCS"

# --------- process

# read 1st data segment which is in FSC 2.0
ff.1 = read.FCS(ifile, transformation = FALSE, dataset = 1)
ff.1
# read 2nd data segment which is in FSC 3.0
ff.2 = read.FCS(ifile, transformation = FALSE, dataset = 2)
ff.2

# in the FSC 3.0 data segment
# - the descriptions are lacking
# - the data are in full scale (20 bits)

# get FL marker indices in FSC3 segment
ff.2.mrk = colnames(ff.2)
nm.2 = gsub("(FL\\d+).+", "\\1", pData(ff.2@parameters)$name)
idx = grep("^FL\\d+", nm.2)

# get FL marker indices in FSC2 segment
nm.1 = gsub("(FL\\d+).+", "\\1", pData(ff.1@parameters)$name)
ds.1 = gsub("(FL\\d+).+", "\\1", pData(ff.1@parameters)$desc)
(mch = match(nm.2[idx], nm.1))
stopifnot(is.na(mch)==FALSE)  # stop if any unmatched FL markers

# create a copy of parameters of FSC3 segment
pd2 = pData(ff.2@parameters)

# replace description
pd2$desc[idx] = ds.1[mch]

# rescale according 18 bits
scl = (pd2$range / 2^18)  # scaling coefficients
exprs(ff.2) = sweep(exprs(ff.2), 2, scl, "/")

# replace the range
pd2$minRange = round(pd2$minRange / scl, 0)
pd2$range = pd2$range / scl
pd2$maxRange = pd2$range - 1
# pd2$maxRange = round(pd2$maxRange / scl, 0)

# replace the parameters back
pData(ff.2@parameters) = pd2

# remove PxR parameters
# ff.2@description = ff.2@description[-grep("^\\$P\\d+R", names(ff.2@description))]

# update PxR parameters
ff.2.kwds = ff.2@description
ff.2.kwds.range = grep("^\\$P\\d+R", names(ff.2.kwds))
ff.2.kwds[ff.2.kwds.range] = as.character(2^18)
ff.2@description = ff.2.kwds

# recover some extra parameters
ff.1.kwds = ff.1@description
ff.1.kwds.names = names(ff.1.kwds)
for (kwd in c("$CYT", "$BTIM", "$ETIM", "$DATE", "$FIL", "$SYS", "$EXP", "$PROJ", "$INST", "$INSTADDRESS", "$RUNNUMBER", "$OP", "$SMNO", "$SRC", "$CELLS")) {
  if (exists(kwd, ff.1.kwds) && !exists(kwd, ff.2.kwds))
    ff.2.kwds[kwd] = ff.1.kwds[kwd]
}
ff.2@description = ff.2.kwds

# write to disk
write.FCS(ff.2, ofile)

# --------- check

(ff.2.bis = read.FCS(ofile, transformation = F))
t(apply(exprs(ff.2.bis), 2, range))
ff.2.bis@description

```

**Comment by NicolasArraud** [comment]
Dear @mikejiang , thank you for the suggestion. 
I have to test it but it could be a valid option for my teachings.

On the other hand I have some colleagues especially from middle east and africa still using Diva 6
So being able to convert my files in a Diva 6 compliant format would really help as they are moving towards more colors.

 Dear @SamGG , thank you so much for the time and effort invested!
I tried the code using both flowCore version 1.40.3 and 1.48.1 and I still have the same Diva error:
![190406 Diva 6 error](https://user-images.githubusercontent.com/49204916/55672723-9b97ba80-589e-11e9-9570-938e116ba232.PNG)

Cheers, 
Nicolas

**Comment by NicolasArraud** [comment]
Dear colleagues, 

I tested the solution proposed by @mikejiang and indeed BD FACS Diva 8.0.1 can perfectly open the files generated with flowCore write.FCS function.

Thank you so much for your help, I close the subject.

Cheers, 
Nicolas
