### ISSUE TITLE
read.flowset using which.lines hangs

### ISSUE THREAD

**Issue by fbenedett** [RGLab/flowCore#150]
Hello, I have a problem with read.flowSet when I use the parameters "which.lines".
I have three files of different size that I can read with read.flowSet.  Since the size of one
of them is bigger than the others I need to randomly sample all the files using the minimum number of rows of the smallest file.  "which.lines" should solve this problem but when I try to use it R(studio) console hang.  Without "which.lines" instead everything works perfectly.
Regarding the reproducing... I never heard of reprex and I am learning it, but the problem is very easy.
this works:
fset=read.flowSet(fcs_files, channel_alias = map)
this doesn't:
fset=read.flowSet(fcs_files, channel_alias = map, which.lines = nmin)

I have put in attachment the code, it's very short.
[test_whichlines.txt](https://github.com/RGLab/flowCore/files/3131352/test_whichlines.txt)

**Comment by fbenedett** [comment]
Update:
It seems to be a bad scaling behavior.  "which.lines" works well for n<10000, for n>100000 it is problematic (in my case n is approx 300000).  A workaround exist by using:
fset_trans <- fsApply(fset_comp, function(x, resample=nmin){
  expr= exprs(x)[sample(1:nmin, replace=FALSE),]
  exprs(x)=expr
  x
})

**Comment by SamGG** [comment]
Let us know if the following code fits your needs.

``` r
library(flowCore)
# a flowset
data("GvHD")
fs = GvHD
# overview of cells per FCS
fsApply(fs, nrow)
#>         [,1]
#> s5a01   3420
#> s5a02   3405
#> s5a03   3435
#> s5a04   8550
#> s5a05  10410
#> s5a06   3750
#> s5a07  13979
#> s6a01   2205
#> s6a02  13350
#> s6a03  11610
#> s6a04  13830
#> s6a05  13934
#> s6a06  19470
#> s6a07   9405
#> s7a01  16055
#> s7a02  10305
#> s7a03  30195
#> s7a04  59849
#> s7a05  39068
#> s7a06  11939
#> s7a07  13214
#> s9a01  12666
#> s9a02   8265
#> s9a03   4065
#> s9a04   7080
#> s9a05  66105
#> s9a06  49421
#> s9a07  12768
#> s10a01 17289
#> s10a02  4530
#> s10a03  6765
#> s10a04  9540
#> s10a05 25515
#> s10a06 24656
#> s10a07 25601
# get the minimal cell count
nmin = min(fsApply(fs, nrow))
# sampling
fs2 = fsApply(fs, function(ff) ff[sample.int(nrow(ff), nmin)])
# check sampled
fsApply(fs2, nrow)
#>        [,1]
#> s5a01  2205
#> s5a02  2205
#> s5a03  2205
#> s5a04  2205
#> s5a05  2205
#> s5a06  2205
#> s5a07  2205
#> s6a01  2205
#> s6a02  2205
#> s6a03  2205
#> s6a04  2205
#> s6a05  2205
#> s6a06  2205
#> s6a07  2205
#> s7a01  2205
#> s7a02  2205
#> s7a03  2205
#> s7a04  2205
#> s7a05  2205
#> s7a06  2205
#> s7a07  2205
#> s9a01  2205
#> s9a02  2205
#> s9a03  2205
#> s9a04  2205
#> s9a05  2205
#> s9a06  2205
#> s9a07  2205
#> s10a01 2205
#> s10a02 2205
#> s10a03 2205
#> s10a04 2205
#> s10a05 2205
#> s10a06 2205
#> s10a07 2205
# clean
rm(fs)
```

<sup>Created on 2019-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by fbenedett** [comment]
Yes, your code solves my problem. Thank you.   Nevertheless, shouldn't which.lines be fixed?
Anyway, I am closing this.

**Comment by mikejiang** [comment]
`which.lines` is meant to be used to achieve partial disk IO for the large FCS that can't be loaded into memory. It will significantly slow down the read (especially for the large size of random sampling) due to the frequent disk seek operations. I've added notes to the doc.
If the goal is to subset rather than partial IO, then what you and @SamGG did were the right answer

**Comment by SamGG** [comment]
@mikejiang Thanks for the follow-up.
