### ISSUE TITLE
Support for attaching transformList to slot of flowFrame

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowCore#151]
Hi @mikejiang and @jacobpwagner,

I know that this has been mentioned before but I was just wondering if there is any possibility of adding support for attaching a `transformList` to a new slot of a `flowFrame` when applying the transformation with `transform`? 

This is an issue that I constantly facing in `CytoRSuite` and although there are approaches to retrieve this information directly from the `GatingSet`, there are instances where this is not possible and the user must manually supply the transformations. Which is OK for experienced users but new users will expect this behavior automatically and may accidentally provide the incorrect transformations. I would like to eliminate this uncertainty if possible. In particular, having this information attached to each `flowFrame` will allow for appropriate axes transformations when visualizing `flowFrame` or `flowSet` objects.

Thanks again for all your help!

Dillon

**Comment by mikejiang** [comment]
>there are instances where this is not possible and the user must manually supply the transformation

Can you provide a n example?

**Comment by DillonHammill** [comment]
For example one scenario which seems likely is having a user try to visualise a transformed `flowFrame` or `flowSet`. As far as I know there is no way to properly display the transformed axes (10^x) unless the transformations are manually supplied. See below image where I have plotted a transformed flowFrame (PE-A channel is transformed) using ggcyto:


![Scales](https://user-images.githubusercontent.com/28646736/57564734-21ee7180-73f4-11e9-89c6-9938fe9c3a99.png)

Now if the transformList was attached to the file this could have been used internally to properly set the axes (on 10^x)  as the user would have expected.

If there is a way to do this without the transformations please let me know.

**Comment by mikejiang** [comment]
Just pass the untransformed data to ggcyto and do `cood_trans`
See https://www.r-bloggers.com/custom-axis-transformations-in-ggplot2/

**Comment by DillonHammill** [comment]
That would work fine for ggplot but I am using base graphics which is more complicated. I will have a look at coord_trans to see how it works.

**Comment by DillonHammill** [comment]
I also have a lot of functions that work at the flowFrame/flowSet level that need to know if the data has been transformed or not. For now I am using the range of the data to determine whether it us transformed or not. This will work in most cases but is likely to fail if the flowFrame/flowSet has few or no events. However, if the transform object was attached it would be easy to tell if the data has in fact been transformed and you would have access to the transformations if you need to use (e.g. for inverse transformation).

**Comment by mikejiang** [comment]
Is there any particular reason for you to not use `GatingSet` in your use cases? We don't want to spend the efforts on replicating the same features that are already there if you can simply switch to the right data structure.

**Comment by DillonHammill** [comment]
I have written GatingSet methods which are obviously preferred but I think it is inevitable that some users will want to interact directly with the data at the flowFrame/flowSet level. How much work would be required to add support for this?

**Comment by mikejiang** [comment]
You can certainly do that outside of flowCore/flowWorkspace. But when you interact with `GatingSet`, the extra slot is not guaranteed to be preserved due to the default coercion.

**Comment by DillonHammill** [comment]
How would I go about doing this? I might give it a try to see if it will work or not...

**Comment by jacobpwagner** [comment]
You can make S4 classes that inherit from `flowFrame` and `flowSet` and add on whatever you want, but as Mike mentioned, this may cause issues when you interact with `GatingSet`. From our end, it's not that adding a slot to the `flowFrame` class for a `transformList` would be particularly difficult on its own, but that would have ramifications for a lot of other classes and methods that interact with it. That seems like an unnecessary shakeup when `GatingHierarchy`/`GatingSet` already serve the purpose of combining the data and standard operations on the data (compensation, transformation, gating).

So if users want to interact with the data at the `flowFrame`/`flowSet` level, it seems more likely that they are electing to be in control of manually compensating and transforming the data (and plot axes) themselves. Conversely, if users want the convenience of having compensation matrices and transformation functions included alongside the data, `GatingSet` already does this.

**Comment by DillonHammill** [comment]
Fair enough. I have added a new API to directly load samples into a GatingSet which will hopefully prevent the need for interacting with flowFrame or flowSet objects directly.

**Comment by mikejiang** [comment]
Again, since `flowFrame` doesn't carry transformation, there is no reliable way to track the history of data transforming on its own. For `GatingSet` , `gh_get_transformation` gives all the information you need to tell whether/how data was transformed.
