### ISSUE TITLE
Some items identified in the data environment either have the wrong dimension or type.

### ISSUE THREAD

**Issue by lcymcdnld** [RGLab/flowCore#156]
Hello, 

I am trying to create a flowSet using the following code: 
`
files <- list.files(path="./AllMacrophage/", pattern=".fcs$")
fs <- read.flowSet(files, path="./AllMacrophage/", transformation = F)
`
The .fcs files I am trying to read in are the result of an export of a population gated in FlowJo. 

However, I am getting the following error...

Error in validObject(.Object) : 
  invalid class “flowSet” object: Some items identified in the data environment either have the wrong dimension or type.

I cant think what is wrong with my fcs files. 

Please help! 
Cheers,
Lucy

**Comment by gfinak** [comment]
Are you sure `files` lists only fcs files? Do all the files returned have
the same number of channels, markers, in the same order, with the same
names?
The error is telling you that the flowSet object is not valid. Try
inspecting the content of the files variable. Then try reading them
individually into a list via a loop and inspect their dimensions.
Greg

**Comment by mikejiang** [comment]
Did you also see the message like `XXX.fcs doesn't have the identical colnames as the other samples`, which may help you to identify the files that cause the failure?

**Comment by lcymcdnld** [comment]
Hello,

Yes it turned out not all samples had FSC-W. Thanks for your help!

Lucy

On 4 Sep 2019, at 19:05, Mike Jiang <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you also see the message like XXX.fcs doesn't have the identical colnames as the other samples, which may help you to identify the files that cause the failure?

**Comment by mikejiang** [comment]
BTW,  You can use `column.pattern` argument to skip reading `FCS-W` if it is not critical for your analysis.
