### ISSUE TITLE
read.FCS reports alias error

### ISSUE THREAD

**Issue by gabora** [RGLab/flowCore#159]
Hi, 
**Describe the bug**
I get the following error while importing a dataset using `read.FCS()`:
`Error in update_channel_by_alias(cn, channel_alias) : 
  channel_alias: Multiple channels from one FCS are matched to the same alias!`

The data was downloaded from [here]( http://ccsb.stanford.edu/content/dam/sm/ccsb/documents/education/data/Supplementary%20Data%20S4.zip ), I re-uploaded here 
[A_BASALHeLa.fcs.zip](https://github.com/RGLab/flowCore/files/3587354/A_BASALHeLa.fcs.zip)

Indeed, it has two channels called by the same alias "treatment". Unfortunately, I have no idea how to fix the data, so I was looking into `read.FCS` if there is a way to solve the problem.  

**To Reproduce**
Download the data from the above link and unzip it. 
For reproducibility here is the code and the whole error message:

```{r}
fcs_file = "./A_BASALHeLa.fcs"
samp <- flowCore::read.FCS(fcs_file, transformation = FALSE)
```
results in 
```{r}
      orig_channel_name new_channel_name
$P40N         treatment        treatment
$P41N         treatment        treatment
Error in update_channel_by_alias(cn, channel_alias) : 
  channel_alias: Multiple channels from one FCS are matched to the same alias!
```

First I tried to operate with the `channel_alias` input of `read.FCS`, but it is not clear what is the `channel name` and what is the `alias`. Based on the error message I tried to rename one of the `treatment` to `treatment2` to resolve the above problem:
```{r}
new_channel_alias = data.frame(alias = "treatment2",
                                channels= '$P41N',
                                stringsAsFactors = F)

samp <- flowCore::read.FCS(fcs_file, transformation=FALSE, channel_alias=new_channel_alias)
```
but I get exactly the same resulting error message, so I guess '$P41N' is not considered as the channel. 

Then I also tried, using "treatment" as the channel and rename
```
new_channel_alias = data.frame(alias = "treatment2",
                                channels= 'treatment',
                                stringsAsFactors = F)
```
but then I get:
```     
orig_channel_name new_channel_name
$P40N         treatment       treatment2
$P41N         treatment       treatment2
Error in update_channel_by_alias(cn, channel_alias) : 
  channel_alias: Multiple channels from one FCS are matched to the same alias!
```
both of the channels are renamed.

** Summary **

- is the `channel_alias` works as expected? I think the `$P41N` should be recognised as a channel name. 
- Is this checking really need to throw and error and not a warning? If I run it in debug mode and modify `flowCore:::update_channel_by_alias`  line 40 (in the uncommented code) 
`is.dup <- tb > 1` to `is.dup = FALSE`  then the data is imported (apparently correctly) and then I might have the chance to change the aliases. 

thanks ,
Attila

**Comment by mikejiang** [comment]
This file doesn't conform to the FCS3.1 standards, i.e.
>Parameter names must be unique, i.e., each name (value of an $PnN keyword)
may occur only once in the data set

**Comment by mikejiang** [comment]
@gabora , the issue is now addressed. (see #161)
