### ISSUE TITLE
Change fcs column order

### ISSUE THREAD

**Issue by algebio** [RGLab/flowCore#160]
Hi

Maybe a very basic question but I'm really struggling with it. How can I modify the column order of a group of fcs files? I have 17 files with the same column names (edited with premessa) but when I try to use them together, some of them have a different order.

I get this error message and bellow an example of the fcs files.

fs <- read.flowSet(md$file_name, transformation = FALSE,truncate_max_range = FALSE)
000011_spleen 18042019_s1_p1_r16_a16_ac.fcs doesn't have the identical colnames as the other samples!
000012_spleen 18042019_s1_p1_r18_a18_ac.fcs doesn't have the identical colnames as the other samples!
000013_spleen 18042019_s1_p1_r19_a19_ac.fcs doesn't have the identical colnames as the other samples!
000014_spleen 18042019_s1_p1_r20_a20_ac.fcs doesn't have the identical colnames as the other samples!
000015_spleen 18042019_s1_p1_r21_a21_ac.fcs doesn't have the identical colnames as the other samples!
000016_spleen 18042019_s1_p1_r22_a22_ac.fcs doesn't have the identical colnames as the other samples!
000017_spleen 18042019_s1_p7_r30_a30_ac.fcs doesn't have the identical colnames as the other samples!
Error in validObject(.Object) : 
  invalid class “flowSet” object: Some items identified in the data environment either have the wrong dimension or type.

Example: the first one has different order to the rest.

colnames(read.FCS("//campus/home/home36/njo47/Projects/renamed/spleen 18042019_s1_p1_r18_a18_ac.fcs"))
 [1] "176Di"   "Nd148Di" "Nd142Di" "Sm149Di" "Eu151Di" "Ho165Di" "Sm152Di" "Yb171Di" "Sm147Di" "Yb172Di"
[11] "Gd160Di" "Er168Di" "Nd146Di" "Pr141Di" "Dy162Di" "Yb170Di" "Tb159Di" "Tm169Di"

> colnames(read.FCS("//campus/home/home36/njo47/Projects/renamed/Exp119_CD45+.fcs"))
 [1] "Pr141Di" "Nd142Di" "Nd146Di" "Sm147Di" "Nd148Di" "Sm149Di" "Eu151Di" "Sm152Di" "Tb159Di" "Gd160Di"
[11] "Dy162Di" "Ho165Di" "Er168Di" "Tm169Di" "Yb170Di" "Yb171Di" "Yb172Di" "176Di"  

> colnames(read.FCS("//campus/home/home36/njo47/Projects/renamed/Exp119_LiveCells.fcs"))
 [1] "Pr141Di" "Nd142Di" "Nd146Di" "Sm147Di" "Nd148Di" "Sm149Di" "Eu151Di" "Sm152Di" "Tb159Di" "Gd160Di"
[11] "Dy162Di" "Ho165Di" "Er168Di" "Tm169Di" "Yb170Di" "Yb171Di" "Yb172Di" "176Di"   

Thanks
Juan

**Comment by mikejiang** [comment]
`read.ncdfFlowSet` should take care of this, e.g.
```r
> library(flowCore)
> library(ncdfFlow)
> data("GvHD")
> fr1 <- GvHD[[1]]
> fr2 <- GvHD[[2]]
> cols <- colnames(fr1)
> fr2 <- fr2[,rev(cols)]
> cols
[1] "FSC-H" "SSC-H" "FL1-H" "FL2-H" "FL3-H" "FL2-A" "FL4-H" "Time" 
> colnames(fr2)
[1] "Time"  "FL4-H" "FL2-A" "FL3-H" "FL2-H" "FL1-H" "SSC-H" "FSC-H"
> f1 <- tempfile()
> f2 <- tempfile()
> write.FCS(fr1, f1)
[1] "/tmp/Rtmpv8TGzl/file3e3a139e9b9c"
> write.FCS(fr2, f2)
[1] "/tmp/Rtmpv8TGzl/file3e3a192304a7"
> fs <- read.ncdfFlowSet(c(f1, f2))
Not all FCS files have the same channels

Only load the following common channels:
FSC-H
SSC-H
FL1-H
FL2-H
FL3-H
FL2-A
FL4-H
Time
Skip the channels that are not found in all samples:

write file3e3a139e9b9c to empty cdf slot...
write file3e3a192304a7 to empty cdf slot...
done!
> fs
An ncdfFlowSet with 2 samples.
NCDF file : /tmp/Rtmpv8TGzl/ncfs3e3a1bfec01b.nc 
An object of class 'AnnotatedDataFrame'
  rowNames: file3e3a139e9b9c file3e3a192304a7
  varLabels: name
  varMetadata: labelDescription

  column names:
    FSC-H, SSC-H, FL1-H, FL2-H, FL3-H, FL2-A, FL4-H, Time
```

**Comment by algebio** [comment]
Thank you
