### ISSUE TITLE
Make the documentation clearer about alias/channels partial matching

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#162]
**Describe the bug**
I don't see any benefit of the partial matching as it could **silently** rename channels without alias.

**To Reproduce**

``` r
df <- data.frame(channels = c("CD45"), alias = c("CD46"))
alias_env <- flowCore:::check_channel_alias(df)
ls(alias_env)
#> [1] "CD45"
update_channel_by_alias(c("CD45RA"), alias_env)
#> [1] "CD46"
```

**Expected behavior**
CD45RA is not CD45, so it should not be renamed. It is unexpected to me that the word "CD45" of the channels column of the alias data frame will searched in the original name of the channels.
I think the documentation should warn about this behavior and should encourage to define every channel and it alias when a strict aliasing is desired.

**Comment by jacobpwagner** [comment]
I chose a poor example in CD45RA, but per the comments on #103 and 21da515d7fe055b20505940fff3fe5725cb85575, the partial matching was added in part to cover cases like `V545` matching to `V545-A`, which seems more reasonable. I can expand on the `channel_alias` section of the doc.

**Comment by mikejiang** [comment]
If only `CD45RA` is present in the data, isn't it the intended behavior for supplying `data.frame(channels = c("CD45"), alias = c("CD46"))`?  I don't see the alternative interpretation of it

**Comment by SamGG** [comment]
@jacobpwagner `-A` example makes definitively sense for partial matching. I think the doc should highlight such an example, but still warn about border effects.
@mikejiang my example intended to point my exact worry. In real life, the channels and alias would be larger making it even more complicated to find out a silent partial match.

**Comment by jacobpwagner** [comment]
Alright. I'll leave the partial matching in place, but update the doc.

**Comment by jacobpwagner** [comment]
Expanded in 3d261a3e3d85153a1d5c80cac3a7f4e9fec95b19

**Comment by SamGG** [comment]
That's perfect. Thanks.
