### ISSUE TITLE
$PnR should be an integer

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#163]
I think so, at least because the maximum value of a channel derives from an Analog to Digital Converter. IIRC flowIO returns an error because '.' is not allowed in numerical values.

IMHO, the following line
https://github.com/RGLab/flowCore/blob/3d261a3e3d85153a1d5c80cac3a7f4e9fec95b19/R/IO.R#L1769

should be followed by 
`pnr[empty_range_ind] <- floor(pnr[empty_range_ind]) + 1`

This addresses empty ranges only.

**Comment by jacobpwagner** [comment]
@SamGG Agreed. By the FCS 3.1 standard, `PnR` must be an integer value. I had to make some minor adjustments to your line. `pnr[empty_range_ind]` is a list that has to be converted to a vector for `floor` and `floor(x) + 1` will introduce an undesired increment when `x` is already an integer, so I went with `ceiling`.

**Comment by SamGG** [comment]
My interpretation is based on p14 of [FCS 3.1 pdf](http://software.broadinstitute.org/cancer/software/genepattern/attachments/fcs_3_1_standard.pdf) concerning integer.

>  $P1R/1024/ specifies that parameter 1 values range from 0 to 1023.

Unfortunately, there is no example for float. Adding 1 ensures that there is no side effect of truncate_max_range, as I already experienced with a parameter encoding cluster identifiers as integers.

**Comment by jacobpwagner** [comment]
The float case is discussed on page p24, though:
> For $DATATYPE/F/ and $DATATYPE/D/ this keyword specifies the maximum range, n1, of
> parameter n used to acquire the data. $DATATYPE/F/ with $PnR/262144/ is commonly used by
> some instruments. The actual value stored in the data set may exceed this range on both sides of
> the interval. Specifically, there may be negative values as well as values greater than n1, e.g., as
> a consequence of compensation. No bit mask shall be applied when reading $DATATYPE/F/ or
> $DATATYPE/D/ data.

I'm curious about the side effect you're seeing. `ceiling` should push the the `$PnR` value beyond the maximum value in the data, so no truncation should occur upon reading the file back in. If you are concerned about the `-1` adjustment in the default case here in `readFCSdata`...
https://github.com/RGLab/flowCore/blob/a0157d8ac4786f0b548f2c487c06bef532bfa6a9/R/IO.R#L1226-L1252

...that occurs after the truncation:
https://github.com/RGLab/flowCore/blob/a0157d8ac4786f0b548f2c487c06bef532bfa6a9/R/IO.R#L1184-L1193

So no values within the explicitly written out `$PnR` should be affected. It does still alter the "ranges" attribute, unfortunately. So you can still get situations like this:
```
> fr2
flowFrame object 'file366747461876'
with 250 cells and 4 observables:
    name desc range  minRange maxRange
$P1    A    A     3 -2.888921        2
$P2    B    B     4 -3.008049        3
$P3    C    C     3 -2.939774        2
$P4    D    D     4 -2.996949        3
44 keywords are stored in the 'description' slot
> attr(exprs(fr2), "ranges")
[1] 2 3 2 3
> colMaxs(exprs(fr2))
[1] 2.497662 3.810277 2.675741 3.055742
```
The data values are not truncated, but the attribute is incorrect. It should be `3 4 3 4`.

**Comment by SamGG** [comment]
Thanks for this clear analysis.

The bug I noticed occurred in cytofkit. The range was computed as (max - min), which is the usual definition, except for FCS where the min is zero whatever the lowest value is. As I have no time to dive into the real cause (end of a student scholarship), I updated the range parameter of the cluster identifier channel by (max + 1).

**Comment by SamGG** [comment]
Hi,
Mike's comment about Premessa #169 awakes me to have a second view on this issue.
@Mike the 1st range call in #169 refers to fr1 whereas it should be fr.

**Short story**: as range parameter should 1024 when the maximum value (of the data) is 1023, I think the current handling of missing $PxR is incorrect. If I understand correctly, when there is no $PxR the process is following: the max is computed and assigned to the range parameters, what is not compliant with the FCS standard as the range is higher than the max in the example (restricted to integers).

https://github.com/RGLab/flowCore/blob/b196fd4ca55ab5093ee61ef03c97abc9fb5eaea1/R/IO.R#L1764-L1768



**Long story**: I made a few tests with my current flowCore installation that does not match the devel version. 
In example 1 of case 2, maxRange is 99 when max is 100.
In example 2 of case 2, maxRange is 100 and range is 100.
In both examples of case 2, the values are not compliant to FCS 3.1 because
the standard states that $P1R/1024/ specifies that parameter 1 values range from 0 to 1023.

I can't clearly guess how to handle min, max and range of floats in FCS 3.1.
The current handling of floats sounds OK as it does not hurt the data during a write/read process,
but maxRange is lower than max(marker). I didn't check how FlowJo manages floats.

Could you check those points in the developpment version? Thanks.

I am still in favor of floor(colMax())+1 instead of ceiling(colMax())

``` r
library(flowCore)
packageVersion("flowCore")
#> [1] '1.52.1'

# = case #1 =========
# Starting with Mike's example based on integers
# Here we reproduce the effect due to the interpretation of the word "range"
# range seems to be in fact the maximum value in FCS definition
# Premessa and other scripts subtract the minimum value leading to a range lower than maximum value
# This range value is written in the header, read back and used to truncate the read values

mat <- matrix(1:100, ncol = 1, dimnames = list(NULL, "APC-A"))
fr <- flowFrame(mat)
keyword(fr)[["$P1R"]] <- 99 ##mimic the effect of `premessa::as_flowFrame`
range(fr, "data")
#>     APC-A
#> min     1
#> max   100
max(exprs(fr))
#> [1] 100

tmp <- tempfile()
invisible(write.FCS(fr, tmp))

fr1 <- read.FCS(tmp)  # truncate_max_range = TRUE by default
range(fr1, "data")
#>     APC-A
#> min     1
#> max    99
fr1
#> flowFrame object 'filed40367a69d3'
#> with 100 cells and 1 observables:
#>      name  desc range minRange maxRange
#> $P1 APC-A APC-A    99        0       98
#> 23 keywords are stored in the 'description' slot
max(exprs(fr1))
#> [1] 99

# Truncation occured: true maximum value is lower than original
# The maxRange is lower than the true max


# = case #2 =========
# Integer example handled currently (check flowCore version I used)
# No minimum subtraction seems to occur

fr <- flowFrame(mat)
range(fr, "data")
#>     APC-A
#> min     1
#> max   100
fr
#> flowFrame object 'anonymous'
#> with 100 cells and 1 observables:
#>      name  desc range minRange maxRange
#> $P1 APC-A APC-A   100        1      100
#> 0 keywords are stored in the 'description' slot
max(exprs(fr))
#> [1] 100

tmp <- tempfile()
invisible(write.FCS(fr, tmp))

fr1 <- read.FCS(tmp)  # truncate_max_range = TRUE by default
keyword(fr1)[["$P1R"]]
#> [1] "100"
range(fr1, "data")
#>     APC-A
#> min     1
#> max   100
fr1
#> flowFrame object 'filed407a89ea1'
#> with 100 cells and 1 observables:
#>      name  desc range minRange maxRange
#> $P1 APC-A APC-A   100        0       99
#> 23 keywords are stored in the 'description' slot
max(exprs(fr1))
#> [1] 100

# NO truncation occured: all values are lower or equal to $PxR
# The maxRange is lower than the true max and the original range

tmp1 <- tempfile()
invisible(write.FCS(fr1, tmp1))

fr2 <- read.FCS(tmp1)  # truncate_max_range = TRUE by default
keyword(fr2)[["$P1R"]]
#> [1] "100"
range(fr2, "data")
#>     APC-A
#> min     1
#> max   100
fr2
#> flowFrame object 'filed407a89ea1'
#> with 100 cells and 1 observables:
#>      name  desc range minRange maxRange
#> $P1 APC-A APC-A   100        0      100
#> 24 keywords are stored in the 'description' slot
max(exprs(fr2))
#> [1] 100

# NO truncation occured
# The maxRange is equal to the true max and the original range
# The maxRange changed althought the data are the same


# ==========
# Float example handled currently (check flowCore version I used)

fr <- flowFrame(mat+0.01)
range(fr, "data")
#>      APC-A
#> min   1.01
#> max 100.01
fr
#> flowFrame object 'anonymous'
#> with 100 cells and 1 observables:
#>      name  desc  range minRange maxRange
#> $P1 APC-A APC-A 100.01     1.01   100.01
#> 0 keywords are stored in the 'description' slot
max(exprs(fr))
#> [1] 100.01

tmp <- tempfile()
invisible(write.FCS(fr, tmp))

fr1 <- read.FCS(tmp)  # truncate_max_range = TRUE by default
keyword(fr1)[["$P1R"]]
#> [1] "101"
range(fr1, "data")
#>      APC-A
#> min   1.01
#> max 100.01
fr1
#> flowFrame object 'filed4057fd35cf'
#> with 100 cells and 1 observables:
#>      name  desc range minRange maxRange
#> $P1 APC-A APC-A   101        0      100
#> 23 keywords are stored in the 'description' slot
max(exprs(fr1))
#> [1] 100.01

# NO truncation occured 
# The maxRange is lower than the true max and the original range
# but range parameter includes all the values

# ==========
# Float example handled currently (check flowCore version I used)

fr <- flowFrame(mat+0.99)
range(fr, "data")
#>      APC-A
#> min   1.99
#> max 100.99
fr
#> flowFrame object 'anonymous'
#> with 100 cells and 1 observables:
#>      name  desc  range minRange maxRange
#> $P1 APC-A APC-A 100.99     1.99   100.99
#> 0 keywords are stored in the 'description' slot
max(exprs(fr))
#> [1] 100.99

tmp <- tempfile()
invisible(write.FCS(fr, tmp))

fr1 <- read.FCS(tmp)  # truncate_max_range = TRUE by default
keyword(fr1)[["$P1R"]]
#> [1] "101"
range(fr1, "data")
#>      APC-A
#> min   1.99
#> max 100.99
fr1
#> flowFrame object 'filed404952895'
#> with 100 cells and 1 observables:
#>      name  desc range minRange maxRange
#> $P1 APC-A APC-A   101        0      100
#> 23 keywords are stored in the 'description' slot
max(exprs(fr1))
#> [1] 100.99

# NO truncation occured 
# The maxRange is lower than the true max and the original range
# but range parameter includes all the values
# No rounding effect on the range, minRange and maxRange values

floor(100) + 1
#> [1] 101
floor(100.01) + 1
#> [1] 101
floor(100.99) + 1
#> [1] 101
```

<sup>Created on 2020-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
