### ISSUE TITLE
read.FCS: data truncation occurs only if no transformation was applied

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#164]
https://github.com/RGLab/flowCore/blob/3d261a3e3d85153a1d5c80cac3a7f4e9fec95b19/R/IO.R#L1183-L1192

IMHO the doc should report this.

**Comment by SamGG** [comment]
Sorry for being picky.

Instead of
`measurement range .i.e.'$PnR'. This truncation only occurs if no transformation
#' has been applied to the measured values.`
I think the following is more precise
measurement range .i.e.'$PnR'. When the transformation keyword of the FCS header is
set (typically to "custom" or "applied"), no truncation will occur.

A similar note should be set for min.limit

**Comment by jacobpwagner** [comment]
Yeah. Sorry. I think you're right about that. I switched it to your language and added a note to `min.limit`

**Comment by SamGG** [comment]
Sounds perfect. Thanks.
