### ISSUE TITLE
write.FCS bug

### ISSUE THREAD

**Issue by OuNao** [RGLab/flowCore#165]
Hi,

write.FCS routine do a wrong check for $PnR keyword

https://github.com/RGLab/flowCore/blob/4cf9283eba550ced0f2963c9ae4989f8f4b3ddaa/R/IO.R#L1759
https://github.com/RGLab/flowCore/blob/4cf9283eba550ced0f2963c9ae4989f8f4b3ddaa/R/IO.R#L1766

Must be:
```
pne <- orig.kw[paste0("$P", pid, "E")]
pnr <- orig.kw[paste0("$P", pid, "R")]
```

Regards,

**Comment by jacobpwagner** [comment]
Hi @OuNao. Actually, if you trace the code, `pid` already has the "$" included, so we don't need to (and shouldn't) prepend another "$". For an example `flowFrame` `x`, these `pid` values are coming from here:
```
> rownames(pData(parameters(x)))  # These will be the values of pid in write.FCS
 [1] "$P1"  "$P2"  "$P3"  "$P4"  "$P5"  "$P6"  "$P7"  "$P8"  "$P9"  "$P10" "$P11" "$P12"
```

**Comment by OuNao** [comment]
Hi,

This is very strange...
```
> rownames(pData(parameters(x)))
 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15" "16" "17" "18" "19" "20" "21" "22" "23"
[24] "24" "25" "26" "27" "28" "29" "30" "31" "32"
```
Your result justify the code:
https://github.com/RGLab/flowCore/blob/4cf9283eba550ced0f2963c9ae4989f8f4b3ddaa/R/IO.R#L1751-L1752
For me, this 2 lines results the same. The first as character and the second as integer...
Any idea?
Maybe flow workspace version?

**Comment by OuNao** [comment]
Sorry,

I found the problem.
The above result is from a flowframe created with 
```
new("flowFrame", exprs=matriz, parameters=Biobase::AnnotatedDataFrame(meta))
```
This constructor must be the problem.

Thanks,

**Comment by jacobpwagner** [comment]
Ah, yeah. That would do it. If `parameters` is missing from the constructor, it will prepend the `$P` to the row numbers for you (see `parDefault` in `AllClasses.R`). If you provide it, then you need to ensure that is the case.

**Comment by OuNao** [comment]
Yes,

I needed to use:
```
rownames(meta)<-sprintf("$P%s", 1:nrow(meta))
```
before the constructor.

Thanks,

**Comment by mikejiang** [comment]
`new("flowFrame")` is not constructor , that said ,`flowFrame()` constructor or class itself probably could use some validity check to catch it at the early stage.

**Comment by jacobpwagner** [comment]
Right. I somehow glanced right past the `new` and to the `parameters`.

**Comment by OuNao** [comment]
> `new("flowFrame")` is not constructor , that said ,`flowFrame()` constructor or class itself probably could use some validity check to catch it at the early stage.

Yes, flowFrame() works better than new("flowFrame"). But I still need to force creation of $PnR keywords for the correct value that represents the ADC range of the cytometer (and pass to flowFrame() function as description option). The write.FCS function use maxRange as $PnR but this didn´t represents the correct ADC range.
In my code I need to "normalize" the values by the ADC range (value/$PnR) and use maxRange as $PnR makes the computation wrong.

However, I think that there´s no way to infer the correct ADC range from a Matrix of data. Maybe selecting the best from common values (1024, 10000, 262144).

For my work I know the correct ADC range values set correctly the $PnR keywords with no problem.

Thanks again.

**Comment by mikejiang** [comment]
Actually the normal way to construct a `flowFrame` is using `read.FCS` since everything (including `$PnR` ) are well defined/stored in FCS files. `flowFrame()` constructor is still considered as hackish thus has rarely been used. I don't know what is the context of your use case that forced you to construct  the flowframe that way?

**Comment by OuNao** [comment]
Hi,

I'm using ML algorithms to impute new markers. So, for these new markers, I need to force a $PnR value (based on input markers, easy!).

Regards,
