### ISSUE TITLE
Does replace method replace the entire description of a flowFrame?

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#166]
Maybe I don't understand what "replace" means in the context of the description of a flowFrame.  I thought the description will contain only the given keywords. It looks like the replacement of a list keywords. Update the doc (not the code)?

https://github.com/RGLab/flowCore/blob/a0157d8ac4786f0b548f2c487c06bef532bfa6a9/R/AllClasses.R#L175

``` r
library(flowCore)
data("GvHD")
ff <- GvHD[[1]]
description(ff)
#> $FCSversion
#> [1] "2"
#> 
#> $`$BYTEORD`
#> [1] "4,3,2,1"
#> 
#> $`$DATATYPE`
#> [1] "I"
#> 
#> $`$NEXTDATA`
#> [1] "0"
#> 
#> $`$SYS`
#> [1] "Macintosh" "System"    "Software"  "9.0.4"    
#> 
#> $CREATOR
#> [1] "CELLQuestª" "3.3"       
#> 
#> $`$TOT`
#> [1] "3420"
#> 
... cut ...
#> $transformation
#> [1] "applied"
description(ff) <- list(sam = "dummy")
description(ff)
#> $FCSversion
#> [1] "2"
#> 
#> $`$BYTEORD`
#> [1] "4,3,2,1"
#> 
#> $`$DATATYPE`
#> [1] "I"
#> 
#> $`$NEXTDATA`
#> [1] "0"
#> 
#> $`$SYS`
#> [1] "Macintosh" "System"    "Software"  "9.0.4"    
#> 
#> $CREATOR
#> [1] "CELLQuestª" "3.3"       
#> 
#> $`$TOT`
#> [1] "3420"
#> 
... cut ...
#> $transformation
#> [1] "applied"
#> 
#> $sam
#> [1] "dummy"
```

**Comment by jacobpwagner** [comment]
Yeah. The replacement method `description<-` is functionally equivalent to `keyword<-`. If you want to do a full replacement, you can always just directly access the slot:
`fr@description <- replacement_description`

Updated the doc.
