### ISSUE TITLE
fr_append_cols not working

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowCore#176]
**Describe the bug**
`fr_append_cols` throws an error when adding a named matrix with same number of rows. The old `cbind` still works but throws depreciated warning.

**To Reproduce**
```{r}
data(GvHD)
fr <- GvHD[[1]]
m <- matrix(1:2*nrow(fr), ncol = 2)
colnames(m) <- c("A", "B")
fr_apend_cols(fr, m)
```

**sessionInfo():**
flowCore v1.53.8

**Comment by jacobpwagner** [comment]
@DillonHammill , right you are. In updating the keywords, it looks like the code was assuming a single column was being added and that was the case being worked out by the tests. I'll probably add a few multi-column appending tests as well. But this should be fixed now.

**Comment by DillonHammill** [comment]
This is fixed now, thanks @jacobpwagner!
