### ISSUE TITLE
read.flowset with parallel option

### ISSUE THREAD

**Issue by jgarces02** [RGLab/flowCore#177]
Hi @flowCore-team, 

Thanks for so marvelous package! Here's my question/suggestion: is there any way to read in parallel those input files for `read.flowset` instead doing it one by one? I'm using a high number of FCSs with a lot of events and it takes a long time...

Thanks again!

**Comment by gfinak** [comment]
What version of the tools are you using? `sessionInfo()`?

**Comment by jgarces02** [comment]
_flowCore_1.50.0_

**Comment by mikejiang** [comment]
>a high number of FCSs with a lot of events
are better suitable for using on-disk based `ncdfFlow`, which has `read.ncdfFlowSet` that does support parallel read through `mc.cores` argument.

**Comment by jgarces02** [comment]
Perfect, and if I running on Windows?? :sweat:
```
Error in mclapply(groups, function(group) { : 
  'mc.cores' > 1 is not supported on Windows
Called from: mclapply(groups, function(group) {
    lapply(group, getChnlEvt)
}, mc.cores = mc.cores)
```

**Comment by mikejiang** [comment]
If you are willing to use Bioconductor development version (i.e. github version), there is `cytoset` provided by `flowWorkspace` , which is the replacement for `flowSet/ncdfFlowSet`. 
Simply call `load_cytoset_from_fcs` by passing `num_threads` argument to achieve better speed for parsing each file.

**Comment by jgarces02** [comment]
Ok, thanks a lot for your help! I've found another [package ](https://github.com/nathanvan/parallelsugar) that overwrites `mclapply` and makes it to work on Windows platforms... in case I'd have problems, I'll take the devel version. Thanks!
