### ISSUE TITLE
.fcs doesn't have the identical colnames as the other samples! (spillover matrix included in fcs files)

### ISSUE THREAD

**Issue by algebio** [RGLab/flowCore#178]
Hi
I have received several batches of fcs files from the same Symphony flow cytometer but one of them have a different number of columns in ff@description. When I try to create a flowset I get this error:

fs <- read.flowSet(here("data",md$file_name))
000053_export_BF208 w24 T FMO_CD45+.fcs doesn't have the identical colnames as the other samples!
Error in validObject(.Object) : 
  invalid class “flowSet” object: Some items identified in the data environment either have the wrong dimension or type.

I have read that I could use column.pattern to use only the columns of interest but I don't know which pattern to use to acquire them. This different batch has .fcs files with a ff@description list of 243 columns, the rest of the batches have a list of 267 columns.

Also when I export the columns of one "normal" file and one from the different batch using 
write.xlsx(ff1@description,"ff1.xlsx")
write.xlsx(ff2@description,"ff2.xlsx")

For the normal one I get just one row for column name and one for values (as expected) but for the different one I get 16 rows which are identical in all columns but those for the spillover matrix.

Is there any way in which I can delete this matrix from these fcs files and also delete the redundant rows? 

Regards
Juan

**Comment by SamGG** [comment]
Hi,
It's not easy to find out what could go wrong without the files. Is it possible of sharing a normal and un-normal file?

**Comment by gfinak** [comment]
Have a look at out cytoqc package on GitHub.com/RGLab/cytoqc
It's designed to quickly diagnose and standardize this type of problem.
You will have to transition to the new cytolib version however.


Greg Finak

**Comment by algebio** [comment]
Hi Sam

Thanks for helping.


[Link](https://newcastle-my.sharepoint.com/:u:/g/personal/njo47_newcastle_ac_uk/EbbQRF210gtAl9zbWhL9YpgB1UanP-lrDpdEvKcFBGdjTQ?e=1kpOPB) to ff1 (normal) and ff2 (abnormal)

Regards
Juan

**Comment by mikejiang** [comment]
You can alternatively use `read.ncdfFlowSet`, which will try to select the common channels across samples automatically. But by doing this, you are running risk of losing information from most files because of that single outlier file. So unless you are sure those extra channels are redundant, the best way is what @gfinak suggested, using `cytoqc` to check and standardize them before analysis.

**Comment by algebio** [comment]
Hi Greg

Thank you for helping

I'm trying to download cytoqc but I'm having trouble. When I try remotes::install_github("RGLab/cytoqc") I get this error:


Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'flowWorkspace' 3.34.1 is being loaded, but >= 3.35.11 is required
Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'cytoqc'
* removing 'C:/Users/njo47/R/win-library/3.6/cytoqc'
Error: Failed to install 'cytoqc' from GitHub:
  (converted from warning) installation of package ‘C:/Users/njo47/AppData/Local/Temp/RtmpOKZcaM/file21dc65d57671/cytoqc_0.99.2.tar.gz’ had non-zero exit status

I've tried to download the new version of flowWorkspace but I couldn't find it.

Regards
Juan

**Comment by mikejiang** [comment]
You will need to do the same (i.e. `install_github`) to `RProtoBufLib`, `cytolib` , `flowCore`, `flowWorkspace` in the order

**Comment by gfinak** [comment]
Everything is on github, not Bioconductor. See the RGLab gthub group site.
use
`remotes::install_github("RGLab/flowWorkspace") and so forth.
You'll need, `RProtoBufLib`, `cytolib`, `flowCore`, `flowWorkspace` `CytoML` `ggcyto` `cytoqc`
You might run into issues with the order of installation, you'd see errors as above, telling you a certain package is out of date, then just install that package.

Here's some cytoqc output on your files. One of them is compensated in flowjo, the other, seemingly isn't. Anyway I didn't investigate too deeply. But if you believe both are compensated and transformed to be comparable, then the channel names can be standardized.
[test.pdf](https://github.com/RGLab/flowCore/files/4350180/test.pdf)

**Comment by SamGG** [comment]
Same conclusion with commands you can run currently. ff1 is already compensated and exported without the spillover whereas ff2 has been exported with its matrix. Usually, we work on FCS with compensation matrix. So, IMHO, ff1 is "abnormal" whereas ff2 is "classical". To be part of a flowset, names must be identical, although one can use the alias argument IIRC.
Best.

``` r
library(flowCore)

ff1 = read.FCS("c:/demo/sampleGithub/ff1.fcs", transformation = FALSE, truncate_max_range = FALSE, min.limit = NULL)
ff2 = read.FCS("c:/demo/sampleGithub/ff2.fcs", transformation = FALSE, truncate_max_range = FALSE, min.limit = NULL)
ff1
#> flowFrame object '28a56e0b-d2c8-4f2b-acf2-ff29459149e3'
#> with 74024 cells and 23 observables:
#>                     name   desc  range minRange maxRange
#> $P1                FSC-A   <NA> 262144        0   262143
#> $P2                FSC-H   <NA> 262144        0   262143
#> $P3                FSC-W   <NA> 262144        0   262143
#> $P4                SSC-A   <NA> 262144        0   262143
#> $P5                SSC-H   <NA> 262144        0   262143
#> $P6                SSC-W   <NA> 262144        0   262143
#> $P7  FJComp-355 379_28-A   CD45 262144        0   262143
#> $P8  FJComp-355 515_30-A    CD4 262144     -111   262143
#> $P9  FJComp-355 580_20-A CD45RA 262144     -111   262143
#> $P10 FJComp-355 740_35-A    CD8 262144     -111   262143
#> $P11 FJComp-405 450_50-A pSTAT5 262144     -111   262143
#> $P12 FJComp-405 525_50-A    CD3 262144     -111   262143
#> $P13 FJComp-405 610_20-A   PD-1 262144     -111   262143
#> $P14 FJComp-405 710_50-A   CD25 262144     -111   262143
#> $P15 FJComp-405 780_60-A CTLA-4 262144     -111   262143
#> $P16 FJComp-488 530_30-A pSTAT1 262144        0   262143
#> $P17 FJComp-488 695_40-A pSTAT6 262144     -111   262143
#> $P18 FJComp-561 586_15-A   CD27 262144     -111   262143
#> $P19 FJComp-561 610_20-A   CD56 262144     -111   262143
#> $P20 FJComp-561 780_60-A   pERK 262144     -111   262143
#> $P21 FJComp-640 670_30-A pSTAT3 262144     -111   262143
#> $P22 FJComp-640 730_45-A   CD69 262144     -111   262143
#> $P23                Time   <NA>  15000        0    14999
#> 220 keywords are stored in the 'description' slot
ff2
#> flowFrame object '9ad3d225-93bd-4489-9117-3f08bcb88458'
#> with 58024 cells and 23 observables:
#>              name   desc  range   minRange maxRange
#> $P1         FSC-A   <NA> 262144    0.00000   262143
#> $P2         FSC-H   <NA> 262144    0.00000   262143
#> $P3         FSC-W   <NA> 262144    0.00000   262143
#> $P4         SSC-A   <NA> 262144    0.00000   262143
#> $P5         SSC-H   <NA> 262144    0.00000   262143
#> $P6         SSC-W   <NA> 262144    0.00000   262143
#> $P7  355 379_28-A   CD45 262144    0.00000   262143
#> $P8  355 515_30-A    CD4 262144    0.00000   262143
#> $P9  355 580_20-A CD45RA 262144    0.00000   262143
#> $P10 355 740_35-A    CD8 262144    0.00000   262143
#> $P11 405 450_50-A pSTAT5 262144    0.00000   262143
#> $P12 405 525_50-A    CD3 262144    0.00000   262143
#> $P13 405 610_20-A   PD-1 262144    0.00000   262143
#> $P14 405 710_50-A   CD25 262144  -16.25918   262143
#> $P15 405 780_60-A CTLA-4 262144 -111.00000   262143
#> $P16 488 530_30-A pSTAT1 262144    0.00000   262143
#> $P17 488 695_40-A pSTAT6 262144  -88.11304   262143
#> $P18 561 586_15-A   CD27 262144 -111.00000   262143
#> $P19 561 610_20-A   CD56 262144    0.00000   262143
#> $P20 561 780_60-A   pERK 262144  -64.67737   262143
#> $P21 640 670_30-A pSTAT3 262144 -111.00000   262143
#> $P22 640 730_45-A   CD69 262144  -91.88095   262143
#> $P23         Time   <NA>  15000    0.00000    14999
#> 196 keywords are stored in the 'description' slot
cbind(names(ff1), names(ff2))
#>       [,1]                                        [,2]                         
#>  [1,] "<FSC-A> FSC-A"                             "<FSC-A> FSC-A"              
#>  [2,] "<FSC-H> FSC-H"                             "<FSC-H> FSC-H"              
#>  [3,] "<FSC-W> FSC-W"                             "<FSC-W> FSC-W"              
#>  [4,] "<SSC-A> SSC-A"                             "<SSC-A> SSC-A"              
#>  [5,] "<SSC-H> SSC-H"                             "<SSC-H> SSC-H"              
#>  [6,] "<SSC-W> SSC-W"                             "<SSC-W> SSC-W"              
#>  [7,] "<FJComp-355 379_28-A> FJComp-355 379_28-A" "<355 379_28-A> 355 379_28-A"
#>  [8,] "<FJComp-355 515_30-A> FJComp-355 515_30-A" "<355 515_30-A> 355 515_30-A"
#>  [9,] "<FJComp-355 580_20-A> FJComp-355 580_20-A" "<355 580_20-A> 355 580_20-A"
#> [10,] "<FJComp-355 740_35-A> FJComp-355 740_35-A" "<355 740_35-A> 355 740_35-A"
#> [11,] "<FJComp-405 450_50-A> FJComp-405 450_50-A" "<405 450_50-A> 405 450_50-A"
#> [12,] "<FJComp-405 525_50-A> FJComp-405 525_50-A" "<405 525_50-A> 405 525_50-A"
#> [13,] "<FJComp-405 610_20-A> FJComp-405 610_20-A" "<405 610_20-A> 405 610_20-A"
#> [14,] "<FJComp-405 710_50-A> FJComp-405 710_50-A" "<405 710_50-A> 405 710_50-A"
#> [15,] "<FJComp-405 780_60-A> FJComp-405 780_60-A" "<405 780_60-A> 405 780_60-A"
#> [16,] "<FJComp-488 530_30-A> FJComp-488 530_30-A" "<488 530_30-A> 488 530_30-A"
#> [17,] "<FJComp-488 695_40-A> FJComp-488 695_40-A" "<488 695_40-A> 488 695_40-A"
#> [18,] "<FJComp-561 586_15-A> FJComp-561 586_15-A" "<561 586_15-A> 561 586_15-A"
#> [19,] "<FJComp-561 610_20-A> FJComp-561 610_20-A" "<561 610_20-A> 561 610_20-A"
#> [20,] "<FJComp-561 780_60-A> FJComp-561 780_60-A" "<561 780_60-A> 561 780_60-A"
#> [21,] "<FJComp-640 670_30-A> FJComp-640 670_30-A" "<640 670_30-A> 640 670_30-A"
#> [22,] "<FJComp-640 730_45-A> FJComp-640 730_45-A" "<640 730_45-A> 640 730_45-A"
#> [23,] "<Time> Time"                               "<Time> Time"

spillover(ff1)
#> Error in .local(x, ...): No spillover matrix stored in that flowFrame
spillover(ff2)
#> $SPILL
#> NULL
#> 
#> $spillover
#> NULL
#> 
#> $`$SPILLOVER`
#>        488 530_30-A  488 695_40-A  640 670_30-A  640 730_45-A  405 450_50-A
#>  [1,]  1.0000000000  0.0087742527  0.0001522889  0.0000000000  0.0002242005
#>  [2,]  0.0009161415  1.0000000000  0.3110333979  0.1049308289 -0.0006772935
#>  [3,]  0.0000000000  0.0036867042  1.0000000000  0.1000686065  0.0005152802
#>  [4,]  0.0010626574  0.0597967989  0.1749424015  1.0000000000  0.0006221916
#>  [5,]  0.0000873584 -0.0000124698 -0.0000249454  0.0000000000  1.0000000000
#>  [6,] -0.0589240311 -0.0363079144 -0.0125684212 -0.0027556974  0.1104656371
#>  [7,]  0.0000581734  0.0223415859  0.0027550926  0.0002907062  0.0317942843
#>  [8,]  0.0000895386  0.0985418499  0.0621138136  0.1200000000  0.0530510345
#>  [9,]  0.0000922506  0.0002238917  0.0008317569  0.0025808275  0.0301278725
#> [10,]  0.0000423005 -0.0000422737  0.0001268678 -0.0000422676  0.0016425714
#> [11,]  0.0079115567  0.0002444181  0.0002000078  0.0000000000  0.0014158249
#> [12,]  0.0308360697  0.0080000000  0.0002725048 -0.0000302615  0.0003134188
#> [13,] -0.0053138928  0.0620000000  0.0056739132  0.1250000000 -0.0055848097
#> [14,]  0.0108171640  0.1339711064  0.0003923144  0.0000326710  0.0002385262
#> [15,]  0.0028055665  0.0074775851 -0.0037395016  0.0018691161 -0.0013700067
#> [16,]  0.0011953111  0.2004580068  0.0019098182  0.0001680109 -0.0000350403
#>        405 525_50-A  405 610_20-A 405 710_50-A  405 780_60-A  355 379_28-A
#>  [1,]  0.0043727938  0.0011573340 0.0000761753 -0.0000761419 -0.0001251792
#>  [2,]  0.0013972404 -0.0046293246 0.4459468066  0.2296051453  0.0020081402
#>  [3,]  0.0006244668  0.0002657452 0.0014923605  0.0000000000  0.0000960952
#>  [4,] -0.0002159503 -0.0004292495 0.1662577504  0.0984107979  0.0004649244
#>  [5,]  0.0420013296  0.0061003645 0.0006748761  0.0003869166  0.0001231848
#>  [6,]  1.0000000000  1.0382977609 0.1764350731  0.0860357732 -0.0111347335
#>  [7,]  0.0014926178  1.0000000000 0.2068694651  0.0946126376 -0.0000211310
#>  [8,]  0.0026641297  0.0012388460 1.0000000000  0.6361299063 -0.0000196051
#>  [9,]  0.0016913714  0.0011411014 0.0084945193  1.0000000000 -0.0000575505
#> [10,]  0.0003009579 -0.0000427234 0.0001691982 -0.0000422830  1.0000000000
#> [11,]  0.0113052260  0.0040784010 0.0004225582  0.0001778142  0.0115373909
#> [12,]  0.0023015212  0.0175377567 0.0014254641  0.0005148059  0.0535849448
#> [13,] -0.0043669503 -0.0046104615 0.0400000000  0.0670000000  0.0270771363
#> [14,]  0.0009662515  0.0936584335 0.0094556846  0.0027867014 -0.0000357540
#> [15,]  0.0009503713  0.0009440935 0.0037406710  0.1818293594 -0.0020485878
#> [16,]  0.0000569562  0.0904532665 0.0145444868  0.0053399138 -0.0000087485
#>       355 515_30-A  355 580_20-A 355 740_35-A  561 586_15-A  561 780_60-A
#>  [1,] 0.0791022600  0.0033769029 0.0000380644  0.0000380611 -0.0000761173
#>  [2,] 0.0102529063  0.0000000000 0.0842034240  0.0009156088  0.0704547742
#>  [3,] 0.0024385028  0.0001769897 0.0011404857  0.0001754159  0.0073801828
#>  [4,] 0.0020049418  0.0002143672 0.1232984422  0.0004247438  0.1029931753
#>  [5,] 0.1707236876  0.0031839345 0.0000872960 -0.0000374095 -0.0000249373
#>  [6,] 3.9382323529  0.4260500351 0.0307695495 -0.0092772813 -0.0069802558
#>  [7,] 0.0047447100  0.0489008562 0.0396583016  0.1065106896  0.0178926134
#>  [8,] 0.0078374547  0.0002532297 0.2499671761  0.0000178947  0.0126734236
#>  [9,] 0.0054570316  0.0002663173 0.0368349443  0.0000395045  0.0080793920
#> [10,] 0.4947291176  0.0081980042 0.0003804738  0.0000000000  0.0000000000
#> [11,] 1.0000000000  0.0393472801 0.0012012666  0.0000444340  0.0000222147
#> [12,] 0.1239695095  1.0000000000 0.0150000000  0.2292224199  0.0030946655
#> [13,] 0.0209359754 -0.0014810000 1.0000000000 -0.0010415691  0.0111794674
#> [14,] 0.0002041558  0.1886103385 0.0031805995  1.0000000000  0.0116522650
#> [15,] 0.0000000000  0.0000000000 0.0140230879  0.0102820766  1.0000000000
#> [16,] 0.0002011862  0.0087048147 0.0060339919  0.1032546205  0.0227565531
#>        561 610_20-A
#>  [1,]  0.0000761910
#>  [2,]  0.0013747395
#>  [3,]  0.0000877991
#>  [4,]  0.0017007714
#>  [5,] -0.0000249615
#>  [6,] -0.0300007690
#>  [7,]  0.4946792360
#>  [8,]  0.0001074789
#>  [9,]  0.0000922822
#> [10,] -0.0000423118
#> [11,]  0.0000444775
#> [12,]  0.2696212580
#> [13,] -0.0025143750
#> [14,]  0.9589177074
#> [15,]  0.0159101499
#> [16,]  1.0000000000
```

<sup>Created on 2020-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by algebio** [comment]
Hi
Thank you very much to all of you for your answers. It´s been really helpful and I have learn a lot from them.

I didn´t know that most of my fcs files were not compensated. Also I didn't know that I should work with FCS instead of fcs files of a gated subpopulation of interest (T-cells).

I have spent the last 24 hours trying to install the recommended packages but I couldn't. I had a number of error messages, I could solve some of them but a number of packages require R 4.0 which I don't have installed on my Windows. I also had problems to find zip instead of tar which I think it's needed for Windows.

example of a common problem installing cytoqc:
"Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
namespace 'flowWorkspace' 3.34.1 is being loaded, but >= 3.35.11 is required"
I couldn't find the required version.

I'm really interested on using the RGLab software (I really liked the cytoqc report) but I don't have more time this week for this. Happy to try again this weekend if you give me some clues / guidance.

I will contact the lab and I'll explain the problem, hopefully they can provide new FCS compensated files.

I can see that I still have lots to learn about the basics of cytof analysis. If you have any resource for this or any advice on how to acquire essential information and good practice for cyto data analysis, I would really appreciate it.

Thanks again for all your advice.

Regards
Juan

**Comment by mikejiang** [comment]
You can install R-devel https://cran.r-project.org/bin/windows/base/rdevel.html
and install the binaries directly from bioconductor development branch, e.g.
`BiocManager::install("flowWorkspace", version = "devel")`

**Comment by DillonHammill** [comment]
FYI flowWorkspace binary is not currently available on BioC devel.

**Comment by algebio** [comment]
Ok, I'll wait until it's stable and available for Windows users. I definitively want to use cytoqc on my samples.

Thanks for letting me know.
