### ISSUE TITLE
flowcore is not available for R version 3.6.3

### ISSUE THREAD

**Issue by EDYAC** [RGLab/flowCore#181]
Hello everyone,
I can't install flowcore, I'm getting an error saying that flowcore is not available for R version 3.6.3
Any idea on what I should do?
Thank you

**Comment by mikejiang** [comment]
please provide your `sessionInfo ()` and the installation command as well as the error message

**Comment by EDYAC** [comment]
HI Mike,
I have re-installed R version 3.6.1 and now it's working. 
Thank you a lot.
