### ISSUE TITLE
Misc in version 1.99.20 (Bioc Dev)

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#182]
Hi,

filter_keywords is no more exported. Sure?

Author N. Le Meur is Nolwenn, not Nathan.
https://scholar.google.fr/citations?user=XdcsFHMAAAAJ&hl=fr

Thanks,
Samuel

**Comment by mikejiang** [comment]
Yes, it wasn't intended to be used by user. Do you have software that is calling it explicitly?

**Comment by SamGG** [comment]
Well I wanted to update the recent install of Bioc Dev from binary and I end up with that version. I was surprised by the big change of version. Sorry, I am not familiar with Bioc Dev.
I checked and the software has no call to filter_keywords, what was also surprising. I will come later to Bioc Dev.
Best.

**Comment by mikejiang** [comment]
Bioc devel will become release next month. So you'd better be prepared now rather than later. Also it also helps if you come across any backward compatibility issues and report to us.

**Comment by SamGG** [comment]
One more level of complexity... I'll look into that, and try again the software.
Should I do test with the current v1.99 or wait for a v1.5x in Bioc Devel?

**Comment by mikejiang** [comment]
The current bioc devel have flowCore1.99.20, I don't know where your 1.5 comes from.

**Comment by SamGG** [comment]
If I am correct, the current flowCore version is 1.52.1. I thought the big difference in version is only temporary and you will come back to a version number slightly higher than the current. Simple guess.

**Comment by mikejiang** [comment]
No. flowCore is depending or cytolib, which is undergoing the major changes. So we decided to make major version bumps to all the tool chain.

**Comment by SamGG** [comment]
Thanks for your time.

**Comment by SamGG** [comment]
Hi Mike,
In my original issue, I was asking for correcting the author description. Could you handle it?
Best,
Samuel

**Comment by jacobpwagner** [comment]
Author field fixed in https://github.com/RGLab/flowCore/commit/a53292d0d8ed14fc8ba39795583e01651f191d9f
