### ISSUE TITLE
Build Failure on Travis & Docker - Multiple Maintainers

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowCore#185]
Just a heads up, both my Travis and Docker builds are now failing because multiple maintainers are listed in the  `Author` field in `DESCRIPTION` for `flowCore`. Here is the latest [travis](https://travis-ci.org/github/DillonHammill/CytoExploreR/jobs/678003671) build.

All other packages (e.g. flowWorkspace and openCyto) list maintainers in a separate `Maintainer` field where this doesn't cause problems...

**Comment by jacobpwagner** [comment]
Sorry, I didn't know that it would throw an error for that. Hopefully it's good after this: https://github.com/RGLab/flowCore/commit/64a1b4684da2525fe0bdc558487187f402b25be6

**Comment by DillonHammill** [comment]
No worries, it is weird that it does not allow for multiple maintainers in the `Author` field.
