### ISSUE TITLE
Data from Guava is truncated, missing data points towards the higher values

### ISSUE THREAD

**Issue by Zymergen-alavy** [RGLab/flowCore#186]
I am trying to work with a FCS file that was generated on Guava flow cytometer.
When the data is plotted using FlowJo I I get the full range of values for the two channels I am interested in.
![FlowJo](https://user-images.githubusercontent.com/55605630/80551103-2ef2d080-8977-11ea-8403-fe5d8e7ab62c.png)

When loading the same file in FlowCore, with or without any transformation, it seems that the data is truncated.
```
file.name = "2019-02-07_at_03-07-59pm.F03.fcs"
x <- read.FCS(file.name, alter.names=TRUE, transformation=FALSE)
summary(x)
```
I get similar results with transformations.

![FlowCore1](https://user-images.githubusercontent.com/55605630/80551149-65305000-8977-11ea-9f66-d586e4e28a3c.png)

![Rplot](https://user-images.githubusercontent.com/55605630/80551282-d243e580-8977-11ea-9c67-e60aa3383f6a.png)

Please see FCS file attached.

[2019-02-07_at_03-07-59pm.F03.fcs.zip](https://github.com/RGLab/flowCore/files/4549264/2019-02-07_at_03-07-59pm.F03.fcs.zip)

Thank you!

**Comment by gfinak** [comment]
Please read the documentation.
