### ISSUE TITLE
Attach flowSet parameter ranges to each flowFrame

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowCore#188]
Hi @mikejiang and @jacobpwagner,

Just wondering if the parameter ranges for the entire cytoset are attached anywhere in the individual flowFrames/cytoframes?

It is often handy to know the full range of values when re-scaling parameters in the individual flowFrames/cytoframes. 

It would be nice if we could do something like this:
```{r}
range(cs[[1]], type = "set")
```

This will return the parameter ranges for the entire cytoset rather than just the supplied flowFrame/cytoframe. I am trying to do this without having access to the cytoset.

Is there a way to access cytoset information given the cytoframe pointer?

Thanks for your help!

Dillon

**Comment by mikejiang** [comment]
`cytoset` is a container that simply holds a collection of `cytoframe` objects. So no global range info is stored. You can easily compute it by iterating through `cytoset`, which should be fast and straightforward.

**Comment by DillonHammill** [comment]
Thanks @mikejiang, this is what I am currently doing. Just wanted to know if there was a better way. Thanks for your help!
