### ISSUE TITLE
Can an installation of flowcore read fcs files generated by a higher or lower version of flowcore?

### ISSUE THREAD

**Issue by pcm32** [RGLab/flowCore#193]
Hi there! Great work being done here. We are maintaining some Galaxy modules that use flowcore, we are wondering if we should pin all of them to the same flowcore version or whether we can leave the version of flowcore free in cases where the tools will have a main dependency that depends in turn in flowcore. For instance, we have modules that depend on flowai, which has in turn flowcore as a dependency. We can either pin the version of flowai and leave conda to pick the adequate version of flowcore, or we can pin both flowai and flowcore versions (this has some downsides when using this with containers though). 

I'm wondering if it could be somehow relevant to make sure that all our modules use the same version of flowcore, maybe because there could be incompatibilities when reading in flowcore version X FCS files written by flowcore version Y? Thanks!

**Comment by gfinak** [comment]
Reading and writing FCS files should not be an problem. The format is standardized and we comply with the standard as well as have regression tests to ensure backward compatibility.
