### ISSUE TITLE
Error in checkOffset

### ISSUE THREAD

**Issue by minghlijiyi** [RGLab/flowCore#196]
I have this issue in FlowCore 2.0.1 when I read the FCS file, the Rstudio version is 4.0, the FlowJO version is 10.7.  
The detail is "Error in checkOffset(offsets, txt, ...): The HEADER and the TEXT segment define different ending point (69993256:169993256) to read the data."
I tried > `devtools::install_github("RGLab/flowCore/trunk")`, but the error is "Error: Failed to install 'flowCore' from GitHub: Does not appear to be an R package (no DESCRIPTION)", could you give me some help? Thank you.

**Comment by jacobpwagner** [comment]
Your installation command is incorrect. First, if you were trying to specify the `trunk` branch, that would be done like this:
```
devtools::install_github("RGLab/flowCore", ref = "trunk")
```
But the main branch is also no longer called trunk (it changed to `master` a while back), so the command you actually want for installing from GitHub is just this:
```
devtools::install_github("RGLab/flowCore")
```

**Comment by minghlijiyi** [comment]
Thank you for your reply.
At first, I installed from Bioconductor the error happened, I just tried "devtools::install_github("RGLab/flowCore")", but it still happens error in checkoffset when I read the multi-data segments FCS file.

**Comment by mikejiang** [comment]
You can set `ignore.text.offset = TRUE`, to bypass the validity check. That said, you are running risk of getting incorrect data because there are inconsistencies in the FCS file and it is worth to investigate why it happens (from where the original FCS was generated) in the first place.

**Comment by SamGG** [comment]
In the HEADER segment, the location of the TEXT, DATA and ANALYSIS segments are encoded on 8 bytes using ASCII characters. 169993256 is 9 characters long. It will never match the 8 characters set in the HEADER. What is the size of this file? How many events? How many channels? Mike's solution is the best way to read such a probably huge file.
