### ISSUE TITLE
flowCore build failing on Travis

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowCore#199]
@mikejiang & @jacobpwagner, I haven't been able to get flowCore to build on travis for a while now. Just wondering if you are also encountering the error that I am seeing on my linux [travis]( https://travis-ci.org/github/DillonHammill/CytoExploreR/jobs/720511938) builds? I see that your flowCore build is passing with a different travis configuration, perhaps I should update my configuration to match yours or maybe maintaining a separate configuration will help pick up build errors?

Thanks for your help!
Dillon

**Comment by mikejiang** [comment]
let me know if it fixes your travis build

**Comment by DillonHammill** [comment]
Thanks @mikejiang, I will force a new build now and let you know how it goes.

**Comment by DillonHammill** [comment]
Thanks @mikejiang, this is working now.
