### ISSUE TITLE
Issue adding flowCore to my library

### ISSUE THREAD

**Issue by elevendoky** [RGLab/flowCore#208]
Hello, I am trying to add flowCORe to my library after successfully downloading it. Issue is that whenever i try to do `library(flowCore)` I get this error
`Error: package or namespace load failed for ‘flowCore’:
 .onLoad failed in loadNamespace() for 'cytolib', details:
  call: dyn.load(cytolib, local = FALSE, now = TRUE)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/cytolib/libs/cytolib.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/cytolib/libs/cytolib.so, 10): Symbol not found: __ZN6google8protobuf8internal17UnknownFieldParseEjPNS1_29InternalMetadataWithArenaLiteEPKcPNS1_12ParseContextE
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/cytolib/libs/cytolib.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/cytolib/libs/cytolib.so`

I have no idea what this means or how to fix it. (I also get the same issue when I try to add cytolib to my library.) Any suggestions?

**Comment by gfinak** [comment]
You need to have RProtoBufLib installed.
You may also need to build these packages from source.

**Comment by elevendoky** [comment]
I downloaded RProtoBufLib but it did not help (still getting the same error). How do I build the packages from the source? Thanks!

**Comment by mikejiang** [comment]
To ensure the consistency of all your flow tools, the best way is to use `BiocManager::install` to install the relevant packages from the current bioc release (i.e. 3.12).

**Comment by elevendoky** [comment]
I downloaded everything under the flowCore bioconductor imports (Biobase, BiocGenerics(>= 0.29.2), grDevices, graphics, methods, stats, utils, stats4, Rcpp, matrixStats, cytolib(>= 1.9.15), S4Vectors). I can add everything to my library except cytolib (get the same error as above). Is there additional packages I need to download?

**Comment by elevendoky** [comment]
Thank you that worked! I just had to restart R after. Thanks for your help!
