### ISSUE TITLE
Manual Compensation Matrix from Diva software may cause unreadability with read.FCS; SPILLOVER keyword

### ISSUE THREAD

**Issue by Close-your-eyes** [RGLab/flowCore#209]
Dear all,

I have a problem reading a FCS files. When calling read.FCS(x) an error occurs:

$SPILLOVER keyword value is of improper size for number of spillover channels!
Error in string_to_spill(txt) : 
  $SPILLOVER size discrepancy could not be resolved!

In comparison to other files that I have and that can be read by read.FCS(x) this file was subject to manual compensation (not the compensation wizard) with the FACS Diva Software on a BD device.
Interestingly, FlowJo does not show the compensation matrix as usual but the Spill-Matrix is in the FCS file's keywords or parameters.

When I import the File to FlowJo and then export it again, read.FCS(x) works. So, somehow FlowJo is able to fix the file but of course I would like to understand the underlying problem.

Question: Did the Diva Software or our Device mess up the FCS file for some reason or is a minor inconsistency in the fcs file treated very strictly by read.FCS(x)?

I just send a respective fcs file which is the only way to help me I think:

https://www.dropbox.com/s/2zmfzk61g93fyhb/Specimen_001_frisch_unst_ad_002.fcs?dl=0

Thanks.

**Comment by SamGG** [comment]
Hi,
The PC running Diva is configured with comma (",") as the decimal point. So 0.95 is written as 0,95. The FCS standard encodes the spillover matrix in a long string where the numbers are separated by comma. So it's hard to decode using the comma as a separator.
Here is what your file looks like
``` r
library(flowCore)
ff = read.FCSheader("C:/data/active/support/tempo/Specimen_001_frisch_unst_ad_002.fcs")
ff[[1]]["SPILL"]
#>                                                                                                                                                                                                                                                                                                                                                               SPILL 
#> "8,b-LP502 530/30-E-A,PE-A,b-LP655 LP670-B-A,b-LP735 780/60-A-A,r-660/20-C-A,r-LP685 720/30-A-A,v-450/50-B-A,v-LP502 510/50-A-A,1,0,109,0,0,0,0,0,005,0,0,019,1,0,0,017,0,0,0,0,0,0,1,0,0,0,0,0,0,0,013000000000000001,0,1,0,0,078,0,0,0,0,0,0,004,1,0,28600000000000003,0,0,0,0,0,0,027000000000000003,0,055999999999999994,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1"
```
Contact your IT to change the decimal separator in Windows 7.
You might ask/search how to do on the cytometry list of Perdue.
Maybe the unajdusted FCS file is correctly encoded.
I admit I didn't understand your point concerning FlowJo. If you mean that although the matrix is shown as a keyword by FJ, FJ does not load the matrix, it makes sense.
Best.

**Comment by Close-your-eyes** [comment]
Thank you Sir. In deed this seemed to be the problem. Changing the language settings affects how Diva writes the FCS file.

I wonder though: Isn't it stupid that the Diva Software does not obey to the FCS standard but uses the local settings?! 

It is hilarious because even Diva tells me that there is a problem with those files that contain commas in the compensation matrix. (It does not say this explicitly though.)

PS: I gave references to FlowJos behaviours as potential hints to solve this issue.

**Comment by SamGG** [comment]
IIRC, Diva is based on Java. I saw some changes in Java programs concerning the localization, ie decimal separator, date... It is even worse than you think: if Windows is set up with a dot as a decimal separator, Java is able to detect the "real" localization and forces the separator to be a comma.
I think FlowJo simply ignores the matrix as it is badly formatted. But I didn't check it.
If you are OK with these information, close the issue.
Best,
Samuel
