### ISSUE TITLE
Error in UseMethod("filter") 

### ISSUE THREAD

**Issue by EmCutlerUCL** [RGLab/flowCore#213]
Hi there,

I'm having problems filtering cells using the package. There seems to be a problem even when i'm using the example GvHD disease data. 

I've attached the example code i'm using and the error code i'm getting. 

![image](https://user-images.githubusercontent.com/79911814/116589236-58d92d00-a914-11eb-8514-46fbe419421e.png)

Does anyone have idea what 'Error in UseMethod("filter") : 
  no applicable method for 'filter' applied to an object of class "flowSet" means? 

Thanks,
Emily

**Comment by mikejiang** [comment]
Did you library(flowCore)?

**Comment by EmCutlerUCL** [comment]
Hi Mikejiang, 

Thanks for getting back to me. Yes I have 'library(flowCore)' at the top of my notebook.
