### ISSUE TITLE
Merging .fcs files from replicates

### ISSUE THREAD

**Issue by carolina671** [RGLab/flowCore#220]
HI, is there a way of pooling or concatenating .fcs into one single file?  I have sample replicates for a single sample and would like to combine the files by row (cells)  as the yhave the same columns (channels). I would like to do this with the raw data before gating....

I tried fcs_pool from phenoflow but i just end up with a flowframe with the same amount of replicates.

**Comment by mikejiang** [comment]
try this
```r
 library(flowCore)
> data("GvHD")
> fr1 = GvHD[[1]]
> fr2 = GvHD[[2]]
> nrow(fr1)
[1] 3420
> nrow(fr2)
[1] 3405
> fs = flowSet(list(fr1, fr2))
> fr = as(fs, "flowFrame")
> nrow(fr)
[1] 6825
> fn = tempfile()
> write.FCS(fr, fn)
```
