### ISSUE TITLE
apply estimateLogicle and transform to a matrix or data frame

### ISSUE THREAD

**Issue by fbenedett** [RGLab/flowCore#223]
Hello,

I am working with data that are very similar to flow cytometry but the format of the file is not fcs, it's csv, therefor it lacks a lot of the metadata of a fcs file.
My problem is relatively simple, is there a way to use the functions:
estimateLogicle and transform on a matrix or a dataframe?
Something like:
lgcl=estimateLogicle(cell_data, channels=the_channels, m=4.9)
fset=transform(cell_data, lgcl)

where cell_data is a data frame or a matrix.
Thanks for any advice.

**Comment by mikejiang** [comment]
You can create a flowframe out of a matrix
```r
> library(flowCore)
> mat = matrix(rnorm(10), 2 , 5)
> colnames(mat) = letters[1:5]
> mat
             a         b           c         d          e
[1,] -0.798732 -1.393017  0.08361935 0.9910978  1.1498790
[2,]  1.299410  1.047789 -0.11636546 0.9242092 -0.3335247
> fr = flowFrame(mat)
> fr
flowFrame object 'file2a5c6763cfca2'
with 2 cells and 5 observables:
           name        desc     range  minRange  maxRange
$P1           a           a         3 -0.798732         2
$P2           b           b         3 -1.393017         2
$P3           c           c         2 -0.116365         1
$P4           d           d         2  0.000000         1
$P5           e           e         3 -0.333525         2
51 keywords are stored in the 'description' slot
```
Then you should be able to use all the APIs of flow frame object

**Comment by fbenedett** [comment]
Thank you, that solved it.
