### ISSUE TITLE
descriptions parameter of read.flowSet does not seem to do anything

### ISSUE THREAD

**Issue by phauchamps** [RGLab/flowCore#226]
Hi dear flowCore team,

I am a PhD student working in Laurent Gatto's CBIO Lab de Duve Institute/UCLouvain in Brussels.
My PhD thesis (started in September last year) is about automated and data driven analysis and viz of flow cytometry data, and so I am now paying a bit with the R packages that are part of the Cytoverse :-) 

This morning I came accross a weird non-behavior, which I guess might be a bug.

when calling read.flowSet and explicitely setting the *descriptions* parameter like this : 

raw_FS <- read.flowSet(paste0(dataset_dir, files), transformation = "linearize",
                       alter.names = FALSE,
                       name = "ImmS",
                       descriptions = paste0("Donor_", seq(nDonors)),
                       truncate_max_range = FALSE)

According to the help documentation : 
*descriptions : Character vector to annotate the object of class flowSet.*, 

Therefore I was expecting my vector of description chars to be part of *pData(raw_FS)* but it is not.
Looking into the code of read.flowSet, I did not manage to find any use of the *descriptions* function parameter, but of course I might well be wrong.

Could you possibly have a look ? 
Thx,
Philippe

**Comment by mikejiang** [comment]
I recommend to do one thing at a time, that is let `read.flowSet` simply does parsing fcs, you can always annotate data afterward
for example
```
pData(raw_FS) = paste0("Donor_", seq(nDonors))
```

**Comment by phauchamps** [comment]
Hi Mike, thanks for your answer. 
I agree with you in that it is probably better practice to split reading and annotating. But then - sorry to come back to these things that might more look like details - wouldn't it be better to just remove this *descriptions* parameter in read.flowSet, that seems to do nothing, and adapt the help doc accordingly ? I must say it is sometimes confusing to newbies users like myself :-)

**Comment by mikejiang** [comment]
Actually, read.flowSet is no longer actively maintained because it loads entire fcs files into memory does not suitable for large data set, I recommend to switch to
```
flowWorkspace::load_cytoset_from_fcs()
```
which is more recent and efficient API

**Comment by phauchamps** [comment]
Hi Mike, thanks a lot for pointing me out to the new function. I will try it out. 
As a matter of fact I have noticed that *flowWorkspace::load_cytoset_from_fcs()*, also contains the *description* parameter, which does not seem to do anything neither :-)
