### ISSUE TITLE
How to subset some cells

### ISSUE THREAD

**Issue by Ivy-ops** [RGLab/flowCore#227]
Hi developer, 
I have a flowSet object, where I want to exclude some cells by the value of one channel. May I know how to achieve that? 
Thanks.

**Comment by mikejiang** [comment]
your question is a little too vague, please provide some concrete example or code snippet

**Comment by mikejiang** [comment]
also read docs and vignettes to understand what the package can do

**Comment by Ivy-ops** [comment]
Hi @mikejiang , 
Thanks for the quick response. 
Please see below example. In this demo data, I want to exclude 'Time' < 3. But I still want to keep the GvHD as flowSet format. Thanks!
<img width="660" alt="image" src="https://user-images.githubusercontent.com/61573164/157780834-f85bc93d-3f0f-436e-a0c0-59186efb0b76.png">

**Comment by mikejiang** [comment]
Try this
```
 fs=GvHD[1:2]
> range(fs[[1]],"data")[,"Time"]
[1]   1 755
> f=expressionFilter(Time>3)
> f
expression filter 'Time > 3' evaluating the expression:
Time > 3
> fs1=fsApply(fs,function(fr){Subset(fr,f)})
> range(fs1[[1]],"data")[,"Time"]
[1]   6 755
```

**Comment by Ivy-ops** [comment]
Thanks @mikejiang , It works well.
