### ISSUE TITLE
remove `curv1Filter`, `curv2Filter`, `norm2Filter` to drop more package dependencies

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowCore#23]
Given @raphg's impression on `flowCore` as a basic infrastructural library : 

> way too many dependencies

By simply moving the `density-based` gating algorithm to `flowStats`, we will immediately eliminate the direct reference to these `4` packages
- `rrcov` 
- `ks` 
- `grDevices`
- `MASS`

Potentially we might be able to further drop the following dependencies that are used by the above `4` packages:
`robustbase`, `pcaPP`, `stats4`, `mvtnorm`,`multicool`, `KernSmooth`  `misc3d` `rgl`

**Comment by mikejiang** [comment]
In light of https://support.bioconductor.org/p/121264/, we may consider to go ahead with the removal of `norm2Filter` (and to `flowStats`), which automatically drops `rrcov`(and its deps recursively) and `MASS` from the `imports` list.
![image](https://user-images.githubusercontent.com/1385649/58121276-e013b700-7bbb-11e9-98e1-087890c5433b.png)

Also `graph` and `graphics` aren't really needed anymore. `corpcor` can be potentially moved (or on suggest list) since its related API is rarely used (if used at all).

**Comment by jacobpwagner** [comment]
After 6ea2ca9c980bb913ba68ef081ca1ba4cfe689dfc, RGLab/flowStats@eba25fbc91fc7bf7494453d8ea2534ec25205a55, and e23acb273198898bc431eaec8de2080cfac1688e this should be done. The `flowSet` `spillover` methods for calculating a spillover matrix from a set of controls were moved to `flowStats` as a way to deal with their `norm2Filter` dependency.
