### ISSUE TITLE
Cannot install flowCore package

### ISSUE THREAD

**Issue by snowinwinterzj** [RGLab/flowCore#231]
**Describe the bug**
Package 'flowCore‘ is missing after install BioManager on a fresh reimaged computer

**To Reproduce**
1. Install R 4.2.0 using the default settings in windows installer
2. Install the latest Rstudio 2022.02.2+485
3. Run the following script to install flowCore package, 
if (!requireNamespace("BiocManager", quietly = TRUE))
  
  install.packages("BiocManager")
BiocManager::install("flowCore")

the outcomes are like this:

> if (!requireNamespace("BiocManager", quietly = TRUE))
+   install.packages("BiocManager")
> BiocManager::install("flowCore")
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: http://cran.rstudio.com/

Warning: unable to access index for repository https://bioconductor.org/packages/3.15/bioc/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/bioc/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/data/annotation/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/data/annotation/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/data/experiment/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/data/experiment/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/workflows/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/workflows/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/books/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/books/src/contrib/PACKAGES'
Bioconductor version 3.15 (BiocManager 1.30.17), R 4.2.0 (2022-04-22 ucrt)
Installing package(s) 'BiocVersion', 'flowCore'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/bioc/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/bioc/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/data/annotation/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/data/annotation/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/data/experiment/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/data/experiment/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/workflows/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/workflows/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/books/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/books/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/bioc/bin/windows/contrib/4.2:
  cannot open URL 'https://bioconductor.org/packages/3.15/bioc/bin/windows/contrib/4.2/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/data/annotation/bin/windows/contrib/4.2:
  cannot open URL 'https://bioconductor.org/packages/3.15/data/annotation/bin/windows/contrib/4.2/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/data/experiment/bin/windows/contrib/4.2:
  cannot open URL 'https://bioconductor.org/packages/3.15/data/experiment/bin/windows/contrib/4.2/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/workflows/bin/windows/contrib/4.2:
  cannot open URL 'https://bioconductor.org/packages/3.15/workflows/bin/windows/contrib/4.2/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/books/bin/windows/contrib/4.2:
  cannot open URL 'https://bioconductor.org/packages/3.15/books/bin/windows/contrib/4.2/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/bioc/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/bioc/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/data/annotation/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/data/annotation/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/data/experiment/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/data/experiment/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/workflows/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/workflows/src/contrib/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.15/books/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.15/books/src/contrib/PACKAGES'
Warning messages:
1: In file(con, "r") :
  URL 'https://bioconductor.org/config.yaml': status was 'SSL peer certificate or SSH remote key was not OK'
2: packages ‘BiocVersion’, ‘flowCore’ are not available for Bioconductor version '3.15'

Versions of these packages for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 

**Additional context**

The BaseBoard from System Summary is MEG Z590I UNIFY (MS-7D05), Manufacturer: Micro-Star International Co., Ltd

I don't have this issue when running the same code on another freshly re-imaged computer with a different BaseBoard: Z390M GAMING-CF, Manufacturer: Gigabyte Technology Co., Ltd.

This is the output of the Z390 computer
![image](https://user-images.githubusercontent.com/105237468/167471128-6dfd1f89-92db-4367-89c8-69ae6897b85f.png)

**Comment by SamGG** [comment]
Hi,
It sounds like the computer does not access to bioconductor.org. Either a temporary failure, either a firewall problem. If you click on any of the URL you reported (e.g. https://bioconductor.org/packages/3.15/bioc/src/contrib/PACKAGES), you web browser should show the contents of this URL. If not, this is an internet problem.
From my experience, I avoid updating packages while installing a new package.
Best.

**Comment by snowinwinterzj** [comment]
Hi SamGG

Thank you for your suggestions. I asked the IT to solve the internet problem. Now I can access the https://bioconductor.org/packages/3.15/bioc/src/contrib/PACKAGES with web browser, but I still have the same issues in installing flowCore in R.

**Comment by SamGG** [comment]
Hi,
This is not a flowCore error, just a problem of installation. Try to find someone who could help you solving this issue. The scrrenshot showing it is working is based on R4.0.2 and Bioc 3.12, not "fresh" R4.2 and Bioc 3.15. Comparison is not possible.

I don't understand why you got a message `'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details`. If the next proposal does not help, try to investigate this, which usually refer to an old version of BiocManager.

Do restart R. Try `chooseCRANmirror()` and select a mirror near to your location.
Then reinstall the 2 packages, without falling back to RStudio archive, which probably means an IT problem.
Install packages one by one, copying/pasting line one by one and stopping as soon you get an error message.
`install.packages("BiocManager")`
`BiocManager::install("flowCore")`

I don't have more time for you. Good luck.
