### ISSUE TITLE
Problem in installing flowCore package

### ISSUE THREAD

**Issue by raman91** [RGLab/flowCore#233]
Hi,

I am unable to install flowCore package and get an error : recipe for target 'RcppExports.o' failed
make: *** [RcppExports.o] Error 1

Do you have any suggestion to solve this issue?

Thank you

**Comment by gfinak** [comment]
What makes you suspect this is a bug in the flowCore code?

**Comment by raman91** [comment]
Hi, i don't think there is a bug. I am able to install 'flowCore' package in other servers but not able to install in one of the server that i want to use for analysis. I think it is due to 'cytolib' package that employs C++ infrastructure. Thanks

**Comment by gfinak** [comment]
If flowCore installs on other servers but not the one you're using for analysis perhaps you should contact your IT support?
Or at least help us help you by providing more context and information (error logs, system configuration info).
We don't read minds over here; if you want help, provide sufficient information for others to reproduce your error.

**Comment by raman91** [comment]
Ok, thank you for your polite reply. I will sort it out.
