### ISSUE TITLE
Question about transform

### ISSUE THREAD

**Issue by Chengwei94** [RGLab/flowCore#236]
Hi there, 

its more of a question rather than a bug. If I have 10 datasets, for the transform function does it transform each dataset separately or does it merge them before transforming? What is the preferred way to do it, merging before transforming or transforming individually?

**Comment by SamGG** [comment]
Hi,
What do you mean by dataset: a flowSet or a flowFrame?  How will you merge them?
Whatever, if you apply the same transformation to all the datasets, the order of operations does not matter.

**Comment by Chengwei94** [comment]
I'm talking about a flowset. Are the trasformation applied on each flowframe individually? I have seen some software that changes the flowframes to a dataframe(such as cycombine) and apply transform. I would assume that results in a different results since the range of values will change. Im quite new to the flow literature so what i was wondering what's the preferred way or they are actually equivilant

**Comment by SamGG** [comment]
If the flowSet consists in 10 FCS files (aka flowFrames), and the transformation is applied to the flowSet, all flowFrames will be transformed the same. A flowFrame consists in a matrix of measurements (each cell is a row) plus metadata. When extracting the measurements and put them into a data.frame, the metadata are lost, but the measurements and the ranges are unchanged. So it is possible to extract measurements them transform them as cyCombine and others. It's up to your data analysis pipeline.
We are currently discussing about how using the flowCore package. This discussion should take place into BioConductor forum.

**Comment by Chengwei94** [comment]
@SamGG  Thanks for the explanation! Any link to the discussion where I can read more about it?

**Comment by SamGG** [comment]
IMHO the most recent reference to get an overview of the state-of-the-art is
https://www.nature.com/articles/s41590-021-01006-z
