### ISSUE TITLE
unable to find an inherited method for function ‘compensate’ for signature ‘"flowFrame", "NULL"’

### ISSUE THREAD

**Issue by yueli8** [RGLab/flowCore#238]
Hello,

Thank you for developing so nice software.

I get something wrong with my data.

Thank you in advance for your great help!

Best,

Yue

```
fileName <- system.file("extdata", "s_Processed.fcs", package="FlowSOM")
ff <- flowCore::read.FCS(fileName)
comp <- flowCore::keyword(ff)[["SPILL"]]
ff <- flowWorkspace::compensate(ff, comp)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘compensate’ for signature ‘"flowFrame", "NULL"
```
[s_Processed.zip](https://github.com/RGLab/flowCore/files/10091039/s_Processed.zip)

**Comment by gfinak** [comment]
The flowWorkspace package is for working with FlowJo workspace files. You have a flowFrame representing a single fcs file. Your want to use the flowCore compensation function. 
Maybe a good place to start is to read some documentation.
cytoverse.org has lots of resources. The package vignettes are also good resources.
