### ISSUE TITLE
Does setting transformation=F in read.flowSet and read.FCS remove the transformation already done by FlowJo?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [RGLab/flowCore#245]
Hi there, 

Thank you for the package. 

I had FCS files that I obtained by converting the channel values exported from FlowJo (which meant they had already been transformed in FlowJo and will not need further transformation) into FCS files using `Spectre::write.files()` function as mentioned in issue #243. So, these FCS files should already been transformed. 

Would you mind confirming that by running `flowCore::read.flowSet(path=fcs.dir1, pattern="*.fcs", transformation = FALSE, truncate_max_range = FALSE)` setting `transformation=F` will not remove the transformation of the input FCS files because it only meant that flowCore will not perform additional transformation to the input FCS, and this `read.flowSet` function therefore will only convert the FCS files into a flowSet object?

Thank you for your help.

**Comment by SamGG** [comment]
Hi,
When ```transformation = TRUE```, read.FCS applies a linear transform; it does not remove any previous, it applies a new one on the data as they are. When ```transformation = TRUE```, no transformation is applied.
I don't know what it is exactly done in your FlowJo/Spectre pipeline. If you export FCS from FlowJo as FCS 2.0, I am quite confident about getting transformed intensities/channels. Apart from FCS 2.0, I would not bet a penny without having tested.
Best

**Comment by mikejiang** [comment]
This transformation refers to something different from the one performed in flowjo, it has to do with PnE/PnG keywords, I don't think you need to concern about this parameter, it has no interferes or impact to your data, as @SamGG pointed out
