### ISSUE TITLE
Problems installing Flowcore on Ubuntu 22.04

### ISSUE THREAD

**Issue by avdvloet** [RGLab/flowCore#247]
I am facing problems when installing the Flowcore package from Github:
Ubuntu 22.04
R 4.1.2
```
devtools::install_github("RGLab/flowCore")
```
The output is very long but here is the last bit (that I think is relevant);
```
/home/anvlo/R/x86_64-pc-linux-gnu-library/4.1/BH/include/boost/algorithm/string/iter_find.hpp:186:31:   required from ‘SequenceSequenceT& boost::algorithm::iter_split(SequenceSequenceT&, RangeT&&, FinderT) [with SequenceSequenceT = std::vector<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > >; RangeT = const std::__cxx11::basic_string<char>&; FinderT = boost::algorithm::detail::token_finderF<boost::algorithm::detail::is_any_ofF<char> >]’
/home/anvlo/R/x86_64-pc-linux-gnu-library/4.1/BH/include/boost/algorithm/string/split.hpp:158:50:   required from ‘SequenceSequenceT& boost::algorithm::split(SequenceSequenceT&, RangeT&&, PredicateT, boost::algorithm::token_compress_mode_type) [with SequenceSequenceT = std::vector<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > >; RangeT = const std::__cxx11::basic_string<char>&; PredicateT = boost::algorithm::detail::is_any_ofF<char>]’
/home/anvlo/R/x86_64-pc-linux-gnu-library/4.1/cytolib/include/cytolib/compensation.hpp:55:15:   required from here
/home/anvlo/R/x86_64-pc-linux-gnu-library/4.1/BH/include/boost/concept/usage.hpp:20:48: warning: ‘this’ pointer is null [-Wnonnull]
   20 |     ~usage_requirements() { ((Model*)0)->~Model(); }
      |                             ~~~~~~~~~~~~~~~~~~~^~
/home/anvlo/R/x86_64-pc-linux-gnu-library/4.1/BH/include/boost/concept/usage.hpp:37:7: note: in a call to non-static member function ‘boost::SinglePassRangeConcept<T>::~SinglePassRangeConcept() [with T = const boost::iterator_range<__gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> > >]’
   37 |       ~model()
      |       ^
/home/anvlo/R/x86_64-pc-linux-gnu-library/4.1/BH/include/boost/range/concepts.hpp:284:9: note: in expansion of macro ‘BOOST_CONCEPT_USAGE’
  284 |         BOOST_CONCEPT_USAGE(SinglePassRangeConcept)
      |         ^~~~~~~~~~~~~~~~~~~
make: *** [/usr/lib/R/etc/Makeconf:177: RcppExports.o] Error 1
ERROR: compilation failed for package ‘flowCore’
* removing ‘/home/anvlo/R/x86_64-pc-linux-gnu-library/4.1/flowCore’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpW7yvY7/file1d0543ab8ac4f/flowCore_2.9.1.tar.gz’ had non-zero exit status
```
I also tried downloading from Biocmanager before, but didn't work either. 

Thanks in advance!

**Comment by avdvloet** [comment]
```
remotes::install_github('RGLab/cytoinstaller', force=TRUE)
devtools::install_github("RGLab/RProtoBufLib")
devtools::install_github("RGLab/cytolib")
```
was successful if necessary

**Comment by klutzzzOOyyyq** [comment]
sorry, when I run"devtools::install_github("RGLab/cytolib")",there is still an error:
> devtools::install_github("RGLab/cytolib")
Downloading GitHub repo RGLab/cytolib@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                   
2: CRAN packages only                    
3: None                                  
4: Rhdf5lib (1.18.2   -> 1.20.0  ) [CRAN]
5: BH       (1.78.0-0 -> 1.81.0-1) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 3
✔  checking for file ‘/private/var/folders/st/7qpxbzfj6gl6tpcp2739bwnr0000gn/T/RtmpFXGz0O/remotes7a4760258550/RGLab-cytolib-24e6c07/DESCRIPTION’ ...
─  preparing ‘cytolib’:
✔  checking DESCRIPTION meta-information
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts (1.5s)
─  checking for empty or unneeded directories
─  building ‘cytolib_2.11.1.tar.gz’
   
* installing *source* package ‘cytolib’ ...
** using staged installation
checking for a sed that does not truncate output... /usr/bin/sed
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
configure: Parsing cytolib version info ...
configure: CYTOLIB_VERSION=2.11.1
configure: creating ./config.status
config.status: creating inst/include/cytolib/cytolibConfig.h
config.status: creating src/Makevars
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -DBOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF -DBOOST_FILESYSTEM_SINGLE_THREADED  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RProtoBufLib/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rhdf5lib/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c dummy.cpp -o dummy.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -DBOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF -DBOOST_FILESYSTEM_SINGLE_THREADED  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RProtoBufLib/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rhdf5lib/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c boost/libs/system/src/error_code.cpp -o boost/libs/system/src/error_code.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DROUT -I../inst/include -DBOOST_NO_AUTO_PTR -DBOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF -DBOOST_FILESYSTEM_SINGLE_THREADED  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/BH/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RProtoBufLib/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rhdf5lib/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c boost/libs/filesystem/src/codecvt_error_category.cpp -o boost/libs/filesystem/src/codecvt_error_category.o
boost/libs/filesystem/src/codecvt_error_category.cpp:18:10: fatal error: 'boost/filesystem/detail/path_traits.hpp' file not found
#include <boost/filesystem/detail/path_traits.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [boost/libs/filesystem/src/codecvt_error_category.o] Error 1
ERROR: compilation failed for package ‘cytolib’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/cytolib’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/cytolib’
Warning message:
In i.p(...) :
  ‘/var/folders/st/7qpxbzfj6gl6tpcp2739bwnr0000gn/T//RtmpFXGz0O/file7a473f537880/cytolib_2.11.1.tar.gz’ had non-zero exit status
