### ISSUE TITLE
flowSet: read.flowSet documentation about name column, file names are taken from sampleNames of the AnnotatedDataFrame

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#32]
Hi,

At the beginning I wanted to use/get short name/id in plotdensity plots. So I provided an annotatedDataFrame to read.flowSet to avoid the use of file name as identifier. The following statement in the documentation has mislead me (Rd format here).
```
First, if the argument \code{phenoData} is present and is of class
\code{\link[Biobase:class.AnnotatedDataFrame]{AnnotatedDataFrame}}, then the
file names are obtained from its sample names (i.e. column
\code{name}. The column is mandatory, and an error will be generated
if it is not there.
```
Apart from the missing ")", I thought that I should provide an ADF with a column called "name". But it is not the right interpretation, and the word "column" was badly used IMO. The following code is used in read.flowSet.
```
file.names <- sampleNames(phenoFrame)
files <- file.path(path, file.names)
```
This means that file names are extracted from the sampleNames of the ADF. If sampleNames is not overloaded, this turns to be the following code from Biobase package.
```
setMethod("sampleNames", "AnnotatedDataFrame",
    function(object) row.names(object@data))
```
So file names are extracted from row names.
I feel the doc should make it clear, unless I am wrong.

Then I set up an ADF with file names as row names. The read is OK, but the show() failed, because my varMetaData was not filled, ie all description are NA. I think the code of the show method should add a na.rm argument in if(any()), what avoids "missing value where TRUE/FALSE needed".

I tried to understand the many places in the code where the $name may be used, but this brought to my own ignorance. There seems to be dependencies to the special column "name" of the flowset phenoData. If this is right, this should also be warned. It should be also told that a name column is filled with file names if this column does not exist. What happens when the name column is supplied by the user and does contains file names, it is too complicated to me.

I didn't catch the meaning of the final code of read.flowSet, after the main lapply(). I was lost about what is the meaning/use of names(flowSet) and then of GUID and identifier. I don't understand if names are mandatory (it seems not). Hope you still have all this knowledge.Best.

Best.

**Comment by mikejiang** [comment]
* I've updated the doc [here](https://github.com/RGLab/flowCore/blob/master/man/read.flowSet.Rd#L80-L81) 

* `show` method is [fixed](https://github.com/RGLab/flowCore/blob/master/R/show-methods.R#L39-L43) so that it won't throw the error when `varMedaData` is empty.
* Validity check for `name` column is now added to [phenoData<-](https://github.com/RGLab/flowCore/blob/master/R/flowSet-accessors.R#L135-L137) to prevent the incomplete `phenoData` to be assigned to `flowSet` (because it is required for visualization by `flowViz`)

* Regarding to `names()` method , I don't think it is defined for `flowSet` class.

* The simple way to change `sample names` to a short format is through `sampleNames<-` replacement method after you read data through `read.flowSet`, that way you don't have to mess with `AnnotatedDataFrame` object.

**Comment by SamGG** [comment]
* Nice job!
* Concerning the doc, ```Also column \code{name} is mandatory, and an error will be generated
if it is not there.``` is not exactly true. My current ADF has no ```name``` column. The current read.flowSet creates it and fills it with the filename (ie rownames) if this column does not exists. If the column already exists, the code does not change it. I like this current behavior although it is not documented. I don't know what happens if the name column is filled with dummy things (ie how flowViz will use it).
* ```names()``` seems to return nothing (neither in the example, neither in my code). Nevertheless the read.flowSet code tries to set it up.
```
    if(!missing(name.keyword)){
        ...
        names(flowSet) <- sapply(flowSet,keyword,name.keyword)
    }else{
        names(flowSet) <- make.unique(file.names)
    }
    flowSet <- as(flowSet,"flowSet")
```
* Thanks for pointing the tip. I came to the same conclusion: let the code of ```sampleNames``` do the job including sanity checks.

**Comment by mikejiang** [comment]
At that point, `flowSet` is still a `list`. so `names` method is preparing the list for coercing `as(flowSet,"flowSet")`

**Comment by mikejiang** [comment]
Ok. I changed the behavior of `phenoData<-` so that `name` will be added if it is missing (which is consistent with `read.flowSet` constructor). Also it must be consistent with `rownames` (i.e. sampleNames of `phenoData`).

**Comment by SamGG** [comment]
Perfect. To summarize, two files of a flowSet can't have the same name in two different folders now. May be will it be too strict, but it makes sense. I feel you should state this point in the doc.
```
Also column \code{name} will be generated based on ```sampleNames``` if it is not there. This column is required by plotViz functions. 
```

**Comment by mikejiang** [comment]
Not true. [Here](https://github.com/RGLab/flowCore/blob/master/R/IO.R#L858) appends sequence numbers for duplicated filenames.

**Comment by SamGG** [comment]
* You're right. But the real file location is lost if it has not been kept in another column. ```make.unique``` add a sequence and ```basename``` removes the relative path (as in my case).
* Nevertheless my doc proposal is still valid :-)

**Comment by mikejiang** [comment]
Maybe we should allow `name` column to be different from `rownames` in `pData` because `name` was dedicated for `plotting` and it makes no sense to keep it if it is mandated to be the same as `rownames`.
