### ISSUE TITLE
add validity check of 'w' value estimated by 'estimateLogicle'

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowCore#34]
This is the error thrown during the `transformation` with the `logicle function` estimated by `estimateLogicle`
```r
trans <- estimateLogicle(fr, channels = chnls)
> fr_trans <- transform(fr, trans)
Error in y@f(x[, y@input]) : 
  Logicle Exception: IllegalParameter: W is not positive 
```
`w` is  calculated by
```r
w=(m-log10(t/abs(r)))/2
```
in which,
* `t` is `max positive value` 
* `r` is most negative value to be included (adjustable through quantile factor `q`) 
* `m` is full width of decades

We should at least throw the error early at `estimateLogicle` stage before it makes way to `transform` .

**Comment by mikejiang** [comment]
Here is the fixed version:
```r
> trans <- estimateLogicle(fr, channels = chnls)
Error in .lgclTrans(x, p, t = rng[, p][2], ...) : 
  w is negative!Try to increase 'm'
```
Then increase `m` from default `4.5` to `4.6`
```r
 trans <- estimateLogicle(fr, channels = chnls, m = 4.6)
 fr_trans <- transform(fr, trans)
densityplot(~., fr_trans)
```
![image](https://cloud.githubusercontent.com/assets/1385649/6878411/cd84bb60-d49a-11e4-8d22-6f0fea9657c1.png)

**Comment by gfinak** [comment]
I think for CyTOF data this could be corrected by setting a different
quantile value for r, since the distribution is quite different from flow.

Greg Finak

**Comment by mikejiang** [comment]
For this particular data, `r` value is not significant enough to contribute to `w`.
The data range is:
```r
range(dat)
[1]    -1.15396 42855.91016
``` 
Top scale `t = 42855`, which is in decade `log10(42855) = 4.63`, without increasing `m = 4.5`, even taking the extreme negative value won't make it positive.
```r
r <- -1.15396
m- log10(t/abs(r))
[1] -0.06981074

```

**Comment by mikejiang** [comment]
Add more options to `estimateLogicle`:
* `t` can be overwritten by the `customized` value instead of always calculating from `instrument range`
* add `type` argument (`c("instrument", "data")`) which adds the option to use actual `data` range to determine `t` and `m` values (instead of default `4.5`)

e.g. here is the default behavior(`m` is hardcoded `4.5` and `t` comes from `instrument range`)
```r
> trans <- estimateLogicle(fr, channels = chnl)
> sapply(c("t","m", "a", "w"), function(param)as.numeric(format(as.vector(environment(trans@transforms[[chnl]]@f)[[param]]), digits = 2)))
     t         m         a         w 
261590.00      4.50      0.00      0.47 
```
here is customized version (`m` and `t` are manually supplied)
```r
> trans <- estimateLogicle(fr, channels = chnl, m = 5.5, t = 1e6)
> sapply(c("t","m", "a", "w"), function(param)as.numeric(format(as.vector(environment(trans@transforms[[chnl]]@f)[[param]]), digits = 2)))
      t       m       a       w 
1.0e+06 5.5e+00 0.0e+00 6.8e-01 
```
And here is the more `data-driven` way (`m` and `t` are derived from `data`)
```r
> trans <- estimateLogicle(fr, channels = chnl, type = "data")
> sapply(c("t","m", "a", "w"), function(param)as.numeric(format(as.vector(environment(trans@transforms[[chnl]]@f)[[param]]), digits = 2)))
       t        m        a        w 
92322.00     5.00     0.00     0.93 
```
