### ISSUE TITLE
serious bug in flowCore coerce method that affects read.flowSet

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowCore#35]
Here is the simple fact of using `base::list2env` to convert a `list` to a `hashed environment`:
* elements stored in new `environment` get shuffled

```r
> myList <- as.list(c(1:10))
> names(myList) <- rev(LETTERS[1:10])
> names(myList)
 [1] "J" "I" "H" "G" "F" "E" "D" "C" "B" "A"
> myEnv <- list2env(myList, new.env(hash=T, parent=emptyenv()))
> ls(myEnv)
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J"
```
And `ls`  (by default) will sort them in `alphabet` order, which could be completely different from the original order if they are **not** already sorted.

Then here comes the **nasty** bug in `cerce` method that is used by `read.flowSet` to convert a list of `flowFrame` objects (generated by `read.FCS`) to `flowSet`
```r
setAs(from="list", to="flowSet", def=function(from)
  {
      if(is.null(names(from)))
          names(from) <- paste("V", seq(1, length(from)), sep="")
      orig.sampleNames <- names(from)
      res <- as(list2env(from, new.env(hash=T, parent=emptyenv())), "flowSet")
      sampleNames(res) <- orig.sampleNames
      res
  })
```
Apparently the assignment of the `orig.sampleNames` will cause the actual samples to be renamed **incorrectly** if it is not already alphabetic ordered.

This seems to be there for quite long time and did not pop up as an issue for several reasons:
* `read.ncdfFlowSet` has a separate logic and thus does not affected by this bug. and `cdf` has been mostly used in our real data analysis
* `read.flowSet` is usually used in a scenario where all `FCS` files are from the same folder, which results in the `alphabet` sorting by the `list.files` API
* Only the sample name changing won't necessarily cause the trouble in down-stream analysis if the `phenodata` was extracted from `workspace` or `FCS header`. (i.e. `sampleName` just serves as an ID, thus even if initially tampered by mistake,it is not going to be read by human)

However, it does bite @ptvan this time, because
* I recommended him to use `flowSet` for quick exploring due to the frequent `transformation` going on (sorry, @ptvan!)
* files do come from two folders and they are simply concatenated but not sorted
* the `phenoData` was indeed extracted from sample names (which unfortunately is wrong this time)
 
The fix is easy though, simply remove the assignment (not sure why it was there in the first place)

**Comment by jan-glx** [comment]
That one did let me go nuts. Thanks for fixing! Don't you think that this is worth a new version to be pushed to bioconductor? Thanks again!

**Comment by mikejiang** [comment]
just pushed to bioc release `1.34.2`
