### ISSUE TITLE
read.FCS, yet another error concerning splitting character. Why not allowing alternate character?

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#38]
Hi guys,
I faced another error when opening a freshly flowcCore saved FCS file: write.FCS(read.FCS("somefile.fcs"), "another.fcs")
In fact, the original file (ie somefile.fcs contains the gating strategy as "All Events\P1\P2\P3\Lympho vivant CD45\NK"). Of course, those "\" misleads the parser when reading the saved file (ie another.fcs). I am going to escape or replace such a character when it is included in the value of a parameter. I am not sure this already done yet in flowCore.
Nevertheless, it is not the first time I am facing such a problem. Googling a little bit, I think such an error has already occurred many times. So, my point is: a) why using anti-slash, b) why is it hard-coded? c) why not allowing another separator. Diva software has chosen 0x0C, and I never saw this character within a parameter's value. Let me know.
Best reagrds.

**Comment by SamGG** [comment]
Thanks for allowing a user defined delimiter. Here are 4 humble comments. Briefly I think that the current escaping is not the solution. 0x0C is certainly a challenging delimiter.
Cheers.

A/ I think the following code 
```
    d <- description(x)
	##make sure there is no empty value for each keyword in order to conform to FCS3.0
#	browser()
	
	d <- lapply(d, function(y){
				if(length(y)==0)
					return(" ")
				else
				{
					#make sure spillover matrix doesn't get converted to vector
					if(is.matrix(y))
						return (y)   
					else{
					  
					  y <- sub("^$"," ",y)
					  delimiter <- paste0("\\", delimiter) #escape it in case of special character
            #escape delimiter character by doubling it
            double_delimiter <- paste0(delimiter, delimiter)
					  return(gsub(delimiter, double_delimiter, y))
            
					}
						
				}
					 
						
			})

```
could be simplified (removing else because of return) as
```
    d <- description(x)
#	browser()
	
	d <- lapply(d, function(y){
				## no empty value for each keyword in order to conform to FCS3.0
				if(length(y)==0) return(" ")
				#make sure spillover matrix doesn't get converted to vector
				if(is.matrix(y)) return (y)   
				## add your comment
				y <- sub("^$"," ",y)  # what difference with the previous length(y) test?
				## add your comment
				delimiter <- paste0("\\", delimiter) #escape it in case of special character
            #escape delimiter character by doubling it
            double_delimiter <- paste0(delimiter, delimiter)
				return(gsub(delimiter, double_delimiter, y))
			})

```

B/ I am not sure that escaping will be successful. I added by hand (Linux/bless) a \ before the \ of "All events\P1...". read.FCS failed, because of emptyValue. Changing the logical value of emptyValue to TRUE or FALSE does not help. IMHO, the delimiter has to be something else than / or \ and I am now convinced that 0x0C is a matured choice.

C/ If escaping may be useful, I don't understand the escaping code: why escaping the delimiter that is searched? anti-slash delimiter, ie "\\" as printed by R, will become "\\\\" and will not be found in "P1\\P2" (as printed by R). IMHO, may be R misleads you when printing a single \ as \\ because R needs to escape the \. If we are looking for a single \ that is unfortunately printed as \\, we need to specify "\\" as pattern and "\\\\" as replacement.

D/ I think gsub must specify ```fixed = TRUE```
```
> gsub("\\", "\\\\", "P1\\P2", fixed = TRUE)
[1] "P1\\\\P2"
> gsub("\\", "\\\\", "P1\\P2")
Error in gsub("\\", "\\\\", "P1\\P2") : 
  invalid regular expression '\', reason 'Trailing backslash'
```

**Comment by SamGG** [comment]
Here is my current patch. Run this code after having loading flowCore library. This code overloads the write.FCS function. HTH.

```
replaceDelimiter = function(ff, pattern = "\\", replacement = "/") {
  # Find string keywords that contain the pattern, ie the delimiter to avoid
  matched = which(sapply(keyword(ff), function(k) {
    if (is.character(k)) length(grep(pattern, k, fixed = TRUE)) else -1 }) > 0)
  # Replace
  if (length(matched) > 0)
    keyword(ff)[matched] = gsub(pattern, replacement, keyword(ff)[matched], fixed = TRUE)
  keyword(ff)
}

write.FCS = function (x, filename, what = "numeric") {
  keyword(x) = replaceDelimiter(x)
  flowCore::write.FCS(x, filename, what)
}
```

**Comment by mikejiang** [comment]
The following example shows the existing code works. 
```r
> data(GvHD)
>     fr <- GvHD[[1]]
>     description(fr)[["pop"]] <- "All events\\P1\\P2"
>     tmp <- tempfile()
>     write.FCS(fr,tmp)
[1] "/tmp/RtmpqXVqsj/file4f0f4ae8dff0"
Warning message:
In write.FCS(fr, tmp) :
  'write.FCS' is not fully tested and should be considered as experimental.
>     fr1 <- read.FCS(tmp, emptyValue = F)
>     description(fr1)[["pop"]]
[1] "All events\\\\P1\\\\P2"
```

**Comment by SamGG** [comment]
Sorry, I don't have time to setup a devel environment to do further tests, as I have already spent enough time locating the problem and solving it in the release version of BioConductor. My tests and feedbacks concern only the current release. As mentioned, I proposed a *patch* that solves the issue in the current release, at least in my case.
I am not sure that the current code is handling escaping correctly: a) what happens if ```description(fr)[["pop"]] <- "All events\\\\P1\\\\P2" ``` and you replay the write/read sequence? b) although the read keyword reflects the escaping process, it is not the original string. In order to keep backward compatibility, I think de-escaping should be done when reading (if this has been stated in the FCS 3.1). But this raises another issue: how the parser knows that characters has been escaped? This sounds like the egg and the chicken.
```
            #escape delimiter character by doubling it
            double_delimiter <- paste0(delimiter, delimiter)
```
A final word about escaping special character: not all delimiters are special characters.
```
	  delimiter <- paste0("\\", delimiter) #escape it in case of special character
```
Hope I helped improving the code.

**Comment by mikejiang** [comment]
* It is not required to `de-escaped` delimiter according to `FCS3.1` standard so I will leave it as it is at the moment 
* Each double-delimiter will be treated as escaped delimiter. because
  * The delimiter is the first character of the primary TEXT segment a
  * empty value is actually not allowed (so `emptyValue` should be set to `FALSE`). 
* I've propagated these changes to release version 1.34.7, you should be able to see it soon
* `write.FCS` it is not a frequently used API but has been brought up as an issue by quite a few users. so I appreciated you helped and pushed for these fixes and enhancements.

**Comment by SamGG** [comment]
Thanks for your work and the discussion. Hope FCS3.1 will be self-consistent.
```write.FCS``` is one of my work-horse.
Best.

**Comment by SamGG** [comment]
Thanks for correcting this.
