### ISSUE TITLE
scale_x_logicle produces "Logicle Exception: DidNotConverge"

### ISSUE THREAD

**Issue by malcook** [RGLab/flowCore#41]
I am trying to use  scale_x_logicle 
I am trying to use  scale_y_logicle 

with ggcyto and getting errors:

```
+ . + Error in scale$trans$trans(x) : 
  Logicle Exception: DidNotConverge: scale() didn't converge 
```

Some few of my values are negative, but this is not a problem, is it?

Are there any better diagnostics available?

**Comment by mikejiang** [comment]
`ggcyto::scale_x_logicle` uses some default  parameter settings (i.e. `w,t,m,a`) of `flowCore::logicleTransform` , which may not necessarily be optimal (or even valid) for any data values.
One possible solution is to use `estimateLogicle` to calculate these parameter values and pass them explicitly to to `scale_x_logicle` when using `ggcyto`.
Or try `scale_x_flowJo_biexp` instead, which may be more robust.
