### ISSUE TITLE
spillover,flowFrame should (a) return a matrix, not a list (b) does not take a 2nd argument

### ISSUE THREAD

**Issue by malcook** [RGLab/flowCore#42]
Hi, the documentation for spillover in flowFrame-class reads:
```
     spillover Extract spillover matrix from description slot if
          present.

          _Usage:_

          ‘ spillover(flowFrame, matrix)’
```
However, 

(a) as implemented, it does not return a matrix, but rather a list with typically one element.  I think it should return just the single matrix, and raise an error if both ("spillover", "SPILL") have non-NULL values.

(b) the usage shows it takes a 2nd argument.  This is incorrect.

Thanks

**Comment by mikejiang** [comment]
I've updated/corrected the doc to reflect the output format instead of changing the API ( in order not to break the existing scripts that used it).  Thanks for pointing it out. the fix is pushed to both bioc devel and release.

**Comment by SamGG** [comment]
I use the following function in order to get the compensation __matrix__ from a flowFrame.
HTH
```r
getSpillover = function(ff, kwd = c("$SPILLOVER", "$SPILL", "SPILL")) {
  if (is.na(kwd) || is.null(kwd))
    stop("getSpillover: please give a keyword to localize the compensation matrix")
  res.is.null = sapply(keyword(ff, kwd), is.null)
  if (all(res.is.null))
    stop("getSpillover: no compensation keyword found")
  res = min(which(!res.is.null))  # take the first match
  kwd = kwd[res]
  m = as.matrix(keyword(ff, kwd)[[1]])
  col.m = colnames(m)
  col.ff = colnames(ff)
  for (patt in c("^FSC", "^SSC", "^Time", "^Event")) {
    id = grep(patt, col.ff, perl = TRUE)
    if (length(id)) col.ff = col.ff[-id]
  }
  theDiff = setdiff(col.ff, col.m)
  if (length(theDiff))
    stop(sprintf("Some columns are not in compensation matrix %s\n",
                 paste(theDiff)))
  m[col.m %in% col.ff, col.ff]
}
```
