### ISSUE TITLE
splitting: various improvements

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#43]
Hi,
- splitting a flowframe using a factor is OK but splitting using numeric or character calls it but don't pass any option, such as flowSet logical argument (... is also ignored). As a workaround, I transformed integer to factor in order to get a flowSet as output by use of flowSet.

``` R
setMethod("split",
          signature=signature(x="flowFrame",
                              f="numeric"),
          definition=function(x, f, drop=FALSE, prefix=NULL,
                              flowSet=FALSE, ...)
          split(x, factor(f)))

setMethod("split",
          signature=signature(x="flowFrame",
                              f="character"),
          definition=function(x, f, drop=FALSE, prefix=NULL,
                              flowSet=FALSE, ...)
          split(x, factor(f)))

```
- Check also the code concerning flowset, I didn't.
- splitting a ff using a factor does an extra/debug print and i argument in the paste function should be replaced by nn IMHO.

``` R
          nn  <- levels(f)
          out <- structure(lapply(nn,function(i) x[f==i,]),
                           names=if(is.null(prefix)) nn else
                           paste(prefix, i, sep=""))
          if(flowSet) {
              print(data.frame(name=nn, split=seq_along(nn), row.names=nn))
```
- Also correct the documentation stating "the optional logical argument \code{filterSet} can be used to return a \code{\linkS4class{flowSet}} instead". The argument is called flowSet, not filterSet.

Best.

**Comment by gfinak** [comment]
@SamGG 
Internal audit of open issues.. seems we missed this one.
Is this still relevant?
Best
Greg

**Comment by SamGG** [comment]
Hi,
Points 1, 2 and 3 have been applied in the current version of flowCore.
Point 4 is a documentation detail, but please verify it (split-methods.R around L66)
I proposed a PR.
Best.
