### ISSUE TITLE
Don't know how to deal with $BYTEORD 3,4,1,2

### ISSUE THREAD

**Issue by jspidlen** [RGLab/flowCore#47]
Hi guys,
this issue came up as I was processing ~30,000 FCS files in ~300 FlowRepository datasets:
Error in readFCSdata(con, offsets, txt, transformation, which.lines, scale, : Don't know how to deal with $BYTEORD 3,4,1,2. 
Any of the 60 files in dataset FR-FCM-ZZY9 (http://flowrepository.org/id/FR-FCM-ZZY9) give this error. All these files can be downloaded from 
http://flowrepository.org/experiments/41/download_ziped_files or, if you just want a single file to test on, you can grab this one: http://flowrepository.org/experiments/41/fcs_files/1873/download

This is essentially a mixed endian encoding. I am not sure how prevalent these types of files are, but I was thinking that it may be possible to support this since you have the splitInt option where you combine 2 16bit uint anyway... 

Thanks,
Josef

--
Josef Spidlen, Ph.D. 
Staff Scientist, Terry Fox Laboratory, BC Cancer Agency 
675 West 10th Avenue, Vancouver, BC, V5Z1L3, Canada 
Tel. +1 604-675-8000, ex. 7755

**Comment by mikejiang** [comment]
@jspidlen , let me know if the data looks right to you with the latest fix.

**Comment by jspidlen** [comment]
Thanks Mike,
the data looks fine to me.
