### ISSUE TITLE
Error in description[[spID]]: subscript out of bounds

### ISSUE THREAD

**Issue by jspidlen** [RGLab/flowCore#48]
Hi guys, files
http://flowrepository.org/experiments/4/fcs_files/329/download
http://flowrepository.org/experiments/4/fcs_files/333/download
give the 
Error in description[[spID]]: subscript out of bounds error. 
Again, this issue came up as I was processing ~30,000 FCS files in ~300 FlowRepository datasets, so not a big deal, but wanted to report it in case you had some time to look into it. I am guessing there may be something slightly weird with these FCS files, so not necessarily a priority to resolve.

Thanks,
Josef

**Comment by mikejiang** [comment]
fixed by 6588a567b66c91580019d18afb33006284ccdf11  see #62 for details
