### ISSUE TITLE
Error: basic_string::substr

### ISSUE THREAD

**Issue by jspidlen** [RGLab/flowCore#49]
Hi guys, file
http://flowrepository.org/experiments/142/fcs_files/11651/download
gives the 
Error: basic_string::substr
This issue also came up as I was processing ~30,000 FCS files in ~300 FlowRepository datasets, so not a big deal, but wanted to report it in case you had some time to look into it. I am guessing there may be something slightly weird with the file, so not necessarily a priority to look into.

Thanks,
Josef

**Comment by mikejiang** [comment]
It is a malformed `FCS` file.
