### ISSUE TITLE
Standardize option naming 

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#55]
The new option "ignore.text.offset" leads me to revisit the option naming convention. I think truncate_max_range should be deprecated in favor to truncate.max.range. In spillover stain_match should also be deprecated. Although some options are camelCased (such as emptyValue), camelCase is more usual in flowCore than underscore. IMHO, underscore should be avoid because two naming pattern are sufficient. Thanks for having chosen dots in the new option.
Best.

**Comment by gfinak** [comment]
I tend to agree here, we should go through and standardize some of these things. Perhaps a new branch dedicated to that and aim for the next release.

**Comment by gfinak** [comment]
Labeling this to address for a future date and closing for now.
