### ISSUE TITLE
Loading compressed fcs files?

### ISSUE THREAD

**Issue by smsaladi** [RGLab/flowCore#57]
Is it possible to load compressed fcs files (gzip or bzip2) without uncompressing them in the filesystem first? If not, I would like to suggest this as a feature to add since flow experiments can very easily get quite big and result in a great deal of data.

**Comment by gfinak** [comment]
No it's not.Your "great deal of data" will have an even bigger problem residing in memory. If you use ncdfFlow, which keeps your data on disk until you need to access it, on-the-fly compression decreases performance (we have benchmarked it). So it's not something we plan to support at the moment. Disk space is cheap, compression is best for archival purposes.
