### ISSUE TITLE
bounding transformation slows down *Gml2 transforming

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowCore#58]
This [one liner](https://github.com/RGLab/flowCore/blob/trunk/R/eval-methods.R#L212-L216) literally eats `95%` CPU time based on my profiling.

Since we are doing `gate extension`, these `eval` methods for `Gml2` transformation class should skip this `data truncation` optionally ( or at least when `boundMin` and `boundMax` are `-Inf` and `Inf`) to avoid the expensive `sapply` and `min/max` calls.

Before I make changes, @jspidlen, let me know if it sounds reasonable to you.

**Comment by jspidlen** [comment]
I don't know the exact details of how you are implementing this, but yes,
it does sound reasonable. Thanks for doing it; cheers, Josef
