### ISSUE TITLE
FILENAME is added automatically in read.FCS and wrongly encoded in write.FCS

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#63]
Hi,
I am running a Shiny application that output a FCS file after some transformation. While there is no FILENAME keyword in the original FCS file, the read.FCS function adds one. While there is nothing wrong with this side effect, it's become a problem because the FILENAME value is something like `C:\Users\samgg\AppData\Local\Temp\RtmpAfNq6F/f1de569b39c6af3fce68efb4/0` (I don't know why there is a mix of `/` and `\`). The fact is that when write.FCS takes place the FILENAME keyword is written as `C:\\temp\\...` on the disk. The `\\` is understand as an empty keyword when reading this new created file.
Currently, I remove the FILENAME keyword after read.FCS, and it does not appear again when write.FCS takes place later on.

``` r
  fcsInput <- reactive({
    if (is.null(input$fcsFile)) return(NULL)
    isFCS <- isFCSfile(input$fcsFile$datapath)
    if (isFCS == FALSE) return(NULL)
    # TODO: return an error if file is not a valid FCS file
    ff = read.FCS(input$fcsFile$datapath, transformation = FALSE)
    kwd = description(ff)
    if (any(names(kwd) == "FILENAME"))
      ff@description = kwd[names(kwd) != "FILENAME"]
    ff
  })
```

I don't ask for any correction. I just want to mention it in case it could help others.
Best.

**Comment by SamGG** [comment]
Just for info.
https://github.com/RGLab/flowCore/blob/417ed6572f5b18008d64e99421c29fbb4c9c44fd/R/IO.R#L150

**Comment by mikejiang** [comment]
Looks like your FCS uses `\` as delimiter, which then makes your `file path` illegal. Here is from the `FCS3.1 standard`
>3.2.7
>The delimiter may not be the first character in a keyword or keyword value. If the delimiter
appears in a keyword or keyword value, it must be immediately followed by a second delimiter.
For example, "$SYS/RSX-11//M/" shows a value of RSX-11/M for the keyword $SYS. Since null
(zero length) keywords or keyword values are not permitted, two consecutive delimiters can never
occur between a value and a keyword. 

 We've also discussed about this https://github.com/RGLab/flowCore/issues/38#issuecomment-120086332

**Comment by SamGG** [comment]
Hi Mike,
The previous discussion was about a keyword that I added or is already present in the header. Currently, my FCS does not have any FILENAME entry. The FILENAME keyword is clearly added by the read.FCS function that takes the filename argument, ie the name of the FCS file to read. In my case (shiny interface), I don't master the filename given by the Browse button. It turns to get a double anti-slash. This is correct for R/Windows. As I am writing, I think I should replace those ```\\``` by ```/``` which the most consistent across all R platforms. ```\\``` is correctly handled by R/Windows. But if I don't carry out such a replacement or a FILENAME keyword removal or a delimiter change in write.FCS, writing the untouched flowframe will lead to an incorrect FCS file. I don't ask for any change, I just want to give you a feedback and make a note if other users come to the same problem. As we already discussed, this will push me to the use of ```|```, ```$``` or 0x0C as a default delimiter in order to avoid any escaping or de-escaping trouble.
Best.

**Comment by mikejiang** [comment]
Well, it is expected behavior to escape the `delimiter` that is present in any keyword content with `double delimiter`.  All you need to do is to explicitly notify the parser about it (by setting `emptyValue = FALSE`)  when you re-read this fcs

**Comment by SamGG** [comment]
Well, I understand that, but I think the current specifications are not side-effect free. I am really thinking about switching to another delimiter. Because I think it will solve some (if not all) IO problems with delimiter on Windows.

If you have time, try the following "side effect":
* read any FCS file specifying the path using ```.\\a_fcs_file.fcs```
* observe the FILENAME field; whatever it may contain, it is overwritten by read.FCS
* write this flowframe asis
* you probably cannot read it, because it contains unescaped ```\\```

![2016-08-09_014737](https://cloud.githubusercontent.com/assets/3333348/17500169/58d2dee6-5dd3-11e6-965c-8fe02f6e5041.png)

Best.
flowCore_1.36.9

**Comment by SamGG** [comment]
It seems that you decided to change the default delimiter.
Thanks.

https://github.com/RGLab/flowCore/commit/e57d42948c759313554488aca144f8e77eeb2e3c#diff-a16861552d761db731e4c78a1c067091
