### ISSUE TITLE
Stable relesase 1.40.1 is not passing check on malbec1

### ISSUE THREAD

**Issue by jirihon** [RGLab/flowCore#67]
Failed test `testthat.R` is preventing latest stable flowCore 1.40.1 to be built. Therefore, a recent critical bugfix #66 can't be propagated to users.

**Comment by mikejiang** [comment]
I am aware of that and have written to BioC for the further troubleshooting since I myself couldn't reproduce the test error reported by BioC

**Comment by jirihon** [comment]
Please consider, if it would be better to temporarily exclude the failing test before you figure out the reason. In the present situation, Bioconductor users can't install flowCore and also any other package that depends on flowCore, if they have BH package from CRAN updated.

**Comment by mikejiang** [comment]
There it failed the unit test changes are the same issue will occur for the end users. So I'd rather get to the bottom of it instead of bypassing the failed tests.

**Comment by gfinak** [comment]
Can this be closed?
