### ISSUE TITLE
What about adding a function to control read/write parameters globally?

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowCore#68]
Hi,
Some previous issues here and other depending packages (https://github.com/nolanlab/spade/issues/134) could be solved by tuning read/write parameters. The emptyValue is an interesting parameter of read.FCS typically. Tuning such parameter without rewriting the source code of the package sounds interesting to me. I think about a function that set global read/write parameters and thus modifies the behaviour of the read/write functions. Of course the flowCore functions need to take this into account. Conflicts between those new global parameters and those explicitly passed as argument should be detected and solved, or may be not, but I have no experience.
Best.
```r
# Here emptyValue is set TRUE globally
flowCoreOptions(emptyValue = TRUE)  # the name of the function is up to you
# Now the read.FCS acts as if emptyValue = TRUE is passed as an argument
ff = read.FCS("somefile.fcs")
# Options could be managed in the same way as graphical parameters (par() function)
fcOptions = flowCoreOptions()  # backup
# do some changes and cytometry processing here
flowCoreOptions(fcOptions)  # restore
```

**Comment by gfinak** [comment]
@SamGG 
I'm going to suggest if some of these older unaddressed are important, that the issue author (you in this case) make changes and submit a PR, with tests, use cases etc.
If you're willing to do so, note it here, otherwise you can close the issue.

**Comment by SamGG** [comment]
@gfinak 
I am running out of time currently. I wanted these changes in order to overwrite some defaults of flowCore such as the FCS delimiter when I was working with SPADE. If you agree, I will reopen this issue later. Thanks.

**Comment by gfinak** [comment]
@SamGG If it's okay with you, I will add you as a contributor to the flowCore package DESCRIPTION. Could you send me your email?
