### ISSUE TITLE
Mean? Arithmetic or Geometric

### ISSUE THREAD

**Issue by mcrone** [RGLab/flowCore#69]
Is the mean provided within FlowCore the Arithmetic or Geometric mean? If it is the arithmetic mean is there a way to easily calculate the geometric mean?

I'm currently just using fsApply:
`meansarray <- fsApply(selcells,each_col,mean)`

**Comment by gfinak** [comment]
The mean function is base R and takes the arithmetic mean.

That said, if your input data is log transformed, your code will take the geometric mean of the raw fluorescence, and the arithmetic mean of the log transformed fluorescence.

If you want to take the geometric mean of the log transformed fluorescence (but I don’t think you should do that), you’d log transform again, take the mean, and exponentiate.
