### ISSUE TITLE
Write little-endian FCS files

### ISSUE THREAD

**Issue by zbjornson** [RGLab/flowCore#76]
It looks like flowCore is [hard-coded to export big-endian files](https://github.com/RGLab/flowCore/blob/trunk/R/IO.R#L1233). The vast majority of hardware is little-endian, and it's faster for many importers to read their native byte ordering. You might want to consider changing it to write little-endian, with or without an `endian = "little"` argument.

**Comment by SamGG** [comment]
I am also in favour.

**Comment by mikejiang** [comment]
The default is `big` to keep it backward compatibile

**Comment by zbjornson** [comment]
Just curious, backward compatible with what? Are there readers out there that can't read little-endian files? (If so, they're not spec-compliant.)

**Comment by gfinak** [comment]
Backward compatible with any existing R code that uses write.FCS.

**Comment by mikejiang** [comment]
Comparing the risk of breaking the user's legacy code(even if they are not spec-compliant) and the hassle of adding extra argument `endian ="little"`,  I'd rather avoid any change of the existing API unless it is really necessary

**Comment by zbjornson** [comment]
Thanks @gfinak for the option. 👍
