### ISSUE TITLE
Use "gating.template" on data.table

### ISSUE THREAD

**Issue by kratschie** [RGLab/flowCore#78]
Hello,

I am working on a small app that allows the user to create a gating Template on html based textInput which is stored in an 'R' data.table(including all the needed columns). I would now like to use the opencyto's  `gating.Template()` function to use the Users Input for  automated gating without having the user saving the data.table as csv and read from there.

I could not find a way to read from data.table instead of csv. Is there a way?

Thanks!

**Comment by mikejiang** [comment]
Can you re-post it in `openCyto` issue page?
