### ISSUE TITLE
getIndexSort() returns the wrong sorting order

### ISSUE THREAD

**Issue by yannabraham** [RGLab/flowCore#80]
When sorting on 384-well plates using our FACSAriaIII, we get 16 "INDEX SORTING LOCATIONS"; when getIndexSort calls the .getLoc function, the line "locs<-locs[order(names(locs))]" will put locations 10 to 16 between locations 1 and 2; this can be fixed by replacing the above line with

locids <- strsplit(names(locs),'_')
locids <- unlist(lapply(locids,function(x) x[2]))
locids <- as.numeric(locids)
locs<-locs[order(locids)]

Hope this helps!

**Comment by gfinak** [comment]
Thanks @yannabraham
