### ISSUE TITLE
can't read flowset of fcs files from ZE5 instrument

### ISSUE THREAD

**Issue by AndyinMission** [RGLab/flowCore#83]
I can read individual files alright using read.FCS, but read.flowSet fails.

`myflowset <- read.flowSet(pattern = ".fcs", path = ".") #read all fcs files in current dir to flowset
Error in readFCSheader(con) : 
  This does not seem to be a valid FCS2.0, FCS3.0 or FCS3.1 file`

Please find 4 test files here:

https://drive.google.com/drive/folders/0B1ppj6LgpY6sNkhqLWFJdV9GTTg?usp=sharing

**Comment by mikejiang** [comment]
It doesn't seem to be flowCore related issue, rather the file/directory issue.
make sure your working directory is the correct folder you wanted. I don't have the problem to run your code on these files.

**Comment by AndyinMission** [comment]
Yes, it turns out this was a very silly mistake, I was saving report images and forgot to strip the extension from the name, so it was finding jpegs containing ".fcs" string.

**Comment by Jane-Xu1** [comment]
Maybe there are some other files that are not .fcs format in your folder.
