### ISSUE TITLE
flowCore fails to read a TIME parameter

### ISSUE THREAD

**Issue by jspidlen** [RGLab/flowCore#89]
I came across this file, seems to come from LSRII (BD FACSDiva Software Version 6.2) couple years ago, and flowCore fails to read the time channel values.

[LD2_PI+NS_B02_exp.fcs.zip](https://github.com/RGLab/flowCore/files/1462173/LD2_PI.NS_B02_exp.fcs.zip)

```
> library(flowCore)
> myFCS <- read.FCS("/Users/josef/Documents/TestData/FCS/PFICS/LD2_PI+NS_B02_exp.fcs")
> myFCS
flowFrame object 'fc98a17b-926a-4616-9668-bf601ef20303'
with 279202 cells and 14 observables:
           name     desc  range minRange maxRange
$P1       FSC-A     <NA> 262144     0.00   262143
$P2       FSC-H     <NA> 262144     0.00   262143
$P3       SSC-A     <NA> 262144     0.00   262143
$P4      AARD-A     Dead  82897   -31.50    82896
$P5    APC-H7-A   HLA-DR  82897   -61.56    82896
$P6     Ax488-A p-ERK1_2  82897   -25.50    82896
$P7     Ax647-A    Blank 262144   -28.88   262143
$P8     Ax700-A      CD3  82897   -33.44    82896
$P9        PE-A Perforin  82897   -46.08    82896
$P10   PE-Cy5-A     CD38  82897   -72.72    82896
$P11   PE-Cy7-A     IFNg  82897   -45.36    82896
$P12 PE-TxRed-A      CD4  82897   -47.52    82896
$P13  PacBlue-A      CD8  82897   -59.25    82896
$P14       Time     <NA>      0     0.00       -1
189 keywords are stored in the 'description' slot
> min(exprs(myFCS[,'Time']))
[1] 0
> max(exprs(myFCS[,'Time']))
[1] 0
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flowCore_1.45.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13        lattice_0.20-35     matrixStats_0.52.2 
 [4] mvtnorm_1.0-6       corpcor_1.6.9       rrcov_1.4-3        
 [7] grid_3.4.1          stats4_3.4.1        pcaPP_1.9-72       
[10] graph_1.56.0        robustbase_0.92-8   tools_3.4.1        
[13] Biobase_2.38.0      DEoptimR_1.0-8      parallel_3.4.1     
[16] compiler_3.4.1      BiocGenerics_0.24.0 cluster_2.0.6      
> 
```

Not sure if there is something wrong with the file itself, but FlowJo seems to read the time channel just fine.

![screen shot 2017-11-10 at 9 36 15 am](https://user-images.githubusercontent.com/431322/32671031-a5ad1f20-c5fa-11e7-85e4-65becc58a582.png)

I have also manually verified the time channel values by looking at the file in iHex and here are actual values present in the time channel: the first 3 events have time 0, the next 6 events have time 0.101064, then there are events with time 0.303193, etc.

![screen shot 2017-11-10 at 9 45 12 am](https://user-images.githubusercontent.com/431322/32671716-520b375a-c5fd-11e7-9e65-394bc6b8ec46.png)

![screen shot 2017-11-10 at 9 51 00 am](https://user-images.githubusercontent.com/431322/32671737-65f5a96c-c5fd-11e7-85e4-f2d0284abaae.png)

![screen shot 2017-11-10 at 9 51 31 am](https://user-images.githubusercontent.com/431322/32671742-6a90d956-c5fd-11e7-890c-4a826c371053.png)

**Comment by gfinak** [comment]
Thanks, we'll sort it out.

Greg Finak

**Comment by mikejiang** [comment]
It is due to the incorrect instrument range that has been set to `time` channel in `$PnR` keyword of FCS Text section
```bash
|$P14R|0|$P14N|Time
```
The same problem was reported and addressed here #37 , so simply turning off the default `truncate_max_range` flag will do
```r
> fr <- read.FCS("LD2_PI+NS_B02_exp.fcs", truncate_max_range = F)
> range(fr, "data")
     FSC-A  FSC-H  SSC-A   AARD-A  APC-H7-A  Ax488-A   Ax647-A   Ax700-A      PE-A
min      0  30019   1896    -31.5    -61.56   -25.50    -28.88    -33.44    -46.08
max 262143 262127 262143 219419.2 252767.64 30774.75 262143.00 262143.00 262143.00
     PE-Cy5-A PE-Cy7-A PE-TxRed-A PacBlue-A Time
min    -72.72   -45.36     -47.52    -59.25    0
max 262143.00 89460.73  249339.61 262143.00 9600
> head(exprs(fr)[,"Time"])
[1] 0.0000000 0.0000000 0.0000000 0.1010643 0.1010643 0.1010643
> library(ggcyto)
> autoplot(fr, "Time", "FSC-A")
```
![image](https://user-images.githubusercontent.com/1385649/32749312-db45190a-c873-11e7-833a-4705086462db.png)

**Comment by jspidlen** [comment]
Thanks!

**Comment by vtosevski** [comment]
I am somewhat late to this discussion but I just have a follow up question. I tend to constantly switch off `truncate_max_range` when reading in data and have also come across the same issue with Time seemingly not being there in the past. My understanding is that `truncate_max_range` would remove entire rows when one of the values is outside stated range. How come in this example it leaves all the rows and just skips a conflicting parameter. I would have expected that no events would be read in...?

**Comment by mikejiang** [comment]
Here is from `?read.FCS`
>>truncate_max_range   logical type. Default is TRUE. can be optionally turned off to avoid truncating the extreme positive value to the instrument measurement range .i.e.'$PnR'.

So it has nothing to do with deleting rows
