### ISSUE TITLE
Support for inverseLogicleTransform Applied to TransformList Object

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowCore#90]
Hi Greg and Mike,

I was wondering if there is any news or planned support for applying inverseLogicleTransform to a transformList object generated by estimateLogicle?

It would be great to have a quick way to reverse the logicle transformation when calculating population statistics (e.g. median fluorescent intensities).

Thanks.

Dillon

**Comment by mikejiang** [comment]
done! See example here https://github.com/RGLab/flowCore/blob/trunk/man/inverseLogicleTransform.Rd#L50-L55

**Comment by DillonHammill** [comment]
Thanks Mike that is excellent!
