### ISSUE TITLE
Support InverseLogicleTransform Applied to GatingSet Transformed with EstimateLogicle

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowCore#92]
Hi Greg and Mike,

Would it be possible to extent support for inverseLogicleTransform applied to a GatingSet transformed with estimateLogicle? 

`trans <- estimateLogicle(gs[[1]],channels)`
`class(trans)`
`[1] "transformerList" "list"`

Thanks.

Dillon

**Comment by mikejiang** [comment]
Depends on what you want to accomplish, if simply back transform the data, you can easily exact the `inverse` from the `transformer` object which already contains both `trans` and `inverse` functions
```r
> trans <- estimateLogicle(gs[[1]], c("CD4", "CD8"))
> trans
$`<B710-A>`
Transformer:  logicle 

$`<R780-A>`
Transformer:  logicle 

attr(,"class")
[1] "transformerList" "list"           
> str(trans[[1]])
List of 6
 $ name     : chr "logicle"
 $ transform:function (x)  
 $ inverse  :function (x)  
 $ breaks   :function (x)  
 $ format   :function (x)  
 $ domain   : num [1:2] -Inf Inf
 - attr(*, "class")= chr "trans"
```

**Comment by DillonHammill** [comment]
I just want be able to reverse the transformation post gating for analysis.

How would I apply the inverse transformation?

**Comment by mikejiang** [comment]
Can you provide the concrete examples (maybe in the form of code snippets) that illustrate your use cases before I decide if we need a new API for this?

**Comment by DillonHammill** [comment]
Here is an example of what I would like to achieve:

`fs <- read.flowSet()`
`SPILL <- fs[[1]]@description$SPILL`
channels <- colnames(SPILL)
`gs <- GatingSet(fs)`
`gs <- compensate(gs,SPILL)`
`trans <- estimateLogicle(gs[[1]],channels)`
`gs <- transform(gs,trans)`

I would then construct a openCyto gating template to identify specific populations (e.g. CD4 T Cells and CD8 T Cells), ideally I would like to reverse the transformation prior to extracting populations using getData():

`inv.trans <- inverseLogicleTransform(trans)`
`gs <- transform(gs,inv.trans)`

`CD4 <- getData(gs,"CD4 T Cells")`
`CD8 <- getData(gs,"CD8 T Cells")`

With the data back on a linear scale I can now calculate statistics (e.g. median fluorescent intensities):

CD4.MFI <- fsApply(CD4, each_col, median)
CD8.MFI <-  fsApply(CD4, each_col, median)

My current workaround is to compensate and transform the fs prior to loading into GatingSet, extract the populations using getData, inverse the transformation and generate statistics. The problem is that the transformation is not associated with the GatingSet (e.g. for use with scale_x_logicle() & axis_x_inverse_trans()).

**Comment by mikejiang** [comment]
`gs <- transform(gs,inv.trans)` will only transform the data and leave the gates unchanged, which makes your new `gs` invalid, especially when you try to visualize it.
You should inverse transform the subsetted data (i.e. `flowSets` CD4, CD8 in your example). 
So all you need to do is to iterate through `transformerList` to extract `inverse` functions and coerce them to `transformList`, with this `one-liner`
```r
inv <- transformList(names(trans), lapply(trans, `[[`, "inverse"))
```
Then
```r
CD4 <- transform(CD4, inv)
```

**Comment by DillonHammill** [comment]
That's excellent! Thanks Mike!

**Comment by vtosevski** [comment]
Hi Mike,

I too need to inverse transform the logicle transformed data to retrieve the original data. However, I am not sure how to do this based on the flowCore help and I also can't reproduce the steps you outlined above. I am using flowCore 1.44.1

I've estimated transform parameters with estimateLogicle:
lgcl <- estimateLogicle(fs[[rndm.indx]], channels = param.names[3:10])

result is
> class(lgcl)
[1] "transformList"
attr(,"package")
[1] "flowCore"

trying your code from above:
> str(lgcl[[1]])
Error in lgcl[[1]] : this S4 class is not subsettable

and I don't see in my transformList the $inverse you mention.

flowCore help says I need to supply the `transform` object to inverseLogicleTransform function, but estimateLogicle creates `transformList` already and I don't know how to "extract" the `transform` object from it.

Can you help with this?

Thanks,
Vinko

**Comment by mikejiang** [comment]
Please read the post and scripts carefully,
```r
trans <- estimateLogicle(gs[[1]],channels)
class(trans)
[1] "transformerList" "list"
```
Here we have `gs`, which is a `GatingSet` instead of `flowSet` (`fs` in your case), as the result, `estimateLogicle` method returns a  `transformerList` instead of  `transformList`. 
But your confusion is understandable given the similarity of the two APIs and this original question should have been posted at the better place (i.e. issue page of `flowWorkspace` package.)

Anyway, in your case, if you are only dealing with `flowSet`, in order to generate the `transformerList`, you can borrow the code from here https://github.com/RGLab/flowWorkspace/blob/trunk/R/GatingSet_Methods.R#L2347-L2354 to run on your `flowFrame`  (i.e. `fs[[rndm.indx]`).
