### ISSUE TITLE
Make addition of flowCore_$PnRMax keywords by write.FCS optional

### ISSUE THREAD

**Issue by zbjornson** [RGLab/flowCore#93]
`write.FCS` adds `flowCore_$PnRMax` keywords, which I don't want. It would be nice to be able to turn them off.

https://github.com/RGLab/flowCore/blob/f498f443ac8f7e60701f70998fb8d7f2be8ac046/R/IO.R#L1274-L1281

**Comment by mikejiang** [comment]
`flowCore_$PnRMax` records the range information for the the `flowFrame` that went through some kind of transformation. Turning if off can potentially create the discrepancy down the road and could be difficult to trace back the cause. So unless there is compelling reason to remove them, I'd leave it as it is.

**Comment by zbjornson** [comment]
I'm using `read.FCS(..., transformation = FALSE)`, so that doesn't apply in this case. What about only writing them if the frame was transformed?

**Comment by mikejiang** [comment]
In theory, `transformation` keyword should be set to `custom` once the frame was transformed, which could be used as a condition here. But I will have to double check to see if this assumption always holds (especially in the broader range of use cases) before making such change.

**Comment by mikejiang** [comment]
Ok. pull the latest fix and you shouldn't see those keywords if and only if `flowFrame` was **not ** transformed by `flowCore` , which typically happens in these circumstances below:
* implicitly transformed by `read.FCS` call with `transformation` argument set to `linearize` by default  
* explicit transformed by `transform` or `%on%` method
* transformed by `flowWorkspace::parseWorkspace`

**Comment by zbjornson** [comment]
Great, thanks for the fast fix! :)
