### ISSUE TITLE
"data is too long" error when import FCS file

### ISSUE THREAD

**Issue by dtelad11** [RGLab/flowCore#96]
I'm trying to import a mass cytometry FCS file post-debarcoding. I get the following error:

```
read.FCS(...)
uneven number of tokens: 683
The last keyword is dropped.
uneven number of tokens: 683
The last keyword is dropped.
Error in matrix(vals, ncol = nrCols, byrow = TRUE) : data is too long
```

I never encountered this issue -- do you happen to know what might be causing it?

Edit: Adding the `which.lines` parameter still leads to the same error.

**Comment by gfinak** [comment]
How many events does your file have?

Greg Finak

**Comment by dtelad11** [comment]
It's seven different files, between 20k and 500k events each. They're within the magnitude that I imported with `flowCore` in the past.

I suspect something about these files specifically is corrupted. Cytobank loads them, though, so I'm not sure what's going on. I will debug it, just wanted to make sure you did not encounter it beforehand before I start going into the IO code.

**Comment by mikejiang** [comment]
Would you please share the example FCS for the trouble shooting?

**Comment by dtelad11** [comment]
Sure -- could we connect via email? I'd rather not post it publicly. If that is an option, I am at el.ad.david.amir@gmail.com. Thanks!

**Comment by mikejiang** [comment]
It is the `SPILL` keyword that failed the `spillover` matrix construction. The FCS has this keyword set to non-empty string `"0,,". Now I am adding the check so that whenever the first number is 0 it will skip the `matrix` construction. Here is the result after the patch is applied
```r
> fr <- read.FCS("xxx.fcs")
> spillover(fr)
$SPILL
[1] "0,,"
> nrow(fr)
[1] 20985
```

**Comment by dtelad11** [comment]
Thank you!
