### ISSUE TITLE
Unable to install package using `devtools::install_github`

### ISSUE THREAD

**Issue by dtelad11** [RGLab/flowCore#97]
I'm not sure whether this is a `flowCore` issue or a github issue, apologies if the latter. I'm trying to install the package using `devtools::install_github`:

```
> devtools::install_github('RGLab/flowCore')
Downloading GitHub repo RGLab/flowCore@master
from URL https://api.github.com/repos/RGLab/flowCore/zipball/master
Installation failed: 404: Not Found
 (404)
```

I never encountered the error before and Google search doesn't come up with anything, so I'm not sure what's wrong. Also tried forking the package, getting same here on the fork.

Edit: Also tried mirroring the repo, I get the same error.

**Comment by gfinak** [comment]
Pull from the trunk branch, not the master branch. install_github()
defaults to the master branch, but there is no master branch.

Greg Finak

**Comment by dtelad11** [comment]
Understood, thank you!
