### ISSUE TITLE
Skip linearization transform on the FCS that has the non-zero $PnE values but stored as float

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowCore#99]
Currently, FCS parser tries to transform the data back to linear scale when it sees the non-zero `$PnE` based on the standard
>$PnE/f1,f2/ $P3E/4.0,0.01/ [REQUIRED]
This keyword specifies whether parameter number n is stored on linear or logarithmic scale and
includes details about the logarithmic amplification if logarithmic scale is used. 
When linear scale is used, $PnE/0,0/ shall be entered. 

However we've encountered some FCS file that apparently doesn't follow the standard. That is keyword says it needs to be transformed to linear scale
```r
> keyword(fr)["$P1E"]
$`$P1E`
[1] "4.07918,1"

```
but the data s actually already stored at linear scale, which caused the parser to inappropriately transform the data. 

Right now, user can prevent it by forcing `transformation = FALSE`. But it was hard for one to figure out the exact cause since the FCS parser would silent do its job and leave users clueless after they see the non-sense results down the road.(such as the flowJo workspace parsing error that @ptvan is puzzled by)

So it would be good if we can fix it automatically by the parser.

I found this clause after further looking into the standards, 
>If the floating point data type is used
(either $DATATYPE/F/ or $DATATYPE/D/), then all parameters shall be stored as linear with
$PnE/0,0/. 

Question is whether we can trust that data type always precedes the `PnE` keyword in terms of deciding data scale @gfinak @jspidlen ?

**Comment by jspidlen** [comment]
Hi Mike, guys,

Question is whether we can trust that data type always precedes the PnE
> keyword in terms of deciding data scale


1) Well, I don't know if it's fair to say "doesn't follow the standard"
because that sentence that you are referring to was added in FCS 3.1 and I
bet the file that you are talking about was FCS 3.0 :-)
2) Nevertheless, it makes little sense to use $PnE other than 0,0 for
floating point data types. For FCS files exported from FlowJo, you can
trust that data type always precedes the $PnE keyword in terms of deciding
data scale.
3) Certain FCS exports from older versions of FlowJo resulted in the
anomaly that you are describing here, but it has been addressed as of
FlowJo 10.4.2. So this shouldn't be coming up unless people are using older
versions of FlowJo or files exported from older versions of FlowJo... which
I guess is possible so it would still make sense if flowCore just
considered $PnE to be "0,0" for $DATATYPE/F/ and $DATATYPE/D/.

Thanks,
Josef

**Comment by mikejiang** [comment]
@jspidlen , Thanks for the confirmation. I will go ahead to make such change.

**Comment by bubblesweety** [comment]
Hi

I just started to use FlowCore to analyze our _pre-gated FCS files off FlowJo_. 

One thing I noticed is that after read.fcs() with the default transformation="linearize", all of my -A channel values got really small and the value distribution looks very strange. See attached plots with and without the default linearization.
It seems to me that it doesnt make sense to shrink all values so much, mostly [0,1]. I searched around and saw very few related articles and there was just this one post.

Our fcs files are 3.0 and our flowjo is 10.4.1. 
![distribution_cpg3_no_linearization](https://user-images.githubusercontent.com/14580409/41435736-aa1a0256-6fd4-11e8-86f1-4ec06a277877.png)
![distribution_cpg3_after_linearization](https://user-images.githubusercontent.com/14580409/41435737-aa482f50-6fd4-11e8-8d51-5a005f6dd8f9.png)

**Comment by SamGG** [comment]
Hi,
What the range look like? Report pData(theFlowFrame).
Best

**Comment by jspidlen** [comment]
Can you upgrade to FlowJo 10.4.2? We have made some changes in FCS export
in FlowJo 10.4.2 to make it work better with R/flowCore.
Let me know if that helps.

Cheers,
Josef

-- 
Josef Spidlen, Ph.D. | josefs@flowjo.com
Director of Bioinformatics | FlowJo, LLC
385 Williamson Way
Ashland, OR 97520  USA

**Comment by bubblesweety** [comment]
sorry that I accidental deleted my original post, so I am posting here again, now also with the data range information.


I just started to use FlowCore to analyze our pre-gated FCS files off FlowJo.

One thing I noticed is that after read.fcs() with the default transformation="linearize", all of my -A channel values got really small and the value distribution looks very strange. See attached plots with and without the default linearization.
It seems to me that it doesnt make sense to shrink all values so much, mostly [0,1]. I searched around and saw very few related articles and there was just this one post.

Our fcs files are 3.0 and our flowjo is 10.4.1.

Without linearization, transformation=FALSE:
Keyword output looks like this:
$P1E "0,0"
$P2E "0,0"
$P3E "0,0"
$P4E "5.22472,100"

![distribution_cpg3_no_linearization](https://user-images.githubusercontent.com/14580409/41440242-af32d9c6-6fe2-11e8-90f3-ceb83ae5d68b.png)

![no-linearization](https://user-images.githubusercontent.com/14580409/41440481-81c96ddc-6fe3-11e8-8888-fa83c502abad.png)



With linearization, transformation="linearize":
![distribution_cpg3_after_linearization](https://user-images.githubusercontent.com/14580409/41440257-c06171da-6fe2-11e8-9e3b-a24fa659b1ee.png)

![after-linearization](https://user-images.githubusercontent.com/14580409/41440486-8620b750-6fe3-11e8-840c-0e5debfa835b.png)

**Comment by bubblesweety** [comment]
Can someone possibly explain this keyword output:
$P1E "0,0"
$P2E "0,0"
$P3E "0,0"
$P4E "5.22472,100"

How come the $P4E "5.22472,100" seem to be so different from the FlowCore example $P4E "4,0"? 
So this is basically from the FACS machine or FlowJo software to mark the value being linear or log? 

Is there a way to see whether the linearization should or should not be done, based on keyword?
thanks!

**Comment by jspidlen** [comment]
Thanks for the additional details.
1) I am pretty sure this confirms that you are seeing a problem that has
been reported and fixed before. You have 2 options, either set
transformations=FALSE in read.FCS; or use FlowJo 10.4.2 to export the FCS
file. Either of those should work just fine.
2) Yes, the value of the $PnE keyword specifies log vs. linear scale;
details can be found in the FCS spec (e.g.,
http://isac-net.org/Resources/Standards/FCS3-1.aspx).

Hope that helps,
Josef

**Comment by bubblesweety** [comment]
Hi. I asked my collaborator to upgrade to 10.4.2 and he pre-gated again and exported from FlowJo 10.4.2 and now I have a new error:
 "..." is not a valid file.

I wanted to ask if FlowCore read.fcs() also rely on the types of the FACS machine.  We are currently using APD CytoFlex... would this be a potential problem for reading the .fcs files? Is FlowCore more suited for  BD machines?

**Comment by mikejiang** [comment]
post  `traceback()` immediately after the error as well as `sessioninfo`, also maybe attache the example file ?

**Comment by bubblesweety** [comment]
> traceback()
4: stop(paste("'", filename, "' is not a valid file", sep = ""))
3: FUN(X[[i]], ...)
2: lapply(files, read.FCS, alter.names = alter.names, transformation = transformation, 
       which.lines = which.lines, column.pattern = column.pattern, 
       invert.pattern = invert.pattern, decades = decades, min.limit = min.limit, 
       emptyValue = emptyValue, ignore.text.offset = ignore.text.offset, 
       dataset = dataset, truncate_max_range = truncate_max_range)
1: flowCore::read.flowSet(fcs_info$fcs_files, transformation = "linearize", 
       alter.names = FALSE, truncate_max_range = FALSE)


> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /AQG/apps/R/rh7/R-3.4.2/lib64/R/lib/libRblas.so
LAPACK: /AQG/apps/R/rh7/R-3.4.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reshape_0.8.7  ggplot2_2.2.1  MetaCyto_1.4.0 tidyr_0.8.0    dplyr_0.7.5   

loaded via a namespace (and not attached):
 [1] pcaPP_1.9-73                Rcpp_0.12.16                RColorBrewer_1.1-2         
 [4] plyr_1.8.4                  pillar_1.2.3                compiler_3.4.2             
 [7] DEoptimR_1.0-8              bindr_0.1.1                 tools_3.4.2                
[10] nlme_3.1-137                gtable_0.2.0                tibble_1.4.2               
[13] lattice_0.20-35             pkgconfig_2.0.1             rlang_0.2.0                
[16] Matrix_1.2-14               graph_1.56.0                igraph_1.2.1               
[19] yaml_2.1.16                 parallel_3.4.2              mvtnorm_1.0-7              
[22] bindrcpp_0.2.2              metafor_2.0-0               cluster_2.0.7-1            
[25] stats4_3.4.2                grid_3.4.2                  tidyselect_0.2.4           
[28] glue_1.2.0                  robustbase_0.93-0           Biobase_2.38.0             
[31] R6_2.2.2                    rrcov_1.4-4                 XML_3.98-1.11              
[34] FlowSOM_1.10.0              pheatmap_1.0.10             fastcluster_1.1.25         
[37] purrr_0.2.5                 corpcor_1.6.9               magrittr_1.5               
[40] scales_0.5.0                matrixStats_0.53.1          ConsensusClusterPlus_1.42.0
[43] BiocGenerics_0.24.0         assertthat_0.2.0            colorspace_1.3-2           
[46] tsne_0.1-3                  flowCore_1.44.2             lazyeval_0.2.1             
[49] munsell_0.4.3              


files are too big for the upload here... can I send you via google drive? thanks!

**Comment by bubblesweety** [comment]
​
 export_01-TCellPanelIso-A1.fcs.zip
<https://drive.google.com/file/d/1hXQxlDla52Xl-tmLF3Gx4jlk-WQ4ujKK/view?usp=drive_web>
​

**Comment by jspidlen** [comment]
I think your fcs_info$fcs_files is empty or something, how did you create
it? I can read your file with flowCore no problem, i.e.,

> library(flowCore)
> x <- read.FCS('Downloads/export_01-TCellPanelIso-A1.fcs')
> x
flowFrame object 'export_01-TCellPanelIso-A1.fcs'
with 752208 cells and 38 observables:
              name               desc    range minRange maxRange
$P1          FSC-A              FSC-A  4417965        0  4417964
$P2          FSC-H              FSC-H  4016331        0  4016330
$P3      FSC-Width          FSC-Width    10000        0     9999
$P4          SSC-A              SSC-A 16777215        0 16777214
$P5          SSC-H              SSC-H 16777215        0 16777214
$P6   FJComp-FL1-A        CD19 FITC-A 16777215     -111 16777214
$P7   FJComp-FL1-H        CD19 FITC-H 16777215     -111 16777214
$P8  FJComp-FL10-A    CD44 Alexa700-A 16777215     -111 16777214
$P9  FJComp-FL10-H    CD44 Alexa700-H 16777215     -111 16777214
$P10 FJComp-FL11-A       CD8 APCCy7-A 16777215     -111 16777214
$P11 FJComp-FL11-H       CD8 APCCy7-H 16777215     -111 16777214
$P12 FJComp-FL12-A       41BB BV421-A 16777215     -111 16777214
$P13 FJComp-FL12-H       41BB BV421-H 16777215     -111 16777214
$P14 FJComp-FL13-A       CD45 BV510-A 16777215     -111 16777214
$P15 FJComp-FL13-H       CD45 BV510-H 16777215     -111 16777214
$P16 FJComp-FL14-A        CD3 BV605-A 16777215     -111 16777214
$P17 FJComp-FL14-H        CD3 BV605-H 16777215     -111 16777214
$P18 FJComp-FL15-A      NKp46 BV711-A 16777215     -111 16777214
$P19 FJComp-FL15-H      NKp46 BV711-H 16777215     -111 16777214
$P20 FJComp-FL16-A       PD-1 BV786-A 16777215     -111 16777214
$P21 FJComp-FL16-H       PD-1 BV786-H 16777215     -111 16777214
$P22 FJComp-FL17-A    Thy1.2 BUV395-A 16777215     -111 16777214
$P23 FJComp-FL17-H    Thy1.2 BUV395-H 16777215     -111 16777214
$P24 FJComp-FL18-A       CD4 BUV496-A 16777215     -111 16777214
$P25 FJComp-FL18-H       CD4 BUV496-H 16777215     -111 16777214
$P26 FJComp-FL21-A   L_D LiveDeadIR-A 16777215     -111 16777214
$P27 FJComp-FL21-H   L_D LiveDeadIR-H 16777215     -111 16777214
$P28  FJComp-FL3-A KLRG1 PerCPCy5.5-A 16777215     -111 16777214
$P29  FJComp-FL3-H KLRG1 PerCPCy5.5-H 16777215     -111 16777214
$P30  FJComp-FL4-A         Ki-67 PE-A 16777215     -111 16777214
$P31  FJComp-FL4-H         Ki-67 PE-H 16777215     -111 16777214
$P32  FJComp-FL5-A      OX40 PETxRd-A 16777215     -111 16777214
$P33  FJComp-FL5-H      OX40 PETxRd-H 16777215     -111 16777214
$P34  FJComp-FL8-A       ICOS PECy7-A 16777215     -111 16777214
$P35  FJComp-FL8-H       ICOS PECy7-H 16777215     -111 16777214
$P36  FJComp-FL9-A        FoxP3 APC-A 16777215     -111 16777214
$P37  FJComp-FL9-H        FoxP3 APC-H 16777215     -111 16777214
$P38          Time               Time      302        0      301
837 keywords are stored in the 'description' slot
>

**Comment by mikejiang** [comment]
check `fcs_info$fcs_files` to see if they are all valid fcs files

**Comment by bubblesweety** [comment]
Very strange... here is my code. it looks like there are valid files... 

>fcs_info=read.csv("facs_liveCD45+_FlowJo10.4.2_Peter/fcs_info.csv",stringsAsFactors=F,check.names=F)
> print(fcs_info)
                                                         fcs_files study_id
1 facs_liveCD45+_FlowJo10.4.2_Peter/export_01-TcellPanelIso-A1.fcs     test
> test_linearize = flowCore::read.flowSet(fcs_info$fcs_files, transformation = "linearize", 
+                              alter.names = FALSE, truncate_max_range = FALSE)
Error in FUN(X[[i]], ...) : 
  'facs_liveCD45+_FlowJo10.4.2_Peter/export_01-TcellPanelIso-A1.fcs' is not a valid file

**Comment by mikejiang** [comment]
Is `facs_liveCD45+_FlowJo10.4.2_Peter/export_01-TcellPanelIso-A1.fcs` a right path relative to you current working directory?

**Comment by bubblesweety** [comment]
thanks guys for all your help... it was a path/file name issue... sorry! 
But I just wanted to update that FlowJo 10.4.2 pregated .fcs files work beautifully with FlowCore. Maybe you could mention this in FlowCore github page... 

thanks again

**Comment by jspidlen** [comment]
Thanks Eva,
Glad that you were able to resolve it :-).

Cheers, Josef

**Comment by bubblesweety** [comment]
Hi Mike

I wanted to ask what the best practice is for the negative values in .fcs
files.

After read.fcs(), I noticed that there are some negative values, e.g.
-54707, in my fcs files. For downstream analysis in the facs data field, do
people normally exclude the negative values, prior to arcsign
transformations ?

thanks and happy July 4th!

**Comment by gfinak** [comment]
Did you intend to attach a figure?

**Comment by bubblesweety** [comment]
I thought It was pasted in the email,but here is the attachment again.
thanks!

**Comment by gfinak** [comment]
I guess the email interface is stripping it. Try pasting it directly online via github.
